INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(2334913, 'UPPER MERION AREA SCHOOL DISTRICT MONTGOMERY COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(2334918, 'SPROTT URANIUM MINERS ETF', 'None', 'N/A', NOW()),
(2334940, 'PITTSBURGH WATER AND SEWER AUTHORITY', 'None', 'N/A', NOW()),
(2334970, 'HAYWARD HOLDINGS INC', 'None', 'Industrials', NOW()),
(2335002, 'ALVARADO INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2335097, 'PDD HOLDINGS INC', 'None', 'ConsumerDiscretionary', NOW()),
(2335120, 'DAYS BETWEEN, LLC', 'None', 'N/A', NOW()),
(429829, 'ARIZONA STATE LOTTERY', 'None', 'N/A', NOW()),
(429837, 'ARLINGTON COUNTY VIRGINIA', 'None', 'N/A', NOW()),
(430034, 'BDT SUNRISE HOLDINGS LLC', 'None', 'N/A', NOW()),
(430197, 'BP CAPITAL MARKETS PLC', 'None', 'N/A', NOW()),
(430322, 'CALIFORNIA INFRASTRUCTURE AND ECONOMIC DEVELOPMENT BANK', 'None', 'N/A', NOW()),
(430446, 'CELANESE US HOLDINGS LLC', 'None', 'N/A', NOW()),
(430493, 'CHARTER TOWNSHIP OF WEST BLOOMFIELD', 'None', 'N/A', NOW()),
(430559, 'CINCINNATI CITY SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430594, 'CITY OF BALTIMORE MARYLAND', 'None', 'N/A', NOW()),
(430610, 'CITY OF CAPE CORAL FLORIDA', 'None', 'N/A', NOW()),
(430618, 'CITY OF CHICAGO', 'None', 'N/A', NOW()),
(430649, 'CITY OF FORT WORTH TEXAS', 'None', 'N/A', NOW()),
(430657, 'CITY OF GREEN BAY WISCONSIN', 'None', 'N/A', NOW()),
(430693, 'CITY OF LOS ANGELES', 'None', 'N/A', NOW()),
(430724, 'CITY OF ORLANDO FLORIDA', 'None', 'N/A', NOW()),
(430768, 'TACOMA CITY OF WASHINGTON', 'None', 'N/A', NOW()),
(430775, 'CITY OF TOMBALL TEXAS', 'None', 'N/A', NOW()),
(430779, 'CITY OF TULSA OKLAHOMA', 'None', 'N/A', NOW()),
(430821, 'CLEVELAND COUNTY EDUCATIONAL FACILITIES AUTHORITY', 'None', 'N/A', NOW()),
(430909, 'COLUMBUS CITY SCHOOL DISTRICT FRANKLIN COUNTY OHIO', 'None', 'N/A', NOW()),
(2334936, 'HIMS & HERS HEALTH INC', 'XLV', 'Healthcare', NOW()),
(2334956, 'SPDR LONG DOLLAR GOLD TRUST', 'GLD', 'N/A', NOW()),
(2335022, 'PROSHARES ULTRAPRO QQQ', 'QQQ', 'N/A', NOW()),
(429504, 'Advanced Energy Industries Inc', 'XLE', 'InformationTechnology', NOW()),
(429588, 'Algonquin Power & Utilities Corp', 'XLU', 'Utilities', NOW()),
(430226, 'Brighthouse Financial Inc', 'XLF', 'Financials', NOW()),
(430498, 'Check Point Software Technologies Ltd', 'XLK', 'InformationTechnology', NOW()),
(430819, 'Clearway Energy Inc', 'XLE', 'Utilities', NOW()),
(2334641, 'VAXXINITY INC', 'CVAXX', 'Healthcare', NOW()),
(2334666, 'VANGUARD TAX-EXEMPT BOND ETF', 'FVTEB', 'N/A', NOW()),
(2334798, 'FIRST TRUST SMID CAP RISING DIVIDEND ACHIEVERS ETF', 'FSDVY', 'N/A', NOW()),
(2334835, 'FIRST TR GLOBAL TACTICAL CMD', 'DFTGC', 'N/A', NOW()),
(2334942, 'VIKING HOLDINGS LTD', 'TDVIK', 'ConsumerDiscretionary', NOW()),
(2335114, 'FIGMA INC', 'NCFIG', 'InformationTechnology', NOW()),
(2335157, 'NEW WORLD FUND INC', 'RNWGX', 'N/A', NOW()),
(429437, 'AAON Inc', 'AAON', 'Industrials', NOW()),
(429450, 'AB GLOBAL BOND FUND INC', 'ANAGX', 'N/A', NOW()),
(429515, 'Aegon NV', 'NVAEG', 'Financials', NOW()),
(429587, 'Alfa Laval AB', 'ALFVY', 'Industrials', NOW()),
(429690, 'AMERICAN FUNDS SMALLCAP WORLD FUND', 'SMCWX', 'N/A', NOW()),
(429697, 'American Homes 4 Rent', 'AMH', 'RealEstate', NOW()),
(429722, 'American Eagle Outfitters Inc', 'AEO', 'ConsumerDiscretionary', NOW()),
(429752, 'AngioDynamics Inc', 'ANGO', 'Healthcare', NOW()),
(429771, 'APA Corporation', 'APA', 'Energy', NOW()),
(429777, 'APi Group Corp', 'APG', 'Industrials', NOW()),
(429809, 'Arcelormittal SA', 'SAMT', 'Materials', NOW()),
(429836, 'ARK ETF Trust - ARK Innovation ETF', 'FARKK', 'N/A', NOW()),
(429842, 'Armstrong World Industries Inc', 'AWI', 'Industrials', NOW()),
(429856, 'Asbury Automotive Group Inc', 'ABG', 'ConsumerDiscretionary', NOW()),
(429931, 'Autoliv Inc', 'ALV', 'ConsumerDiscretionary', NOW()),
(429933, 'AutoNation Inc', 'AN', 'ConsumerDiscretionary', NOW()),
(429958, 'Axa, Paris', 'AXAHY', 'Financials', NOW()),
(429986, 'Banco Santander SA', 'SASAN', 'Financials', NOW()),
(430031, 'BCE Inc', 'BCE', 'CommunicationServices', NOW()),
(430043, 'BeiGene Ltd', 'BGNE', 'Healthcare', NOW()),
(430099, 'Black Hills Corp', 'BKH', 'Utilities', NOW()),
(430268, 'Bruker Corporation', 'BRKR', 'Healthcare', NOW()),
(430343, 'Cameco Corp', 'CCJ', 'Energy', NOW()),
(430362, 'Canon Inc', 'CAJ', 'InformationTechnology', NOW()),
(430366, 'Capgemini SE', 'CGEMY', 'InformationTechnology', NOW()),
(430390, 'CarGurus Inc', 'CARG', 'CommunicationServices', NOW()),
(430419, 'CATALYST MILLBURN HEDGE STRATEGY FUND', 'MBXIX', 'N/A', NOW()),
(430456, 'Permian Resources Corporation', 'PR', 'Energy', NOW()),
(430464, 'Central Garden & Pet Co', 'CENT', 'ConsumerStaples', NOW()),
(430516, 'Chewy Inc', 'CHWY', 'ConsumerDiscretionary', NOW()),
(430550, 'Cie Financiere Richemont AG, Zug', 'CFRUY', 'ConsumerDiscretionary', NOW()),
(430567, 'Cirrus Logic Inc', 'CRUS', 'InformationTechnology', NOW()),
(430800, 'Clarivate PLC', 'CCLVT', 'Industrials', NOW()),
(430853, 'Coca Cola Consolidated Inc', 'COKE', 'ConsumerStaples', NOW()),
(430882, 'DigitalBridge Group Inc', 'DBRG', 'Financials', NOW()),
(430997, 'CORPUS CHRISTI INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431073, 'COUNTY OF SAN DIEGO', 'None', 'N/A', NOW()),
(431076, 'COUNTY OF SANTA CLARA CALIFORNIA', 'None', 'N/A', NOW()),
(431077, 'COUNTY OF SCHENECTADY NEW YORK', 'None', 'N/A', NOW()),
(431239, 'DEPARTMENT OF EDUCATION SOUTH CAROLINA', 'None', 'N/A', NOW()),
(431242, 'DEPARTMENT OF WATER AND POWER OF CITY OF LOS ANGELES', 'None', 'N/A', NOW()),
(431392, 'EASTON AREA SCHOOL DISTRICT NORTHAMPTON AND BUCKS COUNTIES PENNSYLVANIA', 'None', 'N/A', NOW()),
(431617, 'FALCON EDGE GLOBAL LP', 'None', 'N/A', NOW()),
(431901, 'FULTON COUNTY GEORGIA', 'None', 'N/A', NOW()),
(432072, 'GRANT COUNTY PUBLIC UTILITY DISTRICT', 'None', 'N/A', NOW()),
(432087, 'GREATER ORLANDO AVIATION AUTHORITY', 'None', 'N/A', NOW()),
(432183, 'HARTSFIELD JACKSON INTERNATIONAL AIRPORT CITY OF ATLANTA GEORGIA', 'None', 'N/A', NOW()),
(432335, 'HUDSON YARDS INFRASTRUCTURE CORP', 'None', 'N/A', NOW()),
(432379, 'ILLINOIS HOUSING DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(432396, 'COUNTY OF TULSA', 'None', 'N/A', NOW()),
(432779, 'JOHNSON COUNTY COMMUNITY COLLEGE', 'None', 'N/A', NOW()),
(432857, 'KENTUCKY INFRASTRUCTURE AUTHORITY', 'None', 'N/A', NOW()),
(432859, 'KENTUCKY RURAL WATER FINANCE CORP', 'None', 'N/A', NOW()),
(432885, 'KING COUNTY WASTEWATER TREATMENT DIVISION', 'None', 'N/A', NOW()),
(433008, 'LEXINGTON FAYETTE URBAN COUNTY GOVERNMENT KENTUCKY', 'None', 'N/A', NOW()),
(433113, 'LOS ANGELES UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433119, 'LOWER COLORADO RIVER AUTHORITY', 'None', 'N/A', NOW()),
(431708, 'First Financial Bankshares Inc', 'XLF', 'Financials', NOW())
ON CONFLICT (id) DO NOTHING;