INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(2332647, 'UNIVERSITY OF WASHINGTON', 'None', 'N/A', NOW()),
(2333665, 'FLORIDA STATE TURNPIKE AUTHORITY', 'None', 'N/A', NOW()),
(2333863, 'CITIGROUP GLOBAL MKTS HLDGS', 'None', 'Financials', NOW()),
(2333969, 'CITY OF STAMFORD CONNECTICUT', 'None', 'N/A', NOW()),
(2333986, 'ECHO STREET GOODCO SELECT LP', 'None', 'N/A', NOW()),
(2334075, 'WINK-LOVING INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334127, 'SAN MIGUEL COUNTY COLORADO', 'None', 'N/A', NOW()),
(2334129, 'MASSACHUSETTS PORT AUTHORITY', 'None', 'N/A', NOW()),
(2334140, 'WEST VIRGINIA PARKWAYS AUTHORITY', 'None', 'N/A', NOW()),
(2334341, 'OKLAHOMA CAPITOL IMPROVEMENT AUTHORITY', 'None', 'N/A', NOW()),
(2334408, 'WEST HEMPSTEAD UNION FREE SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334419, 'COUNTY OF (MARYLAND) ANNE ARUNDEL', 'None', 'N/A', NOW()),
(2334420, 'ERP OPERATING LP', 'None', 'N/A', NOW()),
(2334424, 'ELLIOTT ASSOCIATES LP', 'None', 'N/A', NOW()),
(2334515, 'CORVEX DYNAMIC EQUITY SELECT LLC', 'None', 'N/A', NOW()),
(2334533, 'KERR COUNTY TEXAS', 'None', 'N/A', NOW()),
(2334563, 'COUNTY OF OSCEOLA FLORIDA', 'None', 'N/A', NOW()),
(2334571, 'POCONO MOUNTAIN SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334573, 'CITY OF KAUKAUNA', 'None', 'N/A', NOW()),
(2334590, 'GARNET VALLEY SCHOOL DISTRICT DELAWARE COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(2334602, 'UNIVERSITY OF KANSAS HOSPITAL AUTHORITY', 'None', 'N/A', NOW()),
(2334607, 'M2G STONE OAK LTD', 'None', 'N/A', NOW()),
(2334618, 'COUNTY OF SPOTSYLVANIA VIRGINIA', 'None', 'N/A', NOW()),
(435620, 'Vanguard Real Estate ETF', 'VNQ', 'N/A', NOW()),
(435927, 'WISCONSIN HEALTH AND EDUCATIONAL FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(2332000, 'JPMORGAN EQUITY PREMIUM INCOME ETF', 'JPM', 'N/A', NOW()),
(2333610, 'Tortoise Energy Infrastructure Corp', 'XLE', 'N/A', NOW()),
(2333854, 'GOLD FIELDS LTD', 'GLD', 'Materials', NOW()),
(2333909, 'URANIUM ENERGY CORP', 'XLE', 'Energy', NOW()),
(2334033, 'GOLDEN OCEAN GROUP', 'GLD', 'Industrials', NOW()),
(2334040, 'CRESCENT ENERGY CO', 'XLE', 'Energy', NOW()),
(2334454, 'COMMUNITY FINANCIAL SYST INC', 'XLF', 'Financials', NOW()),
(2334475, 'RHEINMETALL AG', 'META', 'Industrials', NOW()),
(2334531, 'LIBERTY MEDIA LIBERTY LIVE', 'DIA', 'CommunicationServices', NOW()),
(435439, 'UFP Industries Inc', 'UFPI', 'Industrials', NOW()),
(435440, 'UGI Corp', 'UGI', 'Utilities', NOW()),
(435465, 'United Bankshares Inc', 'UBSI', 'Financials', NOW()),
(435579, 'VanEck Retail ETF', 'TFRTH', 'N/A', NOW()),
(435597, 'Vanguard FTSE Emerging Markets ETF', 'TFVWO', 'N/A', NOW()),
(435635, 'Vanguard Total Bond Market ETF', 'TFBND', 'N/A', NOW()),
(435750, 'Volkswagen AG', 'VWAGY', 'ConsumerDiscretionary', NOW()),
(435838, 'WESCO International Inc', 'WCC', 'Industrials', NOW()),
(435868, 'Western Union Co', 'WU', 'Financials', NOW()),
(435885, 'WEX Inc', 'WEX', 'Financials', NOW()),
(435915, 'WillScot Mobile Mini Holdings Corp', 'WSC', 'Industrials', NOW()),
(2291462, 'The Buckle Inc', 'BKE', 'ConsumerDiscretionary', NOW()),
(2331333, 'Concentrix Corp', 'CNXC', 'Industrials', NOW()),
(2331385, 'Paycor HCM Inc', 'PYCR', 'Industrials', NOW()),
(2331436, 'iShares MSCI Emerging Markets ex China ETF', 'FEMXC', 'N/A', NOW()),
(2331456, 'Instructure Holdings Inc', 'INST', 'InformationTechnology', NOW()),
(2331508, 'Ecopetrol SA', 'SAEC', 'Energy', NOW()),
(2331681, 'DT Midstream Inc', 'DTM', 'Energy', NOW()),
(2332061, 'National Bank of Canada', 'NTIOF', 'Financials', NOW()),
(2332214, 'Li Auto Inc', 'LI', 'ConsumerDiscretionary', NOW()),
(2332364, 'Mowi ASA', 'MHGVY', 'ConsumerStaples', NOW()),
(2332594, 'Ajinomoto Co Inc', 'AJINY', 'ConsumerStaples', NOW()),
(2332923, 'VanEck Vectors Agribusiness ETF', 'TFMOO', 'N/A', NOW()),
(2333399, 'Sompo Holdings Inc', 'SMPNY', 'Financials', NOW()),
(2333434, 'Via Renewables Inc', 'VIA', 'Utilities', NOW()),
(2333438, 'Tellurian Inc', 'TELL', 'Energy', NOW()),
(2333456, 'Phillips Edison & Company Inc', 'PECO', 'RealEstate', NOW()),
(2333585, 'Alteryx Inc', 'AYX', 'InformationTechnology', NOW()),
(2333592, 'XP Inc', 'XP', 'Financials', NOW()),
(2333666, 'BlackRock Utility and Infrastructure Trust', 'BUI', 'N/A', NOW()),
(2333993, 'CASSAVA SCIENCES INC', 'CSAVA', 'Healthcare', NOW()),
(2333996, 'INNOVATIVE INDUSTRIAL PPTYS', 'SIIPR', 'RealEstate', NOW()),
(2334022, 'JOHN HANK MLTFTR ERG MT ETF', 'FJHEM', 'N/A', NOW()),
(2334124, 'CHAMPLAIN SMALL COMPANY FUND', 'CIPNX', 'N/A', NOW()),
(2334150, 'JUST EAT TAKEAWAY.COM N.V.', 'JTKWY', 'ConsumerDiscretionary', NOW()),
(2334161, 'FIDELITY MID CAP INDEX FUND', 'FSMDX', 'N/A', NOW()),
(2334229, 'KIRIN HOLDINGS CO LTD', 'KNBWY', 'ConsumerStaples', NOW()),
(2334281, 'M3 INC', 'MTHRY', 'Healthcare', NOW()),
(2334283, 'MITSUI OSK LINES LTD', 'MSLOY', 'Industrials', NOW()),
(2334286, 'NOMURA RESEARCH INSTITUTE', 'NRILY', 'InformationTechnology', NOW()),
(2334288, 'OCADO GROUP PLC', 'OCDDY', 'ConsumerStaples', NOW()),
(2334290, 'QANTAS AIRWAYS LTD', 'QABSY', 'Industrials', NOW()),
(2334293, 'SEEK LTD', 'SKLTY', 'CommunicationServices', NOW()),
(2334295, 'TERUMO CORP', 'TRUMY', 'Healthcare', NOW()),
(2334296, 'TOTO LTD', 'TOTDY', 'Industrials', NOW()),
(2334380, 'FIDELITY MID CAP STOCK FUND', 'FMCSX', 'N/A', NOW()),
(2334503, 'ISHARES SHORT TREAS BD ETF', 'TFSHV', 'N/A', NOW()),
(2334512, 'COLUMBIA EM CORE EX-CHN ETF', 'FXCEM', 'N/A', NOW()),
(2334584, 'SANDOZ GROUP AG', 'SDZNY', 'Healthcare', NOW()),
(2334620, 'THE UNIVERSITY OF VIRGINIA', 'None', 'N/A', NOW()),
(2334624, 'LKCM HEADWATER INVESTMENTS IV LP', 'None', 'N/A', NOW()),
(2334665, 'RAC OPPORTUNITY FUND II LP', 'None', 'N/A', NOW()),
(2334672, 'VALIANT CAPITAL PARTNERS LP', 'None', 'N/A', NOW()),
(2334682, 'ALPINE INVESTORS IX LP', 'None', 'N/A', NOW()),
(2334702, 'ZTO EXPRESS CAYMAN INC', 'None', 'Industrials', NOW()),
(2334704, 'HILLMAN SOLUTIONS CORP', 'None', 'Industrials', NOW()),
(2334706, 'AMERICA FIRST NATURAL RESOURCES LLC', 'None', 'N/A', NOW()),
(2334771, 'THE GRAPH', 'None', 'N/A', NOW()),
(2334832, 'GOING DOWN THE ROAD FEELING BAD LLC', 'None', 'N/A', NOW()),
(2334844, 'MIAMI UNIVERSITY', 'None', 'N/A', NOW()),
(2334848, 'Public Power Generation Agency', 'None', 'N/A', NOW()),
(2334851, 'TRIMER CAPITAL PARTNERS I LP', 'None', 'N/A', NOW()),
(2334862, 'MONDAY COM LTD', 'None', 'InformationTechnology', NOW()),
(2334871, 'MH NORTHBOUND TRAIN LLC', 'None', 'N/A', NOW()),
(2334878, 'DELAWARE RIVER PORT AUTHORITY', 'None', 'N/A', NOW()),
(2334881, 'TOWNSHIP OF EAST HEMPFIELD PENNSYLVANIA', 'None', 'N/A', NOW()),
(2334913, 'UPPER MERION AREA SCHOOL DISTRICT MONTGOMERY COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(2334918, 'SPROTT URANIUM MINERS ETF', 'None', 'N/A', NOW()),
(2334940, 'PITTSBURGH WATER AND SEWER AUTHORITY', 'None', 'N/A', NOW()),
(2334970, 'HAYWARD HOLDINGS INC', 'None', 'Industrials', NOW()),
(2335002, 'ALVARADO INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2335097, 'PDD HOLDINGS INC', 'None', 'ConsumerDiscretionary', NOW()),
(2335120, 'DAYS BETWEEN, LLC', 'None', 'N/A', NOW()),
(429829, 'ARIZONA STATE LOTTERY', 'None', 'N/A', NOW()),
(429837, 'ARLINGTON COUNTY VIRGINIA', 'None', 'N/A', NOW()),
(430034, 'BDT SUNRISE HOLDINGS LLC', 'None', 'N/A', NOW()),
(430197, 'BP CAPITAL MARKETS PLC', 'None', 'N/A', NOW()),
(430322, 'CALIFORNIA INFRASTRUCTURE AND ECONOMIC DEVELOPMENT BANK', 'None', 'N/A', NOW()),
(430446, 'CELANESE US HOLDINGS LLC', 'None', 'N/A', NOW()),
(430493, 'CHARTER TOWNSHIP OF WEST BLOOMFIELD', 'None', 'N/A', NOW()),
(430559, 'CINCINNATI CITY SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430594, 'CITY OF BALTIMORE MARYLAND', 'None', 'N/A', NOW()),
(430610, 'CITY OF CAPE CORAL FLORIDA', 'None', 'N/A', NOW()),
(430618, 'CITY OF CHICAGO', 'None', 'N/A', NOW()),
(430649, 'CITY OF FORT WORTH TEXAS', 'None', 'N/A', NOW()),
(430657, 'CITY OF GREEN BAY WISCONSIN', 'None', 'N/A', NOW()),
(430693, 'CITY OF LOS ANGELES', 'None', 'N/A', NOW()),
(430724, 'CITY OF ORLANDO FLORIDA', 'None', 'N/A', NOW()),
(430768, 'TACOMA CITY OF WASHINGTON', 'None', 'N/A', NOW()),
(430775, 'CITY OF TOMBALL TEXAS', 'None', 'N/A', NOW()),
(430779, 'CITY OF TULSA OKLAHOMA', 'None', 'N/A', NOW()),
(430821, 'CLEVELAND COUNTY EDUCATIONAL FACILITIES AUTHORITY', 'None', 'N/A', NOW()),
(430909, 'COLUMBUS CITY SCHOOL DISTRICT FRANKLIN COUNTY OHIO', 'None', 'N/A', NOW()),
(2334936, 'HIMS & HERS HEALTH INC', 'XLV', 'Healthcare', NOW()),
(2334956, 'SPDR LONG DOLLAR GOLD TRUST', 'GLD', 'N/A', NOW()),
(2335022, 'PROSHARES ULTRAPRO QQQ', 'QQQ', 'N/A', NOW()),
(429504, 'Advanced Energy Industries Inc', 'XLE', 'InformationTechnology', NOW()),
(429588, 'Algonquin Power & Utilities Corp', 'XLU', 'Utilities', NOW()),
(430226, 'Brighthouse Financial Inc', 'XLF', 'Financials', NOW()),
(430498, 'Check Point Software Technologies Ltd', 'XLK', 'InformationTechnology', NOW()),
(430819, 'Clearway Energy Inc', 'XLE', 'Utilities', NOW()),
(2334641, 'VAXXINITY INC', 'CVAXX', 'Healthcare', NOW()),
(2334666, 'VANGUARD TAX-EXEMPT BOND ETF', 'FVTEB', 'N/A', NOW()),
(2334798, 'FIRST TRUST SMID CAP RISING DIVIDEND ACHIEVERS ETF', 'FSDVY', 'N/A', NOW()),
(2334835, 'FIRST TR GLOBAL TACTICAL CMD', 'DFTGC', 'N/A', NOW()),
(2334942, 'VIKING HOLDINGS LTD', 'TDVIK', 'ConsumerDiscretionary', NOW()),
(2335114, 'FIGMA INC', 'NCFIG', 'InformationTechnology', NOW()),
(2335157, 'NEW WORLD FUND INC', 'RNWGX', 'N/A', NOW()),
(429437, 'AAON Inc', 'AAON', 'Industrials', NOW()),
(429450, 'AB GLOBAL BOND FUND INC', 'ANAGX', 'N/A', NOW()),
(429515, 'Aegon NV', 'NVAEG', 'Financials', NOW()),
(429587, 'Alfa Laval AB', 'ALFVY', 'Industrials', NOW()),
(429690, 'AMERICAN FUNDS SMALLCAP WORLD FUND', 'SMCWX', 'N/A', NOW()),
(429697, 'American Homes 4 Rent', 'AMH', 'RealEstate', NOW()),
(429722, 'American Eagle Outfitters Inc', 'AEO', 'ConsumerDiscretionary', NOW()),
(429752, 'AngioDynamics Inc', 'ANGO', 'Healthcare', NOW()),
(429771, 'APA Corporation', 'APA', 'Energy', NOW()),
(429777, 'APi Group Corp', 'APG', 'Industrials', NOW()),
(429809, 'Arcelormittal SA', 'SAMT', 'Materials', NOW()),
(429836, 'ARK ETF Trust - ARK Innovation ETF', 'FARKK', 'N/A', NOW()),
(429842, 'Armstrong World Industries Inc', 'AWI', 'Industrials', NOW()),
(429856, 'Asbury Automotive Group Inc', 'ABG', 'ConsumerDiscretionary', NOW()),
(429931, 'Autoliv Inc', 'ALV', 'ConsumerDiscretionary', NOW()),
(429933, 'AutoNation Inc', 'AN', 'ConsumerDiscretionary', NOW()),
(429958, 'Axa, Paris', 'AXAHY', 'Financials', NOW()),
(429986, 'Banco Santander SA', 'SASAN', 'Financials', NOW()),
(430031, 'BCE Inc', 'BCE', 'CommunicationServices', NOW()),
(430043, 'BeiGene Ltd', 'BGNE', 'Healthcare', NOW()),
(430099, 'Black Hills Corp', 'BKH', 'Utilities', NOW()),
(430268, 'Bruker Corporation', 'BRKR', 'Healthcare', NOW()),
(430343, 'Cameco Corp', 'CCJ', 'Energy', NOW()),
(430362, 'Canon Inc', 'CAJ', 'InformationTechnology', NOW()),
(430366, 'Capgemini SE', 'CGEMY', 'InformationTechnology', NOW()),
(430390, 'CarGurus Inc', 'CARG', 'CommunicationServices', NOW()),
(430419, 'CATALYST MILLBURN HEDGE STRATEGY FUND', 'MBXIX', 'N/A', NOW()),
(430456, 'Permian Resources Corporation', 'PR', 'Energy', NOW()),
(430464, 'Central Garden & Pet Co', 'CENT', 'ConsumerStaples', NOW()),
(430516, 'Chewy Inc', 'CHWY', 'ConsumerDiscretionary', NOW()),
(430550, 'Cie Financiere Richemont AG, Zug', 'CFRUY', 'ConsumerDiscretionary', NOW()),
(430567, 'Cirrus Logic Inc', 'CRUS', 'InformationTechnology', NOW()),
(430800, 'Clarivate PLC', 'CCLVT', 'Industrials', NOW()),
(430853, 'Coca Cola Consolidated Inc', 'COKE', 'ConsumerStaples', NOW()),
(430882, 'DigitalBridge Group Inc', 'DBRG', 'Financials', NOW()),
(430997, 'CORPUS CHRISTI INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431073, 'COUNTY OF SAN DIEGO', 'None', 'N/A', NOW()),
(431076, 'COUNTY OF SANTA CLARA CALIFORNIA', 'None', 'N/A', NOW()),
(431077, 'COUNTY OF SCHENECTADY NEW YORK', 'None', 'N/A', NOW()),
(431239, 'DEPARTMENT OF EDUCATION SOUTH CAROLINA', 'None', 'N/A', NOW()),
(431242, 'DEPARTMENT OF WATER AND POWER OF CITY OF LOS ANGELES', 'None', 'N/A', NOW()),
(431392, 'EASTON AREA SCHOOL DISTRICT NORTHAMPTON AND BUCKS COUNTIES PENNSYLVANIA', 'None', 'N/A', NOW()),
(431617, 'FALCON EDGE GLOBAL LP', 'None', 'N/A', NOW()),
(431901, 'FULTON COUNTY GEORGIA', 'None', 'N/A', NOW()),
(432072, 'GRANT COUNTY PUBLIC UTILITY DISTRICT', 'None', 'N/A', NOW()),
(432087, 'GREATER ORLANDO AVIATION AUTHORITY', 'None', 'N/A', NOW()),
(432183, 'HARTSFIELD JACKSON INTERNATIONAL AIRPORT CITY OF ATLANTA GEORGIA', 'None', 'N/A', NOW()),
(432335, 'HUDSON YARDS INFRASTRUCTURE CORP', 'None', 'N/A', NOW()),
(432379, 'ILLINOIS HOUSING DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(432396, 'COUNTY OF TULSA', 'None', 'N/A', NOW()),
(432779, 'JOHNSON COUNTY COMMUNITY COLLEGE', 'None', 'N/A', NOW()),
(432857, 'KENTUCKY INFRASTRUCTURE AUTHORITY', 'None', 'N/A', NOW()),
(432859, 'KENTUCKY RURAL WATER FINANCE CORP', 'None', 'N/A', NOW()),
(432885, 'KING COUNTY WASTEWATER TREATMENT DIVISION', 'None', 'N/A', NOW()),
(433008, 'LEXINGTON FAYETTE URBAN COUNTY GOVERNMENT KENTUCKY', 'None', 'N/A', NOW()),
(433113, 'LOS ANGELES UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433119, 'LOWER COLORADO RIVER AUTHORITY', 'None', 'N/A', NOW()),
(431708, 'First Financial Bankshares Inc', 'XLF', 'Financials', NOW())
ON CONFLICT (id) DO NOTHING;