INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(2334860, 'EQV VENTURES ACQN CORP -REDH', 'DHEQV', 'N/A', NOW()),
(2334870, 'TEMPUS AI INC', 'NCTEM', 'Healthcare', NOW()),
(2334934, 'SIMCORP A/S', 'SMCYY', 'InformationTechnology', NOW()),
(2334966, 'TRADEWEB MARKETS INC', 'INCTW', 'Financials', NOW()),
(2334967, 'MITSUBISHI HEAVY INDUST LTD', 'MHVIY', 'Industrials', NOW()),
(2334968, 'UNICREDIT SPA', 'UNCRY', 'Financials', NOW()),
(2334976, 'INNOVIVA INC', 'CINVA', 'Healthcare', NOW()),
(2335003, 'ARIZONA GAME AND FISH DEPARTMENT', 'None', 'N/A', NOW()),
(2335005, 'RCP DIRECT V', 'None', 'N/A', NOW()),
(2335013, 'NORTHAMPTON BORO PENNSYLVANIA', 'None', 'N/A', NOW()),
(2335090, 'CYTOKINETICS INC', 'None', 'Healthcare', NOW()),
(2335092, 'EMPLOYERS HOLDINGS INC', 'None', 'Financials', NOW()),
(2335093, 'FRANKLIN BSP REALTY TRUST IN', 'None', 'Financials', NOW()),
(2335094, 'HILLTOP HOLDINGS INC', 'None', 'Financials', NOW()),
(2335095, 'L''ANSE CREUSE PUBLIC SCHOOLS COUNTY OF MACOMB STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(2335101, 'SOUTHSIDE BANCSHARES INC', 'None', 'Financials', NOW()),
(2335105, 'ROMEO COMMUNITY SCHOOLS', 'None', 'N/A', NOW()),
(2335106, 'CITY OF GRANDVILLE MICHIGAN', 'None', 'N/A', NOW()),
(2335160, 'COREWEAVE INC', 'None', 'InformationTechnology', NOW()),
(429486, 'ADAMS 12 FIVE STAR SCHOOLS COLORADO', 'None', 'N/A', NOW()),
(429559, 'ALABAMA PUBLIC SCHOOL AND COLLEGE AUTHORITY', 'None', 'N/A', NOW()),
(429611, 'ALLIANT HOLDINGS LP', 'None', 'N/A', NOW()),
(429838, 'ARLINGTON HIGHER EDUCATION FINANCE CORP', 'None', 'N/A', NOW()),
(430017, 'BAY AREA TOLL AUTHORITY', 'None', 'N/A', NOW()),
(430054, 'BERGEN COUNTY NEW JERSEY', 'None', 'N/A', NOW()),
(430153, 'BMO HARRIS BANK NA', 'None', 'N/A', NOW()),
(430275, 'BUCKEYE CENTRAL LOCAL SCHOOL DISTRICT OHIO', 'None', 'N/A', NOW()),
(430295, 'BUTLER COUNTY OHIO', 'None', 'N/A', NOW()),
(430338, 'CAMBRIAN SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430398, 'CARMAN AINSWORTH COMMUNITY SCHOOLS COUNTY OF GENESEE STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(430465, 'CENTRAL KITSAP SCHOOL DISTRICT NO 401 KITSAP COUNTY WASHINGTON', 'None', 'N/A', NOW()),
(430511, 'CHEROKEE COUNTY SCHOOL SYSTEM', 'None', 'N/A', NOW()),
(2335059, 'SPDR DOW JONES INDUSTRIAL AVERAGE ETF TRUST', 'DIA', 'N/A', NOW()),
(2335086, 'BEACON FINANCIAL CORP', 'XLF', 'Financials', NOW()),
(2335102, 'VIPER ENERGY INC', 'XLE', 'Energy', NOW()),
(429460, 'Acadia Healthcare Co Inc', 'XLV', 'Healthcare', NOW()),
(430143, 'Bloom Energy Corp', 'XLE', 'Industrials', NOW()),
(430510, 'Cheniere Energy Partners LP', 'XLE', 'Energy', NOW()),
(430512, 'Chesapeake Energy Corp', 'XLE', 'Energy', NOW()),
(432045, 'GOLDMAN SACHS SMALL MID CAP GROWTH FUND', 'GLD', 'N/A', NOW()),
(2335000, 'INVESCO CURRENCYSHARES SWISS FRANC TRUST', 'STFXF', 'N/A', NOW()),
(2335077, 'ARM HOLDINGS PLC', 'LCARM', 'InformationTechnology', NOW()),
(2335119, 'BLUE OWL CAPITAL INC', 'NCOWL', 'Financials', NOW()),
(429440, 'ABBEY CAPITAL FUTURES STRATEGY FUND', 'ABYAX', 'N/A', NOW()),
(429453, 'ABIOMED Inc', 'ABMD', 'Healthcare', NOW()),
(429456, 'ABN AMRO Bank NV', 'AAVMY', 'Financials', NOW()),
(429477, 'ACI Worldwide Inc', 'ACIW', 'InformationTechnology', NOW()),
(429490, 'Adecco Group AG', 'AHEXY', 'Industrials', NOW()),
(429543, 'Airbus SE', 'EADSY', 'Industrials', NOW()),
(429557, 'Akzo Nobel NV', 'AKZOY', 'Materials', NOW()),
(429602, 'ALLETE Inc', 'ALE', 'Utilities', NOW()),
(429628, 'ALPS Alerian MLP ETF', 'FAMLP', 'N/A', NOW()),
(429643, 'Amadeus IT Group SA', 'AMADY', 'ConsumerDiscretionary', NOW()),
(429652, 'AMC Networks Inc', 'AMCX', 'CommunicationServices', NOW()),
(429665, 'American Assets Trust Inc', 'AAT', 'RealEstate', NOW()),
(429718, 'AMERISAFE Inc', 'AMSF', 'Financials', NOW()),
(429728, 'AMG YACKTMAN FUND', 'YACKX', 'N/A', NOW()),
(429750, 'The Andersons Inc', 'ANDE', 'ConsumerStaples', NOW()),
(429753, 'Anglo American PLC', 'NGLOY', 'Materials', NOW()),
(429779, 'A.P. Moller - Maersk A/S', 'AMKBY', 'Industrials', NOW()),
(429813, 'Archrock Inc', 'AROC', 'Energy', NOW()),
(429833, 'Arkema', 'ARKAY', 'Materials', NOW()),
(429855, 'Asahi Kasei Corp', 'AHKSY', 'Materials', NOW()),
(429871, 'Aspen Insurance Holdings Ltd', 'AHL', 'Financials', NOW()),
(429880, 'Assured Guaranty Ltd', 'AGO', 'Financials', NOW()),
(429896, 'Athene Holding Ltd', 'ATH', 'Financials', NOW()),
(429900, 'Atlantica Sustainable Infrastructure PLC', 'PLCAY', 'Utilities', NOW()),
(429937, 'Avangrid Inc', 'AGR', 'Utilities', NOW()),
(429945, 'Avis Budget Group Inc', 'CAR', 'Industrials', NOW()),
(429946, 'Aviva PLC', 'AVVIY', 'Financials', NOW()),
(429969, 'Baidu Inc', 'BIDU', 'CommunicationServices', NOW()),
(429972, 'Baker Hughes Inc', 'BHI', 'Energy', NOW()),
(429974, 'Balchem Corp', 'BCPC', 'Materials', NOW()),
(429977, 'Ballard Power Systems Inc', 'BLDP', 'Industrials', NOW()),
(429989, 'Bank of Hawaii Corp', 'BOH', 'Financials', NOW()),
(430101, 'BlackLine Inc', 'BL', 'InformationTechnology', NOW()),
(430141, 'Block H&R Inc', 'HRB', 'ConsumerDiscretionary', NOW()),
(430162, 'BOC Hong Kong (Holdings) Ltd', 'BHKLY', 'Financials', NOW()),
(430203, 'Brambles Ltd', 'BXBLY', 'Industrials', NOW()),
(430215, 'BRIDGE BUILDER CORE BOND FUND', 'BBTBX', 'N/A', NOW()),
(430216, 'BRIDGE BUILDER CORE PLUS BOND FUND', 'BBCPX', 'N/A', NOW()),
(430218, 'BRIDGE BUILDER LARGE CAP VALUE FUND', 'BBVLX', 'N/A', NOW()),
(430236, 'The British Land Co PLC', 'BTLCY', 'RealEstate', NOW()),
(430237, 'Brixmor Property Group Inc', 'BRX', 'RealEstate', NOW()),
(430253, 'Brookfield Renewable Corp', 'BEPC', 'Utilities', NOW()),
(430262, 'BROWN ADVISORY SUSTAINABLE GROWTH FUND', 'BAWAX', 'N/A', NOW()),
(430286, 'Burberry Group PLC', 'BURBY', 'ConsumerDiscretionary', NOW()),
(430287, 'Bureau Veritas SA', 'BVVBY', 'Industrials', NOW()),
(430300, 'C3.ai Inc', 'AI', 'InformationTechnology', NOW()),
(430335, 'CALVERT SMALL CAP FUND', 'CCVAX', 'N/A', NOW()),
(430336, 'CALVERT US LARGE CAP VALUE RESPONSIBLE INDEX', 'CFJAX', 'N/A', NOW()),
(430386, 'CareDx Inc', 'CDNA', 'Healthcare', NOW()),
(430410, 'Carvana Co', 'CVNA', 'ConsumerDiscretionary', NOW()),
(430411, 'Casella Waste Systems Inc', 'CWST', 'Industrials', NOW()),
(430424, 'Cathay General Bancorp', 'CATY', 'Financials', NOW()),
(430443, 'Cedar Fair LP', 'LPFUN', 'ConsumerDiscretionary', NOW()),
(430539, 'Choice Hotels International Inc', 'CHH', 'ConsumerDiscretionary', NOW()),
(430548, 'Chuy''s Holdings Inc', 'CHUY', 'ConsumerDiscretionary', NOW()),
(430581, 'CITY OF AKRON OHIO', 'None', 'N/A', NOW()),
(430583, 'CITY OF AMES IOWA', 'None', 'N/A', NOW()),
(430585, 'CITY OF ANKENY IOWA', 'None', 'N/A', NOW()),
(430648, 'CITY OF FORT SMITH ARKANSAS', 'None', 'N/A', NOW()),
(430686, 'CITY OF LAREDO TEXAS', 'None', 'N/A', NOW()),
(430700, 'CITY OF MCKINNEY', 'None', 'N/A', NOW()),
(430707, 'CITY OF MILWAUKEE WISCONSIN', 'None', 'N/A', NOW()),
(430734, 'CITY OF PORTLAND OREGON', 'None', 'N/A', NOW()),
(430737, 'CITY OF RALEIGH NORTH CAROLINA', 'None', 'N/A', NOW()),
(430750, 'CITY OF SAN JOSE', 'None', 'N/A', NOW()),
(430762, 'CITY OF SPOKANE WASHINGTON', 'None', 'N/A', NOW()),
(430763, 'CITY OF STOCKTON SAN JOAQUIN COUNTY CALIFORNIA', 'None', 'N/A', NOW()),
(430764, 'CITY OF ST PETERSBURG FLORIDA', 'None', 'N/A', NOW()),
(430771, 'CITY OF TEMPLE TEXAS', 'None', 'N/A', NOW()),
(430774, 'CITY OF TOLEDO OHIO', 'None', 'N/A', NOW()),
(430793, 'CITY OF WINSTON SALEM NORTH CAROLINA', 'None', 'N/A', NOW()),
(430802, 'CLARK COUNTY NEVADA SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430817, 'CLEAR CREEK INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430845, 'COAST COMMUNITY COLLEGE DISTRICT', 'None', 'N/A', NOW()),
(430891, 'COLORADO SPRINGS COLO UTILS REV', 'None', 'N/A', NOW()),
(431018, 'COUNTY OF CHESTER', 'None', 'N/A', NOW()),
(431038, 'COUNTY OF LAKE', 'None', 'N/A', NOW()),
(431044, 'COUNTY OF MARIN', 'None', 'N/A', NOW()),
(431052, 'COUNTY OF MONTGOMERY MARYLAND', 'None', 'N/A', NOW()),
(431056, 'COUNTY OF NASSAU NEW YORK', 'None', 'N/A', NOW()),
(431060, 'COUNTY OF ORANGE CALIFORNIA', 'None', 'N/A', NOW()),
(431069, 'COUNTY OF RIVERSIDE CALIFORNIA', 'None', 'N/A', NOW()),
(431082, 'COUNTY OF WAKE NORTH CAROLINA', 'None', 'N/A', NOW()),
(431116, 'CRISPR Therapeutics AG', 'None', 'Healthcare', NOW()),
(431173, 'DALLAS AREA RAPID TRANSIT', 'None', 'N/A', NOW()),
(431174, 'DALLAS COUNTY HOSPITAL DISTRICT', 'None', 'N/A', NOW()),
(431209, 'Deere (John) Capital Corp', 'None', 'Financials', NOW()),
(431216, 'DELAWARE COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(431337, 'DOUGLAS COUNTY GEORGIA', 'None', 'N/A', NOW()),
(431365, 'DUBLIN UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431383, 'EAST BAY MUNICIPAL UTILITY DISTRICT', 'None', 'N/A', NOW()),
(431432, 'Electrolux AB', 'None', 'ConsumerDiscretionary', NOW()),
(431445, 'EL PASO COUNTY TEXAS', 'None', 'N/A', NOW()),
(431577, 'euNetworks Group Ltd', 'None', 'CommunicationServices', NOW()),
(431795, 'FLORIDA DEPARTMENT OF TRANSPORTATION', 'None', 'N/A', NOW()),
(431813, 'FOLSOM CORDOVA UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431826, 'FORNEY INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431847, 'FOXTROT VENTURES INC', 'None', 'N/A', NOW()),
(430809, 'Clean Energy Fuels Corp', 'XLE', 'Energy', NOW()),
(431294, 'Direxion Daily Financial Bull 3X', 'XLF', 'N/A', NOW()),
(431591, 'Evoqua Water Technologies Corp', 'XLK', 'Industrials', NOW()),
(431673, 'Fidelity Nasdaq Composite Index ETF', 'QQQ', 'N/A', NOW()),
(431736, 'First Trust MLP and Energy Income Fund', 'XLE', 'N/A', NOW()),
(431739, 'First Trust NASDAQ-100 Technology Sector Index Fund', 'XLK', 'N/A', NOW()),
(431897, 'FuelCell Energy Inc', 'XLE', 'Industrials', NOW()),
(432003, 'Global X FinTech ETF', 'XLK', 'N/A', NOW()),
(432033, 'GOLDMAN SACHS FS GOVERNMENT FUND', 'GLD', 'N/A', NOW()),
(432034, 'GOLDMAN SACHS GQG PARTNERS INTERNATIONAL OPPORTUNITIES FUND', 'GLD', 'N/A', NOW()),
(430857, 'Cochlear Ltd', 'CHEOY', 'Healthcare', NOW()),
(430866, 'Cohen & Steers Inc', 'CNS', 'Financials', NOW()),
(430913, 'Comfort Systems USA Inc', 'FIX', 'Industrials', NOW()),
(430940, 'Compass Minerals International Inc', 'CMP', 'Materials', NOW()),
(430970, 'Continental Resources Inc', 'CLR', 'Energy', NOW()),
(431008, 'Coty Inc', 'COTY', 'ConsumerStaples', NOW()),
(431087, 'Coupa Software Inc', 'COUP', 'InformationTechnology', NOW()),
(431099, 'Crane Co', 'CR', 'Industrials', NOW()),
(431112, 'Crestwood Equity Partners LP', 'PCEQP', 'Energy', NOW()),
(431128, 'Cryoport Inc', 'CYRX', 'Healthcare', NOW()),
(431163, 'Daifuku Co Ltd', 'DFKCY', 'Industrials', NOW()),
(431168, 'Dai Nippon Printing Co Ltd', 'DNPLY', 'Industrials', NOW()),
(431184, 'Danone SA', 'DANOY', 'ConsumerStaples', NOW()),
(431215, 'DELAWARE CORPORATE BOND FUND', 'DGCAX', 'N/A', NOW()),
(431217, 'DELAWARE SMALL CAP CORE FUND', 'DCCIX', 'N/A', NOW()),
(431231, 'Denso Corp', 'DNZOY', 'ConsumerDiscretionary', NOW()),
(431250, 'Deutsche Boerse AG', 'DBOEY', 'Financials', NOW()),
(431332, 'Dorman Products Inc', 'DORM', 'ConsumerDiscretionary', NOW()),
(431348, 'DraftKings Inc', 'DKNG', 'ConsumerDiscretionary', NOW()),
(431368, 'Duke Realty Corp', 'DRE', 'RealEstate', NOW()),
(431411, 'EDGEWOOD GROWTH FUND', 'EGFIX', 'N/A', NOW()),
(431414, 'Editas Medicine Inc', 'EDIT', 'Healthcare', NOW()),
(431416, 'EDP-Energias de Portugal SA', 'EDPFY', 'Utilities', NOW()),
(431437, 'Element Solutions Inc', 'ESI', 'Materials', NOW()),
(431453, 'Embraer SA', 'SAERJ', 'Industrials', NOW()),
(431466, 'Empire State Realty Trust Inc', 'ESRT', 'RealEstate', NOW()),
(431470, 'Enanta Pharmaceuticals Inc', 'ENTA', 'Healthcare', NOW()),
(431533, 'EPR Properties', 'EPR', 'RealEstate', NOW()),
(431550, 'Erie Indemnity Co', 'ERIE', 'Financials', NOW()),
(431557, 'Essential Properties Realty Trust Inc', 'EPRT', 'RealEstate', NOW()),
(431581, 'Everbridge Inc', 'EVBG', 'InformationTechnology', NOW()),
(431635, 'Federal National Mortgage Association', 'FNMA', 'Financials', NOW()),
(431696, 'First BanCorp (Puerto Rico)', 'FBP', 'Financials', NOW()),
(431720, 'First Pacific Co Ltd', 'FPAFY', 'ConsumerStaples', NOW()),
(431756, 'First Trust Indxx NextG ETF', 'FNXTG', 'N/A', NOW()),
(431880, 'Fresenius Medical Care AG &Co KGAA', 'AAFMS', 'Healthcare', NOW()),
(431898, 'Fujifilm Holdings Corp', 'FUJIY', 'InformationTechnology', NOW()),
(431918, 'GameStop Corp', 'GME', 'ConsumerDiscretionary', NOW()),
(431923, 'Gap Inc', 'GPS', 'ConsumerDiscretionary', NOW()),
(431968, 'Getinge AB', 'GNGBY', 'Healthcare', NOW()),
(431982, 'Glacier Bancorp Inc', 'GBCI', 'Financials', NOW()),
(432170, 'HARRIS COUNTY FLOOD CONTROL DISTRICT', 'None', 'N/A', NOW()),
(432269, 'HILLSBOROUGH COUNTY FLORIDA', 'None', 'N/A', NOW()),
(432363, 'IDAHO STATE BUILDING AUTHORITY', 'None', 'N/A', NOW()),
(432750, 'JEFFERSON COUNTY TEXAS', 'None', 'N/A', NOW()),
(432827, 'KANSAS DEVELOPMENT FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(432962, 'LAS VEGAS VALLEY WATER DISTRICT', 'None', 'N/A', NOW()),
(433002, 'LEWIS AND CLARK COUNTY', 'None', 'N/A', NOW()),
(433005, 'LEWISVILLE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;