INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(2333183, 'THE MERGER FUND', 'MERFX', 'N/A', NOW()),
(2333444, 'Civitas Resources Inc', 'CIVI', 'Energy', NOW()),
(2333484, 'Repligen Corp', 'RGEN', 'Healthcare', NOW()),
(2333536, 'Rivian Automotive Inc', 'RIVN', 'ConsumerDiscretionary', NOW()),
(2333615, 'Triton International Ltd', 'TRTN', 'Industrials', NOW()),
(2333852, 'Sisecam Resources LP', 'PSIRE', 'Materials', NOW()),
(2334115, 'VICTORY CPTL HLDGS INC', 'CVCTR', 'Financials', NOW()),
(2334200, 'CLEAR SECURE INC', 'NCYOU', 'InformationTechnology', NOW()),
(2334244, 'BOISE CASCADE CO', 'COBCC', 'Industrials', NOW()),
(2334275, 'CENTRAL JAPAN RAILWAY CORP', 'CJPRY', 'Industrials', NOW()),
(2334343, 'OLAPLEX HOLDINGS INC', 'COLPX', 'ConsumerStaples', NOW()),
(2334395, 'PGIM HIGH YIELD FUND', 'PHYZX', 'N/A', NOW()),
(2334540, 'MERCATO PARTNERS TRAVERSE IV QP LP', 'None', 'N/A', NOW()),
(2334566, 'SWARTZ CREEK COMMUNITY SCHOOLS', 'None', 'N/A', NOW()),
(2334567, 'CITY OF TEMPE ARIZONA', 'None', 'N/A', NOW()),
(2334572, 'CITY OF FORT LAUDERDALE', 'None', 'N/A', NOW()),
(2334595, 'CITY OF NEW BRAUNFELS TEXAS', 'None', 'N/A', NOW()),
(2334599, 'SOUTHCENTRAL PENNSYLVANIA GENERAL AUTHORITY', 'None', 'N/A', NOW()),
(2334626, 'SHERMAN INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334690, 'CASS COUNTY JOINT WATER RESOURCE DISTRICT NORTH DAKOTA', 'None', 'N/A', NOW()),
(2334698, 'MAIN STREET NATURAL GAS INC', 'None', 'N/A', NOW()),
(2334742, 'HARRIS COUNTY TOLL ROAD AUTHORITY', 'None', 'N/A', NOW()),
(2334756, 'WEST CHESTER AREA SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334757, 'GREATER NEW HAVEN WATER POLLUTION CONTROL AUTHORITY', 'None', 'N/A', NOW()),
(2334825, 'CRINETICS PHARMCTCL INC', 'None', 'Healthcare', NOW()),
(2334834, 'KENT STREET GROUP GP', 'None', 'N/A', NOW()),
(2334839, 'WAKE OF THE FLOOD LLC', 'None', 'N/A', NOW()),
(2334895, 'LANTHEUS HOLDINGS INC', 'None', 'Healthcare', NOW()),
(2335158, 'SERA PROGNOSTICS INC', 'None', 'Healthcare', NOW()),
(429927, 'AUSTIN INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430066, 'BEXAR COUNTY TEXAS', 'None', 'N/A', NOW()),
(430157, 'BOARD OF PUBLIC BUILDINGS OF STATE OF MISSOURI', 'None', 'N/A', NOW()),
(430280, 'BUILDGROUP LLC', 'None', 'N/A', NOW()),
(430283, 'BULLOCH COUNTY GEORGIA', 'None', 'N/A', NOW()),
(430468, 'CENTRAL TEXAS REGIONAL MOBILITY AUTHORITY', 'None', 'N/A', NOW()),
(430612, 'CITY OF CARMEL REDEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(430616, 'CITY OF CHARLOTTE NORTH CAROLINA', 'None', 'N/A', NOW()),
(430656, 'CITY OF GRAND RAPIDS MICHIGAN', 'None', 'N/A', NOW()),
(430669, 'CITY OF HOOVER ALABAMA', 'None', 'N/A', NOW()),
(430688, 'CITY OF LAS VEGAS NEVADA', 'None', 'N/A', NOW()),
(430704, 'CITY OF MESA', 'None', 'N/A', NOW()),
(430710, 'MOBILE COUNTY OF ALABAMA', 'None', 'N/A', NOW()),
(430716, 'CITY OF NORFOLK VIRGINIA', 'None', 'N/A', NOW()),
(430739, 'CITY OF RICHMOND VIRGINIA', 'None', 'N/A', NOW()),
(430748, 'CITY OF SAN ANTONIO TEXAS', 'None', 'N/A', NOW()),
(430792, 'CITY OF WILMINGTON DELEWARE', 'None', 'N/A', NOW()),
(430804, 'CLARK COUNTY WATER RECLAMATION DISTRICT NEVADA', 'None', 'N/A', NOW()),
(431024, 'COUNTY OF DUPAGE ILLINOIS', 'None', 'N/A', NOW()),
(431079, 'COUNTY OF SHELBY', 'None', 'N/A', NOW()),
(431176, 'DALLAS COUNTY TEXAS', 'None', 'N/A', NOW()),
(431232, 'DENTON COUNTY TEXAS', 'None', 'N/A', NOW()),
(431233, 'DENTON INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431247, 'DES MOINES COUNTY IOWA', 'None', 'N/A', NOW()),
(431629, 'FEDERAL FARM CREDIT BANK', 'None', 'N/A', NOW()),
(2334799, 'INVESCO NASDAQ 100 ETF', 'QQQ', 'N/A', NOW()),
(2334894, 'PAR TECHNOLOGY CORP', 'XLK', 'InformationTechnology', NOW()),
(429488, 'AdaptHealth Corp', 'XLV', 'Healthcare', NOW()),
(429928, 'AUSTIN TEXAS UTILITIES AUTHORITY', 'XLU', 'N/A', NOW()),
(430299, 'BWX Technologies Inc', 'XLK', 'Industrials', NOW()),
(430357, 'Canadian Natural Resources Ltd', 'DIA', 'Energy', NOW()),
(430842, 'CNO Financial Group Inc', 'XLF', 'Financials', NOW()),
(430854, 'Coca-Cola Europacific Partners PLC', 'KO', 'ConsumerStaples', NOW()),
(431473, 'Encompass Health Corp', 'XLV', 'Healthcare', NOW()),
(2334535, 'MSD ACQUISITION CORP', 'PMSDA', 'N/A', NOW()),
(2334581, 'ALAMO GROUP INC', 'NCALG', 'Industrials', NOW()),
(2334604, 'DIMENSIO INTER CORE EQUI ETF', 'FDFAI', 'N/A', NOW()),
(2334622, 'DIMENSIONAL US SML CAP ETF', 'FDFAS', 'N/A', NOW()),
(2334631, 'ABRDN PHYSICAL PALLAD SH ETF', 'FPALL', 'N/A', NOW()),
(2334645, 'FRESHPET INC', 'CFRPT', 'ConsumerStaples', NOW()),
(2334711, 'TUHURA BIOSCIENCES INC', 'CHURA', 'N/A', NOW()),
(2334740, 'PIMCO COMMODITIES PLUS STRATEGY FUND', 'PCLPX', 'N/A', NOW()),
(2334769, 'STERLING INFRASTRUCTURE INC', 'CSTRL', 'Industrials', NOW()),
(2334847, 'SPDR® PORTFOLIO MORTGAGE BACKED BOND ETF', 'FSPMB', 'N/A', NOW()),
(2334921, 'FIRST BUSEY CORP', 'PBUSE', 'Financials', NOW()),
(2334991, 'SANDISK CORP', 'PSNDK', 'InformationTechnology', NOW()),
(2335091, 'DUOLINGO INC', 'CDUOL', 'ConsumerDiscretionary', NOW()),
(429529, 'Agios Pharmaceuticals Inc', 'AGIO', 'Healthcare', NOW()),
(429579, 'Alcon Inc', 'ALC', 'Healthcare', NOW()),
(429630, 'ALPS Medical Breakthroughs ETF', 'FSBIO', 'N/A', NOW()),
(429636, 'Altice usa Inc', 'ATUS', 'CommunicationServices', NOW()),
(429758, 'Annaly Capital Management Inc', 'NLY', 'Financials', NOW()),
(429766, 'Australia & New Zealand Banking Group Ltd', 'ANZBY', 'Financials', NOW()),
(429884, 'Astellas Pharma Inc', 'ALPMY', 'Healthcare', NOW()),
(429912, 'AtriCure Inc', 'ATRC', 'Healthcare', NOW()),
(429963, 'The AZEK Company Inc', 'AZEK', 'Industrials', NOW()),
(430083, 'Biomarin Pharmaceutical Inc', 'BMRN', 'Healthcare', NOW()),
(430174, 'Boot Barn Holdings Inc', 'BOOT', 'ConsumerDiscretionary', NOW()),
(430868, 'Cohen & Steers Ltd Duration Preferred and Income Fund Inc', 'LDP', 'N/A', NOW()),
(430917, 'Commerzbank AG, Frankfurt', 'CRZBY', 'Financials', NOW()),
(431104, 'Credit Agricole SA, Paris', 'CRARY', 'Financials', NOW()),
(431107, 'Credit Suisse Group', 'CS', 'Financials', NOW()),
(431166, 'Daikin Industries Ltd', 'DKILY', 'Industrials', NOW()),
(431237, 'Dentsu Group Inc', 'DNTUY', 'CommunicationServices', NOW()),
(431253, 'Deutsche Telekom AG', 'DTEGY', 'CommunicationServices', NOW()),
(431288, 'Diodes Inc', 'DIOD', 'InformationTechnology', NOW()),
(431355, 'Dropbox Inc', 'DBX', 'InformationTechnology', NOW()),
(431361, 'DSV A/S', 'DSDVY', 'Industrials', NOW()),
(431456, 'EMCOR Group Inc', 'EME', 'Industrials', NOW()),
(431497, 'Enerpac Tool Group Corp', 'EPAC', 'Industrials', NOW()),
(431545, 'Equitrans Midstream Corp', 'ETRN', 'Energy', NOW())
ON CONFLICT (id) DO NOTHING;