INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(433382, 'Microsoft Corp', 'MSFT', 'InformationTechnology', NOW()),
(429622, 'Alphabet Inc', 'GOOGL', 'CommunicationServices', NOW()),
(433770, 'NVIDIA Corporation', 'NVDA', 'InformationTechnology', NOW()),
(429789, 'Apple Inc', 'AAPL', 'InformationTechnology', NOW()),
(432796, 'JPMorgan Chase & Co', 'JPM', 'Financials', NOW()),
(431610, 'Meta Platforms Inc', 'META', 'CommunicationServices', NOW()),
(435467, 'Unitedhealth Group Inc', 'UNH', 'Healthcare', NOW()),
(2264488, 'Berkshire Hathaway Inc', 'BRK.B', 'Financials', NOW()),
(2334591, 'JPMORGAN 100% US TREASURY SECURITIES MONEY MARKET FUND', 'JPM', 'N/A', NOW()),
(429495, 'Adobe Inc', 'ADBE', 'InformationTechnology', NOW()),
(435735, 'Visa Inc', 'V', 'Financials', NOW()),
(435211, 'Tesla Inc', 'TSLA', 'ConsumerDiscretionary', NOW()),
(435546, 'US TREASURY NOTE', '^TNX', 'N/A', NOW()),
(432782, 'Johnson & Johnson', 'JNJ', 'Healthcare', NOW()),
(429988, 'Bank of America Corp', 'BAC', 'Financials', NOW()),
(433323, 'Merck & Co Inc', 'MRK', 'Healthcare', NOW()),
(431303, 'The Walt Disney Co', 'DIS', 'CommunicationServices', NOW()),
(432293, 'The Home Depot Inc', 'HD', 'ConsumerDiscretionary', NOW()),
(434517, 'salesforce.com Inc', 'CRM', 'InformationTechnology', NOW()),
(430911, 'Comcast Corp', 'CMCSA', 'CommunicationServices', NOW()),
(433036, 'Eli Lilly and Co', 'LLY', 'Healthcare', NOW()),
(432464, 'Intel Corp', 'INTC', 'InformationTechnology', NOW()),
(434041, 'Pfizer Inc', 'PFE', 'Healthcare', NOW()),
(434191, 'The Procter & Gamble Co', 'PG', 'ConsumerStaples', NOW()),
(429443, 'AbbVie Inc', 'ABBV', 'Healthcare', NOW()),
(433589, 'Netflix Inc', 'NFLX', 'CommunicationServices', NOW()),
(435673, 'Verizon Communications Inc', 'VZ', 'CommunicationServices', NOW()),
(433381, 'Micron Technology Inc', 'XLK', 'InformationTechnology', NOW()),
(430852, 'The Coca-Cola Co', 'KO', 'ConsumerStaples', NOW()),
(433254, 'Mastercard Inc', 'MA', 'Financials', NOW()),
(429914, 'AT&T Inc', 'T', 'CommunicationServices', NOW()),
(431156, 'CVS Health Corp', 'XLV', 'Healthcare', NOW()),
(435403, 'Truist Financial Corp', 'XLF', 'Financials', NOW()),
(435432, 'Uber Technologies Inc', 'UBER', 'Industrials', NOW()),
(432035, 'The Goldman Sachs Group Inc', 'GLD', 'Financials', NOW()),
(429793, 'Applied Materials Inc', 'XLB', 'InformationTechnology', NOW()),
(429765, 'Elevance Health Inc', 'XLV', 'Healthcare', NOW()),
(430368, 'Capital One Financial Corp', 'XLF', 'Financials', NOW()),
(430515, 'Chevron Corp', 'CVX', 'Energy', NOW()),
(431424, 'Elanco Animal Health Inc', 'XLV', 'Healthcare', NOW()),
(433865, 'Oracle Corp', 'ORCL', 'InformationTechnology', NOW()),
(435777, 'Walmart Inc', 'WMT', 'ConsumerStaples', NOW()),
(1282836, 'Wells Fargo & Co', 'WFC', 'Financials', NOW()),
(430431, 'CBOE MINI SPX INDEX', 'EXXSP', 'N/A', NOW()),
(429469, 'Accenture PLC', 'LCACN', 'InformationTechnology', NOW()),
(430239, 'Broadcom Inc', 'AVGO', 'InformationTechnology', NOW()),
(435219, 'Texas Instruments Inc', 'TXN', 'InformationTechnology', NOW()),
(434019, 'PepsiCo Inc', 'PEP', 'ConsumerStaples', NOW()),
(434933, 'Starbucks Corp', 'SBUX', 'ConsumerDiscretionary', NOW()),
(429442, 'Abbott Laboratories', 'ABT', 'Healthcare', NOW()),
(430570, 'Citigroup Inc', 'C', 'Financials', NOW()),
(429505, 'Advanced Micro Devices Inc', 'AMD', 'InformationTechnology', NOW()),
(434591, 'Schwab (Charles) Corp', 'SCHW', 'Financials', NOW()),
(435244, 'Thermo Fisher Scientific Inc', 'TMO', 'Healthcare', NOW()),
(435472, 'United Parcel Service Inc', 'UPS', 'Industrials', NOW()),
(433469, 'Morgan Stanley', 'MS', 'Financials', NOW()),
(429769, 'Aon PLC', 'LCAON', 'Financials', NOW()),
(430423, 'Caterpillar Inc', 'CAT', 'Industrials', NOW()),
(433048, 'Linde PLC', 'LCLIN', 'Materials', NOW()),
(432337, 'Humana Inc', 'HUM', 'Healthcare', NOW()),
(432490, 'Intuit Inc', 'INTU', 'InformationTechnology', NOW()),
(431181, 'Danaher Corp', 'DHR', 'Healthcare', NOW()),
(435137, 'Target Corp', 'TGT', 'ConsumerStaples', NOW()),
(430016, 'Baxter International Inc', 'BAX', 'Healthcare', NOW()),
(433658, 'Nike Inc', 'NKE', 'ConsumerDiscretionary', NOW()),
(431003, 'Costco Wholesale Corp', 'COST', 'ConsumerStaples', NOW()),
(436024, 'Zoetis Inc', 'ZTS', 'Healthcare', NOW()),
(435459, 'Union Pacific Corp', 'UNP', 'Industrials', NOW()),
(429822, 'Arista Networks Inc', 'ANET', 'InformationTechnology', NOW()),
(430955, 'ConocoPhillips', 'COP', 'Energy', NOW()),
(434658, 'ServiceNow Inc', 'NOW', 'InformationTechnology', NOW()),
(432951, 'Lam Research Corp', 'LRCX', 'InformationTechnology', NOW()),
(434275, 'QUALCOMM Inc', 'QCOM', 'InformationTechnology', NOW()),
(430117, 'Blackrock Inc', 'BLK', 'Financials', NOW()),
(433309, 'Medtronic PLC', 'LCMDT', 'Healthcare', NOW()),
(429867, 'ASML Holding NV', 'VASML', 'InformationTechnology', NOW()),
(430534, 'Chipotle Mexican Grill Inc', 'CMG', 'ConsumerDiscretionary', NOW()),
(432480, 'International Business Machines Corp', 'IBM', 'InformationTechnology', NOW()),
(430172, 'Booking Holdings Inc', 'BKNG', 'ConsumerDiscretionary', NOW()),
(431675, 'Fidelity National Information Services Inc', 'FIS', 'Financials', NOW()),
(433279, 'McDonald''s Corp', 'MCD', 'ConsumerDiscretionary', NOW()),
(429617, 'The Allstate Corporation', 'ALL', 'Financials', NOW()),
(430820, 'Cleveland-Cliffs Inc', 'CLF', 'Materials', NOW()),
(431645, 'FedEx Corp', 'FDX', 'Industrials', NOW()),
(433121, 'Lowe''s Cos Inc', 'LOW', 'ConsumerDiscretionary', NOW()),
(434678, 'The Sherwin-Williams Co', 'SHW', 'Materials', NOW()),
(1734484, 'Centene Corp', 'CNC', 'Healthcare', NOW()),
(429700, 'American International Group Inc', 'AIG', 'Financials', NOW()),
(431426, 'ELCM2 LLC', 'None', 'N/A', NOW()),
(434983, 'STATE OF OHIO', 'None', 'N/A', NOW()),
(2334916, 'MH BUILT TO LAST LLC', 'None', 'N/A', NOW()),
(2334865, 'NOT FADE AWAY LLC', 'None', 'N/A', NOW()),
(2334500, 'MAYS ALLOCATE LP', 'None', 'N/A', NOW()),
(433633, 'NEW YORK CITY TRANSITIONAL FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(434996, 'STATE OF WASHINGTON', 'None', 'N/A', NOW()),
(434652, 'Sensata Technologies Holding PLC', 'XLK', 'Industrials', NOW()),
(434094, 'Pinterest Inc', 'PINS', 'CommunicationServices', NOW()),
(434118, 'The PNC Financial Services Group Inc', 'XLF', 'Financials', NOW()),
(429542, 'Airbnb Inc', 'ABNB', 'ConsumerDiscretionary', NOW()),
(434919, 'SS&C Technologies Holdings Inc', 'XLK', 'Industrials', NOW()),
(431320, 'Dominion Energy Inc', 'XLE', 'Utilities', NOW()),
(432199, 'HCA Healthcare Inc', 'XLV', 'Healthcare', NOW()),
(431121, 'CrowdStrike Holdings Inc', 'CRWD', 'InformationTechnology', NOW()),
(431527, 'EPAM Systems Inc', 'EPAM', 'InformationTechnology', NOW()),
(431946, 'General Motors Co', 'GM', 'ConsumerDiscretionary', NOW()),
(432899, 'KKR & Co Inc', 'KKR', 'Financials', NOW()),
(433952, 'Parker-Hannifin Corp', 'PH', 'Industrials', NOW()),
(431772, 'Fiserv Inc', 'FI', 'Financials', NOW()),
(433586, 'NetApp Inc', 'NTAP', 'InformationTechnology', NOW()),
(431208, 'DEERE & COMPANY', 'ANYDE', 'Industrials', NOW()),
(431819, 'Ford Motor Co', 'F', 'ConsumerDiscretionary', NOW()),
(431998, 'GLOBAL PAYMENTS Inc', 'GPN', 'Financials', NOW()),
(432491, 'Intuitive Surgical Inc', 'ISRG', 'Healthcare', NOW()),
(429725, 'Amgen Inc', 'AMGN', 'Healthcare', NOW()),
(431833, 'Fortinet Inc', 'FTNT', 'InformationTechnology', NOW()),
(433927, 'Palo Alto Networks Inc', 'PANW', 'InformationTechnology', NOW()),
(429708, 'American Tower Corp', 'AMT', 'RealEstate', NOW()),
(2334695, 'GE VERNOVA INC', 'NCGEV', 'Industrials', NOW()),
(430231, 'Bristol-Myers Squibb Co', 'BMY', 'Healthcare', NOW()),
(431124, 'Crown Castle International Corp', 'CCI', 'RealEstate', NOW()),
(431944, 'General Electric Co', 'GE', 'Industrials', NOW()),
(429741, 'Analog Devices Inc', 'ADI', 'InformationTechnology', NOW()),
(434348, 'Regeneron Pharmaceuticals Inc', 'REGN', 'Healthcare', NOW()),
(435112, 'Sysco Corporation', 'SYY', 'ConsumerStaples', NOW()),
(433227, 'Marriott International Inc', 'MAR', 'ConsumerDiscretionary', NOW()),
(435040, 'Stryker Corp', 'SYK', 'Healthcare', NOW()),
(429677, 'American Express Co', 'AXP', 'Financials', NOW()),
(429932, 'Automatic Data Processing Inc', 'ADP', 'Industrials', NOW()),
(430041, 'Becton Dickinson and Co', 'BDX', 'Healthcare', NOW()),
(430133, 'Blackstone Group Inc', 'BX', 'Financials', NOW()),
(430994, 'Corning Inc', 'GLW', 'InformationTechnology', NOW()),
(431608, 'Exxon Mobil Corp', 'XOM', 'Energy', NOW()),
(432965, 'The Estee Lauder Cos Inc', 'EL', 'ConsumerStaples', NOW()),
(433456, 'Monster Beverage Corp', 'MNST', 'ConsumerStaples', NOW()),
(433568, 'NCR Corp', 'NCR', 'InformationTechnology', NOW()),
(430305, 'Cadence Design Systems Inc', 'CDNS', 'InformationTechnology', NOW()),
(433229, 'Marsh & McLennan Companies Inc', 'MMC', 'Financials', NOW()),
(434055, 'Philip Morris International Inc', 'PM', 'ConsumerStaples', NOW()),
(435611, 'VANGUARD LONG TERM TAX EXEMPT FUND', 'VWLUX', 'N/A', NOW()),
(431315, 'Dollar General Corporation', 'DG', 'ConsumerStaples', NOW()),
(435282, 'T-Mobile US Inc', 'TMUS', 'CommunicationServices', NOW()),
(432298, 'Honeywell International Inc', 'HON', 'Industrials', NOW()),
(433444, 'Mondelez International Inc', 'MDLZ', 'ConsumerStaples', NOW()),
(435532, 'U.S. Bancorp', 'USB', 'Financials', NOW()),
(431346, 'Dow Inc', 'DOW', 'Materials', NOW()),
(431395, 'Eaton Corp PLC', 'LCETN', 'Industrials', NOW()),
(433130, 'Lululemon Athletica Inc', 'LULU', 'ConsumerDiscretionary', NOW()),
(433283, 'McKesson Corp', 'MCK', 'Healthcare', NOW()),
(435808, 'Waste Management Inc', 'WM', 'Industrials', NOW()),
(433735, 'Novo Nordisk A/S', 'SNVO', 'Healthcare', NOW()),
(429428, '3M Co', 'MMM', 'Industrials', NOW()),
(429939, 'Avantor Inc', 'AVTR', 'Healthcare', NOW()),
(431299, 'Warner Bros Discover Inc', 'WBD', 'CommunicationServices', NOW()),
(434316, 'RTX Corp', 'RTX', 'Industrials', NOW()),
(434562, 'SBA Communications Corp', 'SBAC', 'RealEstate', NOW()),
(435958, 'Workday Inc', 'WDAY', 'InformationTechnology', NOW()),
(430543, 'Chubb Ltd', 'CB', 'Financials', NOW()),
(435639, 'Vanguard Total Stock Market ETF', 'TFVTI', 'N/A', NOW()),
(431607, 'Extra Space Storage Inc', 'EXR', 'RealEstate', NOW()),
(432924, 'The Kraft Heinz Co', 'KHC', 'ConsumerStaples', NOW()),
(433688, 'Norfolk Southern Corp', 'NSC', 'Industrials', NOW()),
(434883, 'S&P Global Inc', 'SPGI', 'Financials', NOW()),
(436020, 'Zimmer Biomet Holdings Inc', 'ZBH', 'Healthcare', NOW()),
(430554, 'Cigna Corp', 'CI', 'Healthcare', NOW()),
(433081, 'Lockheed Martin Corp', 'LMT', 'Industrials', NOW()),
(434460, 'Shell PLC', 'CSHEL', 'Energy', NOW()),
(430834, 'CME Group Inc', 'CME', 'Financials', NOW()),
(430875, 'Colgate-Palmolive Co', 'CL', 'ConsumerStaples', NOW()),
(432250, 'The Hershey Co', 'HSY', 'ConsumerStaples', NOW()),
(434151, 'PPG Industries Inc', 'PPG', 'Materials', NOW()),
(435281, 'The TJX Companies Inc', 'TJX', 'ConsumerDiscretionary', NOW()),
(435430, 'Tyson Foods Inc', 'TSN', 'ConsumerStaples', NOW()),
(430962, 'Constellation Brands Inc', 'STZ', 'ConsumerStaples', NOW()),
(433338, 'Metlife Inc', 'MET', 'Financials', NOW()),
(434194, 'The Progressive Corp', 'PGR', 'Financials', NOW()),
(431418, 'Edwards Lifesciences Corp', 'EW', 'Healthcare', NOW()),
(432866, 'Keurig Dr Pepper Inc', 'KDP', 'ConsumerStaples', NOW()),
(432937, 'Laboratory Corp of America Holdings', 'LH', 'Healthcare', NOW()),
(433819, 'Old Dominion Freight Line Inc', 'ODFL', 'Industrials', NOW()),
(433977, 'Paychex Inc', 'PAYX', 'Industrials', NOW()),
(429720, 'Cencora Inc', 'COR', 'Healthcare', NOW()),
(434954, 'STATE OF CONNECTICUT', 'None', 'N/A', NOW()),
(431333, 'DORMITORY AUTHORITY OF THE STATE OF NEW YORK', 'None', 'N/A', NOW()),
(434327, 'Realty Income Corp', 'None', 'RealEstate', NOW()),
(2334898, 'MH FOUR WINDS LLC', 'None', 'N/A', NOW()),
(433232, 'Martin Marietta Materials Inc', 'XLB', 'Materials', NOW()),
(429583, 'Alexandria Real Estate Equities Inc', 'VNQ', 'RealEstate', NOW()),
(431506, 'Enphase Energy Inc', 'XLE', 'InformationTechnology', NOW()),
(433817, 'OKTA Inc', 'OKTA', 'InformationTechnology', NOW()),
(434353, 'Regions Financial Corp', 'XLF', 'Financials', NOW()),
(433379, 'Microchip Technology Inc', 'XLK', 'InformationTechnology', NOW()),
(2331336, 'Palantir Technologies Inc', 'PLTR', 'InformationTechnology', NOW()),
(431298, 'Discover Financial Services', 'XLF', 'Financials', NOW()),
(431783, 'FleetCor Technologies Inc', 'XLK', 'Financials', NOW()),
(433236, 'Marvell Technology Inc', 'XLK', 'InformationTechnology', NOW()),
(435342, 'Trane Technologies PLC', 'XLK', 'Industrials', NOW()),
(430573, 'Citizens Financial Group Inc', 'XLF', 'Financials', NOW()),
(434233, 'Prudential Financial Inc', 'XLF', 'Financials', NOW()),
(435765, 'Westinghouse Air Brake Technologies Corp', 'XLK', 'Industrials', NOW()),
(432382, 'Illumina Inc', 'ILMN', 'Healthcare', NOW())
ON CONFLICT (id) DO NOTHING;