INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(431726, 'First Trust Dow Jones Internet Index Fund', 'DIA', 'N/A', NOW()),
(432133, 'Gulfport Energy Corp', 'XLE', 'Energy', NOW()),
(432228, 'Helios Technologies Inc', 'XLK', 'Industrials', NOW()),
(432229, 'Helix Energy Solutions Group Inc', 'XLE', 'Energy', NOW()),
(432466, 'Intellia Therapeutics Inc', 'INTC', 'Healthcare', NOW()),
(432591, 'iShares Gold Trust', 'GLD', 'N/A', NOW()),
(432808, 'JPMORGAN STRATEGIC INCOME OPPORTUNITIES FUND', 'JPM', 'N/A', NOW()),
(433085, 'Logitech International SA, Apples', 'AAPL', 'InformationTechnology', NOW()),
(430919, 'Commonwealth Bank of Australia', 'CMWAY', 'Financials', NOW()),
(430935, 'CommVault Systems Inc', 'CVLT', 'InformationTechnology', NOW()),
(430959, 'Consolidated Edison Inc', 'ED', 'Utilities', NOW()),
(430996, 'Corporate Office Properties Trust', 'CDP', 'RealEstate', NOW()),
(431131, 'CSL Ltd', 'CSLLY', 'Healthcare', NOW()),
(431150, 'Cushman & Wakefield Ltd', 'CWK', 'RealEstate', NOW()),
(431165, 'Daiichi Sankyo Company Ltd', 'DSNKY', 'Healthcare', NOW()),
(431170, 'Daiwa House Industry Co Ltd', 'DWAHY', 'RealEstate', NOW()),
(431245, 'The Descartes Systems Group Inc', 'DSGX', 'InformationTechnology', NOW()),
(431252, 'Deutsche Post AG', 'DPSGY', 'Industrials', NOW()),
(431276, 'Dick''s Sporting Goods Inc.', 'DKS', 'ConsumerDiscretionary', NOW()),
(431314, 'Dolby Laboratories Inc', 'DLB', 'InformationTechnology', NOW()),
(431335, 'DOUBLELINE EMERGING MARKETS FIXED INCOME FUND', 'DBLEX', 'N/A', NOW()),
(431454, 'EMC Corp', 'EMC', 'InformationTechnology', NOW()),
(431500, 'Engie SA', 'ENGIY', 'Utilities', NOW()),
(431552, 'Erste Group Bank AG', 'EBKDY', 'Financials', NOW()),
(431556, 'Essent Group Ltd', 'ESNT', 'Financials', NOW()),
(431561, 'Essilorluxottica', 'ESLOY', 'Healthcare', NOW()),
(431595, 'Exelixis Inc', 'EXEL', 'Healthcare', NOW()),
(431628, 'Fast Retailing Co Ltd', 'FRCOY', 'ConsumerDiscretionary', NOW()),
(431636, 'Federal Realty Investment Trust', 'FRT', 'RealEstate', NOW()),
(431655, 'FIDELITY ADVISOR FOCUSED EMERGING MARKETS FUND', 'FIMKX', 'N/A', NOW()),
(431704, 'FIRST EAGLE GLOBAL FUND', 'SGENX', 'N/A', NOW()),
(431710, 'First Hawaiian Inc', 'FHB', 'Financials', NOW()),
(431792, 'Floor & Decor Holdings Inc', 'FND', 'ConsumerDiscretionary', NOW()),
(431812, 'F.N.B. Corp', 'FNB', 'Financials', NOW()),
(431932, 'GATX Corp', 'GATX', 'Industrials', NOW()),
(431934, 'GCI Liberty Inc', 'GLIBA', 'CommunicationServices', NOW()),
(431959, 'Gentex Corporation', 'GNTX', 'ConsumerDiscretionary', NOW()),
(432047, 'Golub Capital BDC Inc', 'GBDC', 'Financials', NOW()),
(432103, 'Grifols S.A.', 'GRFS', 'Healthcare', NOW()),
(432153, 'Hannon Armstrong Sustainable Infrastructure Capital Inc', 'HASI', 'Financials', NOW()),
(432188, 'Hawaiian Electric Industries Inc', 'HE', 'Utilities', NOW()),
(432224, 'Heidelbergcement AG', 'HDELY', 'Materials', NOW()),
(432230, 'Helmerich & Payne Inc', 'HP', 'Energy', NOW()),
(432246, 'Hermes International SA', 'HESAY', 'ConsumerDiscretionary', NOW()),
(432257, 'Hexcel Corp', 'HXL', 'Industrials', NOW()),
(432279, 'HNI Corp', 'HNI', 'Industrials', NOW()),
(432295, 'Honda Motor Co Ltd', 'HMC', 'ConsumerDiscretionary', NOW()),
(432322, 'Hoya Corp', 'HOCPY', 'Healthcare', NOW()),
(432342, 'Huntsman Corp', 'HUN', 'Materials', NOW()),
(432359, 'ICU Medical Inc', 'ICUI', 'Healthcare', NOW()),
(432395, 'Industria De Diseno Textil Inditex SA', 'IDEXY', 'ConsumerDiscretionary', NOW()),
(432436, 'Ingredion Inc', 'INGR', 'ConsumerStaples', NOW()),
(432548, 'iRobot Corp', 'IRBT', 'ConsumerDiscretionary', NOW()),
(432580, 'iShares Core S&P U.S. Growth ETF', 'FIUSG', 'N/A', NOW()),
(432583, 'iShares ESG Aware MSCI EAFE ETF', 'FESGD', 'N/A', NOW()),
(432611, 'iShares iBoxx High Yield Corporate Bond ETF', 'TFHYG', 'N/A', NOW()),
(432864, 'Kering', 'PPRUY', 'ConsumerDiscretionary', NOW()),
(432919, 'Koninklijke Philips NV', 'NVPHG', 'Healthcare', NOW()),
(432922, 'Kose Corp', 'KSRYY', 'ConsumerStaples', NOW()),
(432939, 'L''Air Liquide SA', 'AIQUY', 'Materials', NOW()),
(432970, 'Lazard Ltd', 'LAZ', 'Financials', NOW()),
(433009, 'LXP Industrial Trust', 'LXP', 'RealEstate', NOW()),
(433032, 'Life Storage Inc', 'LSI', 'RealEstate', NOW()),
(433041, 'Lincoln Electric Holdings Inc', 'LECO', 'Industrials', NOW()),
(433152, 'Mack-Cali Realty Corp', 'VRE', 'RealEstate', NOW()),
(433155, 'Macquarie Group Ltd', 'MQBKY', 'Financials', NOW()),
(433183, 'MAINE TURNPIKE AUTHORITY', 'None', 'N/A', NOW()),
(433342, 'METROPOLITAN NASHVILLE AIRPORT AUTHORITY', 'None', 'N/A', NOW()),
(433348, 'METROPOLITAN WATER RECLAMATION DISTRICT OF GREATER CHICAGO', 'None', 'N/A', NOW()),
(433264, 'Maxar Technologies Inc', 'XLK', 'Industrials', NOW()),
(433228, 'Marriott Vacations Worldwide Corp', 'VAC', 'ConsumerDiscretionary', NOW()),
(433243, 'Masimo Corp', 'MASI', 'Healthcare', NOW()),
(433399, 'Minerals Technologies Inc', 'XLK', 'Materials', NOW()),
(433408, 'MISSOURI HEALTH AND EDUCATIONAL FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(433412, 'MISSOURI PUBLIC UTILITIES COMMISSION', 'XLU', 'N/A', NOW()),
(433425, 'Mizuho Financial Group Inc', 'XLF', 'Financials', NOW()),
(433605, 'New Gold Inc', 'GLD', 'Materials', NOW()),
(433651, 'NextEra Energy Partners LP', 'XLE', 'Utilities', NOW()),
(433738, 'NRG Energy Inc', 'XLE', 'Utilities', NOW()),
(433801, 'OGE ENERGY CORP', 'XLE', 'Utilities', NOW()),
(433999, 'Peloton Interactive Inc', 'PTON', 'ConsumerDiscretionary', NOW()),
(434393, 'RHODE ISLAND HEALTH AND EDUCATIONAL BUILDING CORP', 'XLV', 'N/A', NOW()),
(434648, 'Semtech Corp', 'XLK', 'InformationTechnology', NOW()),
(434772, 'Solaris Oilfield Infrastructure Inc', 'USO', 'Energy', NOW()),
(434848, 'SPDR Gold Trust', 'GLD', 'N/A', NOW()),
(433362, 'MGIC Investment Corp', 'MTG', 'Financials', NOW()),
(433387, 'The Middleby Corp', 'MIDD', 'Industrials', NOW()),
(433419, 'Mitsubishi Estate Co Ltd', 'MITEY', 'RealEstate', NOW()),
(433449, 'Monotaro Co Ltd', 'MONOY', 'Industrials', NOW()),
(433491, 'MSA Safety Inc', 'MSA', 'Industrials', NOW()),
(433533, 'Naspers Ltd', 'NPSNY', 'ConsumerDiscretionary', NOW()),
(433536, 'National Australia Bank Ltd', 'NABZY', 'Financials', NOW()),
(433539, 'National Beverage Corp', 'FIZZ', 'ConsumerStaples', NOW()),
(433614, 'New Jersey Resources Corp', 'NJR', 'Utilities', NOW()),
(433655, 'Nidec Corp', 'NJDCY', 'Industrials', NOW()),
(433722, 'NorthWestern Corp', 'NWE', 'Utilities', NOW()),
(433729, 'Novanta Inc', 'NOVT', 'InformationTechnology', NOW()),
(433736, 'Novozymes A/S', 'NVZMY', 'Materials', NOW()),
(433748, 'Nutanix Inc', 'NTNX', 'InformationTechnology', NOW()),
(433843, 'ONE Gas Inc', 'OGS', 'Utilities', NOW()),
(433979, 'Paylocity Holding Corp', 'PCTY', 'Industrials', NOW()),
(434000, 'Pembina Pipeline Corp', 'PBA', 'Energy', NOW()),
(434016, 'Pentair PLC', 'LCPNR', 'Industrials', NOW()),
(434061, 'Phreesia Inc', 'PHR', 'Healthcare', NOW()),
(434103, 'Plains All American Pipeline LP', 'LPPAA', 'Energy', NOW()),
(434110, 'PLDT Inc', 'PHI', 'CommunicationServices', NOW()),
(434196, 'Progress Software Corp', 'PRGS', 'InformationTechnology', NOW()),
(434277, 'Qualys Inc', 'QLYS', 'InformationTechnology', NOW()),
(434298, 'Radius Global Infrastructure Inc', 'RADI', 'CommunicationServices', NOW()),
(434304, 'Ralph Lauren Corp', 'RL', 'ConsumerDiscretionary', NOW()),
(434386, 'Rexford Industrial Realty Inc', 'REXR', 'RealEstate', NOW()),
(434406, 'RingCentral Inc', 'RNG', 'InformationTechnology', NOW()),
(434465, 'Royalty Pharma PLC', 'CRPRX', 'Healthcare', NOW()),
(433367, 'MIAMI DADE COUNTY SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433372, 'MICHIGAN FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(433619, 'NEW MEXICO FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(433803, 'OHIO HOUSING FINANCE AGENCY', 'None', 'N/A', NOW()),
(433815, 'OKLAHOMA TURNPIKE AUTHORITY', 'None', 'N/A', NOW()),
(433942, 'PARCHMENT SCHOOL DISTRICT COUNTY OF KALAMAZOO STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(434557, 'SARASOTA COUNTY FLORIDA', 'None', 'N/A', NOW()),
(434572, 'SCHOOL BOARD OF BROWARD COUNTY FLORIDA', 'None', 'N/A', NOW()),
(434633, 'The Industrial Select Sector SPDR Fund', 'XLI', 'N/A', NOW()),
(434642, 'Selective Insurance Group Inc', 'SIGI', 'Financials', NOW()),
(434671, 'SGS Sa', 'SGSOY', 'Industrials', NOW()),
(434681, 'Shin-Etsu Chemical Co Ltd', 'SHECY', 'Materials', NOW()),
(434704, 'Silicon Laboratories Inc', 'SLAB', 'InformationTechnology', NOW()),
(434783, 'Sonova Holding AG', 'SONVY', 'Healthcare', NOW()),
(434838, 'SPDR Bloomberg Barclays Corporate Bond ETF', 'FSPBO', 'N/A', NOW()),
(434871, 'SPDR S&P Regional Banking ETF', 'TFKRE', 'N/A', NOW()),
(434891, 'Splunk Inc', 'SPLK', 'InformationTechnology', NOW()),
(434952, 'STATE OF COLORADO', 'None', 'N/A', NOW()),
(434961, 'STATE OF IOWA', 'None', 'N/A', NOW()),
(434964, 'STATE OF KANSAS DEPARTMENT OF TRANSPORTATION', 'None', 'N/A', NOW()),
(434966, 'STATE OF MAINE', 'None', 'N/A', NOW()),
(434971, 'STATE OF MISSISSIPPI', 'None', 'N/A', NOW()),
(434979, 'STATE OF NEW MEXICO', 'None', 'N/A', NOW()),
(434986, 'STATE OF RHODE ISLAND', 'None', 'N/A', NOW()),
(435226, 'TEXAS STATE UNIVERSITY SYSTEM', 'None', 'N/A', NOW()),
(435401, 'TROY SCHOOL DISTRICT COUNTY OF OAKLAND STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(435437, 'UC4K INVESTMENTS LLC', 'None', 'N/A', NOW()),
(435723, 'VIRGINIA COLLEGE BUILDING AUTHORITY', 'None', 'N/A', NOW()),
(435726, 'VIRGINIA STATE PUBLIC SCHOOL AUTHORITY', 'None', 'N/A', NOW()),
(435791, 'WASHINGTON COUNTY TENNESSEE', 'None', 'N/A', NOW()),
(435793, 'WASHINGTON DC METRO AREA TRANS', 'None', 'N/A', NOW()),
(435803, 'WASHOE COUNTY NEVADA', 'None', 'N/A', NOW()),
(435976, 'UNIFIED GOVERNMENT OF WYANDOTTE COUNTY AND KANSAS CITY KANSAS', 'None', 'N/A', NOW()),
(603019, 'COUNTY OF LOS ANGELES', 'None', 'N/A', NOW()),
(620167, 'STATE OF NEW YORK', 'None', 'N/A', NOW()),
(727175, 'ALAMO COMMUNITY COLLEGE DISTRICT', 'None', 'N/A', NOW()),
(825289, 'STATE OF SOUTH CAROLINA', 'None', 'N/A', NOW()),
(2149018, 'PENNSYLVANIA STATE SYSTEM OF HIGHER EDUCATION', 'None', 'N/A', NOW()),
(2271839, 'CITY OF ST LOUIS MISSOURI', 'None', 'N/A', NOW()),
(2331334, 'LAKE COOK KANE AND MCHENRY COUNTIES ILLINOIS', 'None', 'N/A', NOW()),
(2331393, 'YIHENG CAPITAL PARTNERS LP', 'None', 'N/A', NOW()),
(2331430, 'PORT OF PORTLAND OREGON', 'None', 'N/A', NOW()),
(2332013, 'LOS ANGELES COUNTY METROPOLITAN TRANSPORTATION AUTHORITY', 'None', 'N/A', NOW()),
(2332160, 'DALLAS FORT WORTH INTERNATIONAL AIRPORT', 'None', 'N/A', NOW()),
(2332548, 'WYOMING PUBLIC SCHOOLS', 'None', 'N/A', NOW()),
(2332593, 'ILLINOIS STATE UNIVERSITY', 'None', 'N/A', NOW()),
(2332712, 'CITY OF MIAMI FLORIDA', 'None', 'N/A', NOW()),
(2333290, 'MURFREESBORO CITY OF TENNESSEE', 'None', 'N/A', NOW()),
(435062, 'Suncor Energy Inc', 'XLE', 'Energy', NOW()),
(435172, 'Teladoc Health Inc', 'XLV', 'Healthcare', NOW()),
(435600, 'Vanguard Global ex-U.S. Real Estate ETF', 'VNQ', 'N/A', NOW()),
(435676, 'VERMONT EDUCATIONAL AND HEALTH BUILDINGS FINANCING AGENCY', 'XLV', 'N/A', NOW()),
(435952, 'Woodside Energy Group Ltd', 'XLE', 'Energy', NOW()),
(435995, 'Yamana Gold Inc', 'GLD', 'Materials', NOW()),
(1452871, 'NEW YORK CITY HEALTH AND HOSPITALS CORP', 'XLV', 'N/A', NOW()),
(2274783, 'Northern Oil and Gas Inc', 'USO', 'Energy', NOW()),
(2331192, 'SAN FRANCISCO UNIFIED SCHOOL DISTRICT', 'CSCO', 'N/A', NOW()),
(2331778, 'SOUTH DAKOTA DEPARTMENT OF HEALTH', 'XLV', 'N/A', NOW()),
(2332010, 'Genworth Financial Inc', 'XLF', 'Financials', NOW()),
(2332816, 'SPDR S&P Metals & Mining ETF', 'META', 'N/A', NOW()),
(2333267, 'Fortescue Metals Group Ltd', 'META', 'Materials', NOW()),
(434939, 'Starwood Property Trust Inc', 'STWD', 'Financials', NOW()),
(435066, 'Sunoco LP', 'LPSUN', 'Energy', NOW()),
(435073, 'Supernus Pharmaceuticals Inc', 'SUPN', 'Healthcare', NOW()),
(435083, 'Swedbank AB', 'SWDBY', 'Financials', NOW()),
(435086, 'Sweetgreen Inc', 'SG', 'ConsumerDiscretionary', NOW()),
(435164, 'Teck Resources Ltd', 'TECK', 'Materials', NOW()),
(435181, 'Telenor ASA', 'TELNY', 'CommunicationServices', NOW()),
(435187, 'TELUS Corp', 'TU', 'CommunicationServices', NOW()),
(435233, 'Textron Inc', 'TXT', 'Industrials', NOW()),
(435245, 'Thermon Group Holdings Inc', 'THR', 'Industrials', NOW()),
(435253, 'Thor Industries Inc', 'THO', 'ConsumerDiscretionary', NOW()),
(435290, 'Toray Industries Inc', 'TRYIY', 'Materials', NOW()),
(435296, 'Managed Portfolio Series Tortoise North American Pipeline Fund', 'TPYP', 'N/A', NOW()),
(435298, 'Toshiba Corp', 'TOSYY', 'Industrials', NOW()),
(435332, 'Toyota Motor Credit Corp', 'A', 'Financials', NOW()),
(435354, 'Travel Plus Leisure Co', 'TNL', 'ConsumerDiscretionary', NOW()),
(435377, 'Trinity Industries Inc', 'TRN', 'Industrials', NOW()),
(435523, 'Upm-Kymmene Corp', 'UPMMY', 'Materials', NOW()),
(435527, 'Urban Edge Properties', 'UE', 'RealEstate', NOW()),
(435555, 'Valaris Ltd', 'ESV', 'Energy', NOW()),
(435690, 'ViaSat Inc', 'VSAT', 'InformationTechnology', NOW()),
(435820, 'WD-40 Co', 'WDFC', 'ConsumerStaples', NOW()),
(435875, 'Westpac Banking Corp', 'WBK', 'Financials', NOW()),
(435964, 'World Wrestling Entertainment Inc', 'WWE', 'CommunicationServices', NOW()),
(435966, 'W. P. Carey Inc', 'WPC', 'RealEstate', NOW()),
(435968, 'WPP PLC', 'LCWPP', 'CommunicationServices', NOW())
ON CONFLICT (id) DO NOTHING;