INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(433011, 'LGI Homes Inc', 'LGIH', 'ConsumerDiscretionary', NOW()),
(433105, 'LORD ABBETT ULTRA SHORT BOND FUND', 'LUBFX', 'N/A', NOW()),
(433106, 'L''Oreal S.A., Paris', 'LRLCY', 'ConsumerStaples', NOW()),
(433749, 'Nutrien Ltd', 'NTR', 'Materials', NOW()),
(434153, 'PPL Corp', 'PPL', 'Utilities', NOW()),
(434616, 'Seagen Inc', 'SGEN', 'Healthcare', NOW()),
(434617, 'Sealed Air Corp', 'SEE', 'Materials', NOW()),
(434680, 'Shimano Inc', 'SMNNY', 'ConsumerDiscretionary', NOW()),
(434739, 'SL Green Realty Corp', 'SLG', 'RealEstate', NOW()),
(434803, 'Southern Copper Corp', 'SCCO', 'Materials', NOW()),
(434859, 'SPDR S&P 400 Mid Cap Value ETF', 'FMDYV', 'N/A', NOW()),
(434910, 'Sprouts Farmers Market Inc', 'SFM', 'ConsumerStaples', NOW()),
(434992, 'STATE OF TEXAS', 'None', 'N/A', NOW()),
(435547, 'UTAH TRANSIT AUTHORITY', 'None', 'N/A', NOW()),
(2212272, 'COMMONWEALTH OF MASSACHUSETTS', 'None', 'N/A', NOW()),
(2332471, 'RECURRING CAPITAL FUND III LP', 'None', 'N/A', NOW()),
(2334218, 'STATE OF NEW YORK GENERAL OBLIGATION BONDS', 'None', 'N/A', NOW()),
(2334222, 'NEW JERSEY TRANSPORTATION TRUST FUND AUTHORITY', 'None', 'N/A', NOW()),
(2334251, 'ISSAQUAH SCHOOL DISTRICT NO 411 KING COUNTY WASHINGTON', 'None', 'N/A', NOW()),
(2334421, 'NXP BV/NXP FUNDING LLC', 'None', 'N/A', NOW()),
(2334556, 'CLEAR CREEK COUNTY', 'None', 'N/A', NOW()),
(2334564, 'PORTLAND INTERNATIONAL AIRPORT', 'None', 'N/A', NOW()),
(2334814, 'VERSUS CAPITAL REAL ASSETS FUND LLC', 'None', 'N/A', NOW()),
(429823, 'ARIZONA BOARD OF REGENTS', 'None', 'N/A', NOW()),
(430032, 'BDT CAPITAL PARTNERS LLC', 'None', 'N/A', NOW()),
(430592, 'CITY OF AUSTIN TEXAS', 'None', 'N/A', NOW()),
(430924, 'COMMONWEALTH OF VIRGINIA', 'None', 'N/A', NOW()),
(432052, 'GOVERNMENT NATIONAL MORTGAGE ASSOCIATION', 'None', 'N/A', NOW()),
(432262, 'HIDALGO COUNTY TX', 'None', 'N/A', NOW()),
(433182, 'MAINE STATE HOUSING AUTHORITY', 'None', 'N/A', NOW()),
(433248, 'MASSACHUSETTS DEPARTMENT OF TRANSPORTATION', 'None', 'N/A', NOW()),
(433699, 'NORTH DAKOTA HOUSING FINANCE AGENCY', 'None', 'N/A', NOW()),
(434065, 'PIERCE COUNTY WASHINGTON', 'None', 'N/A', NOW()),
(434294, 'RACINE UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(434518, 'SALES TAX SECURITIZATION CORP', 'None', 'N/A', NOW()),
(434874, 'SPECIAL SCHOOL DISTRICT NO 1 MINNEAPOLIS MINNESOTA', 'None', 'N/A', NOW()),
(434956, 'STATE OF FLORIDA DEPARTMENT OF ENVIRONMENTAL PROTECTION', 'None', 'N/A', NOW()),
(435343, 'TransCanada PipeLines Ltd', 'None', 'Energy', NOW()),
(435493, 'UNIVERSITY OF ARKANSAS', 'None', 'N/A', NOW()),
(435514, 'UNIVERSITY OF PITTSBURGH', 'None', 'N/A', NOW()),
(2335078, 'BITMINE IMMERSION TECHNOLOGIES INC', 'XLK', 'N/A', NOW()),
(430888, 'COLORADO HEALTH FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(431707, 'FirstEnergy Corp', 'XLE', 'Utilities', NOW()),
(431889, 'FS ENERGY AND POWER FUND', 'XLE', 'N/A', NOW()),
(432544, 'iRhythm Technologies Inc', 'XLK', 'Healthcare', NOW()),
(433207, 'Manulife Financial Corp', 'XLF', 'Financials', NOW()),
(433885, 'ORLANDO UTILITIES COMMISSION', 'XLU', 'N/A', NOW()),
(433976, 'Patterson-UTI Energy Inc', 'T', 'Energy', NOW()),
(434853, 'SPDR Series Trust - SPDR Portfolio S&P 500 Value ETF', 'SPY', 'N/A', NOW()),
(435224, 'Texas Roadhouse Inc', 'TXRH', 'ConsumerDiscretionary', NOW()),
(435542, 'US Physical Therapy Inc', 'USPH', 'Healthcare', NOW()),
(435602, 'Vanguard Growth ETF', 'TFVUG', 'N/A', NOW()),
(435656, 'Vector Group Ltd', 'VGR', 'ConsumerStaples', NOW()),
(435818, 'Wayfair Inc', 'W', 'ConsumerDiscretionary', NOW()),
(2300828, 'KBR Inc', 'KBR', 'Industrials', NOW()),
(2331431, 'CubeSmart', 'CUBE', 'RealEstate', NOW()),
(2331796, 'iShares MSCI Australia ETF', 'TFEWA', 'N/A', NOW()),
(2333856, 'FIRST GUARANTY BANCSHARES', 'SFGBI', 'Financials', NOW()),
(2334094, 'FLYWIRE CORP', 'PFLYW', 'Financials', NOW()),
(2334128, 'ISHARES CORE MSCI TOTAL INTL', 'LIXUS', 'N/A', NOW()),
(2334155, 'VAXCYTE INC', 'CPCVX', 'Healthcare', NOW()),
(2334231, 'SPIRE INC', 'INCSR', 'Utilities', NOW()),
(2334350, 'INVESCO S&P MDCP QUALITY ETF', 'FXMHQ', 'N/A', NOW()),
(2334365, 'GITLAB INC', 'CGTLB', 'InformationTechnology', NOW()),
(2334457, 'DISCO CORP', 'DSCSY', 'InformationTechnology', NOW()),
(429570, 'Albertsons Cos Inc', 'ACI', 'ConsumerStaples', NOW()),
(429866, 'Ashtead Group PLC', 'ASHTY', 'Industrials', NOW()),
(429879, 'Assurant Inc', 'AIZ', 'Financials', NOW()),
(429985, 'Cadence Bank', 'CADE', 'Financials', NOW()),
(430284, 'Bunge Ltd', 'BG', 'ConsumerStaples', NOW()),
(430507, 'The Chemours Co', 'CC', 'Materials', NOW()),
(430547, 'Churchill Downs Inc', 'CHDN', 'ConsumerDiscretionary', NOW()),
(430810, 'Clean Harbors Inc', 'CLH', 'Industrials', NOW()),
(430885, 'Coloplast A/S', 'CLPBY', 'Healthcare', NOW()),
(431609, 'F5 Inc', 'FFIV', 'InformationTechnology', NOW()),
(431711, 'First Horizon Corp', 'FHN', 'Financials', NOW()),
(431804, 'Flowers Foods Inc', 'FLO', 'ConsumerStaples', NOW()),
(431806, 'Fluor Corp', 'FLR', 'Industrials', NOW()),
(431814, 'Fomento Economico Mexican SAB de CV', 'CVFMX', 'ConsumerStaples', NOW()),
(431844, 'Four Corners Property Trust Inc', 'FCPT', 'RealEstate', NOW()),
(432057, 'Graco Inc', 'GGG', 'Industrials', NOW()),
(432266, 'Highwoods Properties Inc', 'HIW', 'RealEstate', NOW()),
(432301, 'Horace Mann Educators Corp', 'HMN', 'Financials', NOW()),
(432429, 'Infosys Ltd', 'INFY', 'InformationTechnology', NOW()),
(432456, 'Installed Building Products Inc', 'IBP', 'ConsumerDiscretionary', NOW()),
(432460, 'Integra LifeSciences Holdings Corp', 'IART', 'Healthcare', NOW()),
(432618, 'iShares MBS ETF', 'TFMBB', 'N/A', NOW()),
(432633, 'iShares International Equity- ETFs  iShares MSCI Japan ETF', 'TFEWJ', 'N/A', NOW()),
(432643, 'iShares Preferred and Income Securities ETF', 'TFPFF', 'N/A', NOW()),
(432994, 'Lennox International Inc', 'LII', 'Industrials', NOW()),
(433384, 'MicroStrategy Inc', 'MSTR', 'InformationTechnology', NOW()),
(433535, 'Natera Inc', 'NTRA', 'Healthcare', NOW()),
(434022, 'PERFORMANCE FOOD GROUP COMPANY', 'YPFGC', 'ConsumerStaples', NOW()),
(434026, 'Pernod-Ricard', 'PDRDY', 'ConsumerStaples', NOW()),
(434257, 'Pure Storage Inc', 'PSTG', 'InformationTechnology', NOW()),
(434269, 'Qorvo Inc', 'QRVO', 'InformationTechnology', NOW()),
(434286, 'Quidel Corp', 'QDEL', 'Healthcare', NOW()),
(434359, 'RELX PLC', 'CRELX', 'Industrials', NOW()),
(434412, 'Ritchie Bros Auctioneers Inc', 'RBA', 'Industrials', NOW()),
(434440, 'Rolls Royce Holdings PLC', 'RYCEY', 'Industrials', NOW())
ON CONFLICT (id) DO NOTHING;