INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(2333183, 'THE MERGER FUND', 'MERFX', 'N/A', NOW()),
(2333444, 'Civitas Resources Inc', 'CIVI', 'Energy', NOW()),
(2333484, 'Repligen Corp', 'RGEN', 'Healthcare', NOW()),
(2333536, 'Rivian Automotive Inc', 'RIVN', 'ConsumerDiscretionary', NOW()),
(2333615, 'Triton International Ltd', 'TRTN', 'Industrials', NOW()),
(2333852, 'Sisecam Resources LP', 'PSIRE', 'Materials', NOW()),
(2334115, 'VICTORY CPTL HLDGS INC', 'CVCTR', 'Financials', NOW()),
(2334200, 'CLEAR SECURE INC', 'NCYOU', 'InformationTechnology', NOW()),
(2334244, 'BOISE CASCADE CO', 'COBCC', 'Industrials', NOW()),
(2334275, 'CENTRAL JAPAN RAILWAY CORP', 'CJPRY', 'Industrials', NOW()),
(2334343, 'OLAPLEX HOLDINGS INC', 'COLPX', 'ConsumerStaples', NOW()),
(2334395, 'PGIM HIGH YIELD FUND', 'PHYZX', 'N/A', NOW()),
(2334540, 'MERCATO PARTNERS TRAVERSE IV QP LP', 'None', 'N/A', NOW()),
(2334566, 'SWARTZ CREEK COMMUNITY SCHOOLS', 'None', 'N/A', NOW()),
(2334567, 'CITY OF TEMPE ARIZONA', 'None', 'N/A', NOW()),
(2334572, 'CITY OF FORT LAUDERDALE', 'None', 'N/A', NOW()),
(2334595, 'CITY OF NEW BRAUNFELS TEXAS', 'None', 'N/A', NOW()),
(2334599, 'SOUTHCENTRAL PENNSYLVANIA GENERAL AUTHORITY', 'None', 'N/A', NOW()),
(2334626, 'SHERMAN INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334690, 'CASS COUNTY JOINT WATER RESOURCE DISTRICT NORTH DAKOTA', 'None', 'N/A', NOW()),
(2334698, 'MAIN STREET NATURAL GAS INC', 'None', 'N/A', NOW()),
(2334742, 'HARRIS COUNTY TOLL ROAD AUTHORITY', 'None', 'N/A', NOW()),
(2334756, 'WEST CHESTER AREA SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334757, 'GREATER NEW HAVEN WATER POLLUTION CONTROL AUTHORITY', 'None', 'N/A', NOW()),
(2334825, 'CRINETICS PHARMCTCL INC', 'None', 'Healthcare', NOW()),
(2334834, 'KENT STREET GROUP GP', 'None', 'N/A', NOW()),
(2334839, 'WAKE OF THE FLOOD LLC', 'None', 'N/A', NOW()),
(2334895, 'LANTHEUS HOLDINGS INC', 'None', 'Healthcare', NOW()),
(2335158, 'SERA PROGNOSTICS INC', 'None', 'Healthcare', NOW()),
(429927, 'AUSTIN INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430066, 'BEXAR COUNTY TEXAS', 'None', 'N/A', NOW()),
(430157, 'BOARD OF PUBLIC BUILDINGS OF STATE OF MISSOURI', 'None', 'N/A', NOW()),
(430280, 'BUILDGROUP LLC', 'None', 'N/A', NOW()),
(430283, 'BULLOCH COUNTY GEORGIA', 'None', 'N/A', NOW()),
(430468, 'CENTRAL TEXAS REGIONAL MOBILITY AUTHORITY', 'None', 'N/A', NOW()),
(430612, 'CITY OF CARMEL REDEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(430616, 'CITY OF CHARLOTTE NORTH CAROLINA', 'None', 'N/A', NOW()),
(430656, 'CITY OF GRAND RAPIDS MICHIGAN', 'None', 'N/A', NOW()),
(430669, 'CITY OF HOOVER ALABAMA', 'None', 'N/A', NOW()),
(430688, 'CITY OF LAS VEGAS NEVADA', 'None', 'N/A', NOW()),
(430704, 'CITY OF MESA', 'None', 'N/A', NOW()),
(430710, 'MOBILE COUNTY OF ALABAMA', 'None', 'N/A', NOW()),
(430716, 'CITY OF NORFOLK VIRGINIA', 'None', 'N/A', NOW()),
(430739, 'CITY OF RICHMOND VIRGINIA', 'None', 'N/A', NOW()),
(430748, 'CITY OF SAN ANTONIO TEXAS', 'None', 'N/A', NOW()),
(430792, 'CITY OF WILMINGTON DELEWARE', 'None', 'N/A', NOW()),
(430804, 'CLARK COUNTY WATER RECLAMATION DISTRICT NEVADA', 'None', 'N/A', NOW()),
(431024, 'COUNTY OF DUPAGE ILLINOIS', 'None', 'N/A', NOW()),
(431079, 'COUNTY OF SHELBY', 'None', 'N/A', NOW()),
(431176, 'DALLAS COUNTY TEXAS', 'None', 'N/A', NOW()),
(431232, 'DENTON COUNTY TEXAS', 'None', 'N/A', NOW()),
(431233, 'DENTON INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431247, 'DES MOINES COUNTY IOWA', 'None', 'N/A', NOW()),
(431629, 'FEDERAL FARM CREDIT BANK', 'None', 'N/A', NOW()),
(2334799, 'INVESCO NASDAQ 100 ETF', 'QQQ', 'N/A', NOW()),
(2334894, 'PAR TECHNOLOGY CORP', 'XLK', 'InformationTechnology', NOW()),
(429488, 'AdaptHealth Corp', 'XLV', 'Healthcare', NOW()),
(429928, 'AUSTIN TEXAS UTILITIES AUTHORITY', 'XLU', 'N/A', NOW()),
(430299, 'BWX Technologies Inc', 'XLK', 'Industrials', NOW()),
(430357, 'Canadian Natural Resources Ltd', 'DIA', 'Energy', NOW()),
(430842, 'CNO Financial Group Inc', 'XLF', 'Financials', NOW()),
(430854, 'Coca-Cola Europacific Partners PLC', 'KO', 'ConsumerStaples', NOW()),
(431473, 'Encompass Health Corp', 'XLV', 'Healthcare', NOW()),
(2334535, 'MSD ACQUISITION CORP', 'PMSDA', 'N/A', NOW()),
(2334581, 'ALAMO GROUP INC', 'NCALG', 'Industrials', NOW()),
(2334604, 'DIMENSIO INTER CORE EQUI ETF', 'FDFAI', 'N/A', NOW()),
(2334622, 'DIMENSIONAL US SML CAP ETF', 'FDFAS', 'N/A', NOW()),
(2334631, 'ABRDN PHYSICAL PALLAD SH ETF', 'FPALL', 'N/A', NOW()),
(2334645, 'FRESHPET INC', 'CFRPT', 'ConsumerStaples', NOW()),
(2334711, 'TUHURA BIOSCIENCES INC', 'CHURA', 'N/A', NOW()),
(2334740, 'PIMCO COMMODITIES PLUS STRATEGY FUND', 'PCLPX', 'N/A', NOW()),
(2334769, 'STERLING INFRASTRUCTURE INC', 'CSTRL', 'Industrials', NOW()),
(2334847, 'SPDR® PORTFOLIO MORTGAGE BACKED BOND ETF', 'FSPMB', 'N/A', NOW()),
(2334921, 'FIRST BUSEY CORP', 'PBUSE', 'Financials', NOW()),
(2334991, 'SANDISK CORP', 'PSNDK', 'InformationTechnology', NOW()),
(2335091, 'DUOLINGO INC', 'CDUOL', 'ConsumerDiscretionary', NOW()),
(429529, 'Agios Pharmaceuticals Inc', 'AGIO', 'Healthcare', NOW()),
(429579, 'Alcon Inc', 'ALC', 'Healthcare', NOW()),
(429630, 'ALPS Medical Breakthroughs ETF', 'FSBIO', 'N/A', NOW()),
(429636, 'Altice usa Inc', 'ATUS', 'CommunicationServices', NOW()),
(429758, 'Annaly Capital Management Inc', 'NLY', 'Financials', NOW()),
(429766, 'Australia & New Zealand Banking Group Ltd', 'ANZBY', 'Financials', NOW()),
(429884, 'Astellas Pharma Inc', 'ALPMY', 'Healthcare', NOW()),
(429912, 'AtriCure Inc', 'ATRC', 'Healthcare', NOW()),
(429963, 'The AZEK Company Inc', 'AZEK', 'Industrials', NOW()),
(430083, 'Biomarin Pharmaceutical Inc', 'BMRN', 'Healthcare', NOW()),
(430174, 'Boot Barn Holdings Inc', 'BOOT', 'ConsumerDiscretionary', NOW()),
(430868, 'Cohen & Steers Ltd Duration Preferred and Income Fund Inc', 'LDP', 'N/A', NOW()),
(430917, 'Commerzbank AG, Frankfurt', 'CRZBY', 'Financials', NOW()),
(431104, 'Credit Agricole SA, Paris', 'CRARY', 'Financials', NOW()),
(431107, 'Credit Suisse Group', 'CS', 'Financials', NOW()),
(431166, 'Daikin Industries Ltd', 'DKILY', 'Industrials', NOW()),
(431237, 'Dentsu Group Inc', 'DNTUY', 'CommunicationServices', NOW()),
(431253, 'Deutsche Telekom AG', 'DTEGY', 'CommunicationServices', NOW()),
(431288, 'Diodes Inc', 'DIOD', 'InformationTechnology', NOW()),
(431355, 'Dropbox Inc', 'DBX', 'InformationTechnology', NOW()),
(431361, 'DSV A/S', 'DSDVY', 'Industrials', NOW()),
(431456, 'EMCOR Group Inc', 'EME', 'Industrials', NOW()),
(431497, 'Enerpac Tool Group Corp', 'EPAC', 'Industrials', NOW()),
(431545, 'Equitrans Midstream Corp', 'ETRN', 'Energy', NOW()),
(431589, 'Evolution AB (publ)', 'EVVTY', 'ConsumerDiscretionary', NOW()),
(431597, 'ExlService Holdings Inc', 'EXLS', 'Industrials', NOW()),
(431632, 'Federal Home Loan Mortgage Corp', 'FMCC', 'Financials', NOW()),
(431649, 'Ferrari NV', 'VRACE', 'ConsumerDiscretionary', NOW()),
(432026, 'Goldman Sachs ActiveBeta Emerging Markets Equity ETF', 'GLD', 'N/A', NOW()),
(432371, 'iHeartMedia Inc', 'DIA', 'CommunicationServices', NOW()),
(432692, 'iShares US Technology ETF', 'XLK', 'N/A', NOW()),
(434438, 'Roku Inc', 'ROKU', 'CommunicationServices', NOW()),
(434499, 'Sabra Health Care REIT Inc', 'VNQ', 'RealEstate', NOW()),
(434630, 'The Consumer Staples Select Sector SPDR Fund', 'XLP', 'N/A', NOW()),
(434631, 'The Select Sector SPDR Trust - The Energy Select Sector SPDR Fund', 'XLE', 'N/A', NOW()),
(434866, 'SPDR S&P Biotech ETF', 'XLK', 'N/A', NOW()),
(434909, 'Sprott Physical Gold & Silver Trust', 'GLD', 'N/A', NOW()),
(431801, 'FLORIDA STATE BOARD OF EDUCATION', 'None', 'N/A', NOW()),
(435147, 'TC Energy Corp', 'XLE', 'Energy', NOW()),
(431661, 'FIDELITY CONTRAFUND', 'FCNTX', 'N/A', NOW()),
(431663, 'Fidelity Covington Trust - Fidelity Dividend ETF for Rising Rates', 'FDRR', 'N/A', NOW()),
(431786, 'Flex Ltd', 'FLEX', 'InformationTechnology', NOW()),
(431894, 'FTI Consulting Inc', 'FCN', 'Industrials', NOW()),
(431970, 'Getty Realty Corp', 'GTY', 'RealEstate', NOW()),
(431978, 'Givaudan SA', 'GVDNY', 'Materials', NOW()),
(432049, 'Goodyear Tire & Rubber Co', 'GT', 'ConsumerDiscretionary', NOW()),
(432063, 'Grand Canyon Education Inc', 'LOPE', 'ConsumerDiscretionary', NOW()),
(432097, 'Green Plains Partners LP', 'LPGPP', 'Energy', NOW()),
(432226, 'Helen of Troy Ltd', 'HELE', 'ConsumerDiscretionary', NOW()),
(432242, 'Herc Holdings Inc', 'HRI', 'Industrials', NOW()),
(432256, 'Hexagon AB', 'HXGBY', 'InformationTechnology', NOW()),
(432275, 'Hitachi Ltd', 'HTHIY', 'Industrials', NOW()),
(432299, 'Hong Kong Exchanges and Clearing Ltd', 'HKXCY', 'Financials', NOW()),
(432305, 'Horizon Therapeutics Public Ltd Co', 'HZNP', 'Healthcare', NOW()),
(432319, 'The Howard Hughes Corp', 'HHC', 'RealEstate', NOW()),
(432358, 'Icon PLC', 'CICLR', 'Healthcare', NOW()),
(432360, 'IDACORP Inc', 'IDA', 'Utilities', NOW()),
(432472, 'Intercontinental Hotels Group PLC', 'LCIHG', 'ConsumerDiscretionary', NOW()),
(432479, 'Intesa Sanpaolo SPA', 'ISNPY', 'Financials', NOW()),
(432537, 'Ionis Pharmaceuticals Inc', 'IONS', 'Healthcare', NOW()),
(432569, 'iShares Core Dividend Growth ETF', 'FDGRO', 'N/A', NOW()),
(432571, 'iShares Core MSCI EAFE ETF', 'FIEFA', 'N/A', NOW()),
(432727, 'James Hardie Industries PLC', 'LCJHX', 'Materials', NOW()),
(432742, 'Japan Tobacco Inc', 'JAPAY', 'ConsumerStaples', NOW()),
(432746, 'JBG SMITH Properties', 'JBGS', 'RealEstate', NOW()),
(432840, 'Kddi Corp', 'KDDIY', 'CommunicationServices', NOW()),
(432931, 'Kubota Corp', 'KUBTY', 'Industrials', NOW()),
(433058, 'Lithia Motors Inc', 'LAD', 'ConsumerDiscretionary', NOW()),
(433060, 'Littelfuse Inc', 'LFUS', 'InformationTechnology', NOW()),
(433075, 'Lloyds Banking Group PLC', 'LCLYG', 'Financials', NOW()),
(433094, 'Lonza Group AG, Zuerich', 'LZAGY', 'Healthcare', NOW()),
(433172, 'Magna International Inc', 'MGA', 'ConsumerDiscretionary', NOW()),
(433475, 'Morningstar Inc', 'MORN', 'Financials', NOW()),
(433490, 'MS&AD Insurance Group Holdings Inc', 'MSADY', 'Financials', NOW()),
(433550, 'National Retail Properties Inc', 'NNN', 'RealEstate', NOW()),
(433643, 'The New York Times Company', 'NYT', 'CommunicationServices', NOW()),
(433654, 'NICE Ltd', 'NICE', 'InformationTechnology', NOW()),
(433743, 'NUANCE MID CAP VALUE FUND', 'NMVZX', 'N/A', NOW()),
(433757, 'Nushares ETF Trust - Nuveen ESG Large Cap ETF', 'FNULC', 'N/A', NOW()),
(433831, 'Olympus Corp', 'OLYMY', 'Healthcare', NOW()),
(433887, 'Orsted A/S', 'DNNGY', 'Utilities', NOW()),
(433896, 'Otsuka Holdings Co Ltd', 'OTSKY', 'Healthcare', NOW()),
(433953, 'Park Hotels & Resorts Inc', 'PK', 'RealEstate', NOW()),
(433969, 'Patrick Industries Inc', 'PATK', 'ConsumerDiscretionary', NOW()),
(434121, 'Polaris Inc', 'PII', 'ConsumerDiscretionary', NOW()),
(434146, 'PotlatchDeltic Corp', 'PCH', 'RealEstate', NOW()),
(434317, 'RBC Bearings Inc', 'RBC', 'Industrials', NOW()),
(434346, 'Regency Centers Corp', 'REG', 'RealEstate', NOW()),
(434596, 'Schwab US Large-Cap ETF', 'FSCHX', 'N/A', NOW()),
(434662, 'Seven & I Holdings Co Ltd', 'SVNDY', 'ConsumerStaples', NOW()),
(434748, 'Smith & Nephew PLC', 'LCSNN', 'Healthcare', NOW()),
(434767, 'Softbank Group Corp', 'SFTBY', 'CommunicationServices', NOW()),
(434813, 'SouthState Corporation', 'SSB', 'Financials', NOW()),
(434820, 'Southwest Gas Holdings Inc', 'SWX', 'Utilities', NOW()),
(435048, 'Sumitomo Chemical Co Ltd', 'SOMMY', 'Materials', NOW()),
(435070, 'Suntory Beverage & Food Ltd', 'STBFY', 'ConsumerStaples', NOW()),
(435095, 'Symrise AG', 'SYIEY', 'Materials', NOW()),
(435206, 'Terex Corp', 'TEX', 'Industrials', NOW()),
(435222, 'Texas Pacific Land Corp', 'TPL', 'Energy', NOW()),
(435247, 'The Shyft Group Inc', 'SHYF', 'Industrials', NOW()),
(435284, 'Tokio Marine Holdings Inc', 'TKOMY', 'Financials', NOW()),
(435433, 'Ubiquiti Inc', 'UI', 'InformationTechnology', NOW()),
(432120, 'GS FINANCE CORP', 'None', 'N/A', NOW()),
(432539, 'IOWA FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(432894, 'KIRKOSWALD GLOBAL MACRO FUND LP', 'None', 'N/A', NOW()),
(433144, 'LYNETT CAPITAL PARTNERS II LP', 'None', 'N/A', NOW()),
(433341, 'METROPOLITAN GOVERNMENT OF NASHVILLE AND DAVIDSON COUNTY TENNESSEE', 'None', 'N/A', NOW()),
(433347, 'METROPOLITAN WATER DISTRICT OF SOUTHERN CALIFORNIA', 'None', 'N/A', NOW()),
(433690, 'NORTH ALLEGHENY SCHOOL DISTRICT ALLEGHENY COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(433816, 'OKLAHOMA WATER RESOURCES BOARD', 'None', 'N/A', NOW()),
(433959, 'PARTNERRE FINANCE B LLC', 'None', 'N/A', NOW()),
(434974, 'STATE OF NEVADA', 'None', 'N/A', NOW()),
(434984, 'STATE OF OKLAHOMA', 'None', 'N/A', NOW()),
(434985, 'STATE OF OREGON', 'None', 'N/A', NOW()),
(435129, 'TAMPA FLORIDA SOLID WASTE SYSTEM', 'None', 'N/A', NOW()),
(435516, 'UNIVERSITY OF TEXAS', 'None', 'N/A', NOW()),
(435817, 'WAXAHACHIE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(478121, 'FLORIDA HOMELOAN CORP', 'None', 'N/A', NOW()),
(2019743, 'CITY OF SAN ANTONIO TEXAS WATER SYSTEM', 'None', 'N/A', NOW()),
(2265164, 'CITY OF PHOENIX ARIZONA', 'None', 'N/A', NOW()),
(2331603, 'CITY OF OMAHA NEBRASKA', 'None', 'N/A', NOW()),
(2331863, 'NEW JERSEY EDUCATIONAL FACILITIES AUTHORITY', 'None', 'N/A', NOW()),
(2331987, 'PFLUGERVILLE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2332587, 'IBM INTERNATIONAL GROUP CAPITAL', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;