INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(432422, 'Infinera Corp', 'INFN', 'InformationTechnology', NOW()),
(432475, 'The Interpublic Group of Cos Inc', 'IPG', 'CommunicationServices', NOW()),
(433364, 'MGM Resorts International', 'MGM', 'ConsumerDiscretionary', NOW()),
(433594, 'Neurocrine Biosciences Inc', 'NBIX', 'Healthcare', NOW()),
(433724, 'NortonLifeLock Inc', 'GEN', 'InformationTechnology', NOW()),
(433744, 'Nucor Corp', 'NUE', 'Materials', NOW()),
(434647, 'Sempra', 'SRE', 'Utilities', NOW()),
(434737, 'Skyworks Solutions Inc', 'SWKS', 'InformationTechnology', NOW()),
(434763, 'Societe Generale Group', 'SCGLY', 'Financials', NOW()),
(434785, 'Sony Group Corporation', 'SONY', 'ConsumerDiscretionary', NOW()),
(435567, 'Valvoline Inc', 'VVV', 'ConsumerDiscretionary', NOW()),
(435682, 'Vertiv Holdings Co', 'VRT', 'Industrials', NOW()),
(435994, 'Xylem Inc', 'XYL', 'Industrials', NOW()),
(2334588, 'CORE & MAIN INC', 'NCCNM', 'Industrials', NOW()),
(430290, 'Burlington Stores Inc', 'BURL', 'ConsumerDiscretionary', NOW()),
(431625, 'Farmers & Merchants Bancorp Inc', 'FMAO', 'Financials', NOW()),
(431926, 'Garmin Ltd', 'GRMN', 'ConsumerDiscretionary', NOW()),
(433139, 'LVMH Moet Hennessy Louis Vuitton SE', 'LVMHF', 'ConsumerDiscretionary', NOW()),
(433919, 'Packaging Corp Of America', 'PKG', 'Materials', NOW()),
(434255, 'PulteGroup Inc', 'PHM', 'ConsumerDiscretionary', NOW()),
(434747, 'A. O. Smith Corp', 'AOS', 'Industrials', NOW()),
(435205, 'Teradyne Inc', 'TER', 'InformationTechnology', NOW()),
(435353, 'The Travelers Companies Inc', 'TRV', 'Financials', NOW()),
(1869593, 'Liberty Global PLC', 'LBYAV', 'CommunicationServices', NOW()),
(429653, 'Amcor PLC', 'CAMCR', 'Materials', NOW()),
(429845, 'Arrow Electronics Inc', 'ARW', 'InformationTechnology', NOW()),
(430304, 'CACI International Inc', 'CACI', 'Industrials', NOW()),
(430351, 'Campbell Soup Co', 'CPB', 'ConsumerStaples', NOW()),
(430445, 'Celanese Corp', 'CE', 'Materials', NOW()),
(430828, 'Cloudflare Inc', 'NET', 'InformationTechnology', NOW()),
(431326, 'Donaldson Co Inc', 'DCI', 'Industrials', NOW()),
(431559, 'Essex Property Trust Inc', 'ESS', 'RealEstate', NOW()),
(431809, 'FMC Corp', 'FMC', 'Materials', NOW()),
(431930, 'Gates Industrial Corp PLC', 'CGTES', 'Industrials', NOW()),
(432366, 'IDEX Corp', 'IEX', 'Industrials', NOW()),
(432550, 'Iron Mountain Inc', 'IRM', 'RealEstate', NOW()),
(432950, 'Lamb Weston Holdings Inc', 'LW', 'ConsumerStaples', NOW()),
(433066, 'Live Nation Entertainment Inc', 'LYV', 'CommunicationServices', NOW()),
(433440, 'Molson Coors Beverage Company', 'TAP', 'ConsumerStaples', NOW()),
(433446, 'MongoDB Inc', 'MDB', 'InformationTechnology', NOW()),
(433603, 'Newell Brands Inc', 'NWL', 'ConsumerDiscretionary', NOW()),
(433686, 'Nordson Corp', 'NDSN', 'Industrials', NOW()),
(434096, 'Pioneer Natural Resources Co', 'PXD', 'Energy', NOW()),
(434174, 'Primerica Inc', 'PRI', 'Financials', NOW()),
(2333803, 'DEPARTMENT OF STATE PENNSYLVANIA', 'None', 'N/A', NOW()),
(2334327, 'HPS SPECIAL SITUATIONS OPPORTUNITY FUND II LP', 'None', 'N/A', NOW()),
(429898, 'CITY OF ATLANTA', 'None', 'N/A', NOW()),
(433405, 'MISSISSIPPI DEVELOPMENT BANK', 'None', 'N/A', NOW()),
(434960, 'STATE OF ILLINOIS', 'None', 'N/A', NOW()),
(446117, 'WASHINGTON KING COUNTY', 'None', 'N/A', NOW()),
(2331401, 'TRIBOROUGH BRIDGE AND TUNNEL AUTHORITY', 'None', 'N/A', NOW()),
(2333494, 'CME CORN', 'None', 'N/A', NOW()),
(430630, 'CITY OF DALLAS', 'None', 'N/A', NOW()),
(430953, 'CONNECTICUT HOUSING FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(431178, 'CITIES OF DALLAS AND FORT WORTH TEXAS', 'None', 'N/A', NOW()),
(433632, 'NEW YORK CITY MUNICIPAL WATER FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(434969, 'STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(435227, 'TEXAS TRANSPORTATION COMMISSION', 'None', 'N/A', NOW()),
(435982, 'Wynn Resorts Ltd', 'None', 'ConsumerDiscretionary', NOW()),
(443910, 'CITY OF HOUSTON', 'None', 'N/A', NOW()),
(2331058, 'BRAZIL GOVERNMENT BONDS', 'None', 'N/A', NOW()),
(2334849, 'SKI MASK DOG', 'None', 'N/A', NOW()),
(429827, 'ARIZONA INDUSTRIAL DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(433805, 'OHIO STATE UNIVERSITY', 'None', 'N/A', NOW()),
(2334550, 'INTAPP INC', 'None', 'InformationTechnology', NOW()),
(430576, 'CITY AND COUNTY OF DENVER COLORADO', 'None', 'N/A', NOW()),
(430622, 'CITY OF CLEVELAND OHIO', 'None', 'N/A', NOW()),
(431374, 'DXC Technology Co', 'XLK', 'InformationTechnology', NOW()),
(432025, 'Goldman Sachs AccessTreasury 0-1 Year ETF', '^TNX', 'N/A', NOW()),
(434285, 'Quest Diagnostics Inc', 'DIA', 'Healthcare', NOW()),
(431586, 'Eversource Energy', 'XLE', 'Utilities', NOW()),
(432553, 'iShares 10-20 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(432649, 'iShares Trust - iShares Russell 2000 ETF', 'IWM', 'N/A', NOW()),
(433019, 'Liberty Media Corp Braves Group', 'DIA', 'CommunicationServices', NOW()),
(434755, 'Snap-On Inc', 'SNAP', 'Industrials', NOW()),
(430092, 'BITCOIN', 'BTC-USD', 'N/A', NOW()),
(431272, 'Diamondback Energy Inc', 'XLE', 'Energy', NOW()),
(432344, 'Hyatt Hotels Corp', 'T', 'ConsumerDiscretionary', NOW()),
(432648, 'iShares Russell 1000 Value ETF', 'IWM', 'N/A', NOW()),
(2334180, 'SHOALS TECHNOLOGIES GRP INC', 'XLK', 'Industrials', NOW()),
(430457, 'CenterPoint Energy Inc', 'XLE', 'Utilities', NOW()),
(2332102, 'Southern States Bancshares Inc', 'SSBK', 'Financials', NOW()),
(2334019, 'CONSTELLATION ENE CORP', 'RPCEG', 'Utilities', NOW()),
(430035, 'Beacon Roofing Supply Inc', 'BECN', 'Industrials', NOW()),
(430075, 'BHP Group Ltd', 'BHP', 'Materials', NOW()),
(430175, 'Booz Allen Hamilton Holding Corporation', 'BAH', 'Industrials', NOW()),
(431343, 'Dover Corp', 'DOV', 'Industrials', NOW()),
(432203, 'H D F C Bank Ltd', 'HDB', 'Financials', NOW()),
(432717, 'Jabil Inc', 'JBL', 'InformationTechnology', NOW()),
(433067, 'Livent Corp', 'LTHM', 'Materials', NOW()),
(434459, 'Royal Caribbean Group', 'RCL', 'ConsumerDiscretionary', NOW()),
(434751, 'The J M Smucker Company', 'SJM', 'ConsumerStaples', NOW()),
(435663, 'Ventas Inc', 'VTR', 'RealEstate', NOW()),
(2331138, 'NU HOLDINGS LTD', 'LTDNU', 'Financials', NOW()),
(2334103, 'Ranger Equity Bear ETF', 'FHDGE', 'N/A', NOW()),
(2334228, 'HALEON PLC', 'LCHLN', 'Healthcare', NOW()),
(430342, 'Camden Property Trust', 'CPT', 'RealEstate', NOW()),
(430418, 'Catalent Inc', 'CTLT', 'Healthcare', NOW()),
(431413, 'Edison International', 'EIX', 'Utilities', NOW()),
(431986, 'Glaxosmithkline PLC', 'LCGSK', 'Healthcare', NOW())
ON CONFLICT (id) DO NOTHING;