INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(434700, 'Signature Bank', 'SBNY', 'Financials', NOW()),
(434734, 'Skyline Champion Corp', 'SKY', 'ConsumerDiscretionary', NOW()),
(435539, 'US Foods Holding Corp', 'USFD', 'ConsumerStaples', NOW()),
(435636, 'Vanguard Total International Bond ETF', 'FBNDX', 'N/A', NOW()),
(435544, 'US TREASURY BILLS', '^TNX', 'N/A', NOW()),
(429648, 'Amazon.com Inc', 'AMZN', 'ConsumerDiscretionary', NOW()),
(433981, 'PayPal Holdings Inc', 'PYPL', 'Financials', NOW()),
(430568, 'Cisco Systems Inc', 'CSCO', 'InformationTechnology', NOW()),
(433650, 'NextEra Energy Inc', 'XLE', 'Utilities', NOW()),
(433531, 'Nasdaq Inc', 'QQQ', 'Financials', NOW()),
(429590, 'Align Technology Inc', 'XLK', 'Healthcare', NOW()),
(431493, 'Energy Transfer LP', 'XLE', 'Energy', NOW()),
(1282634, 'Vanguard S&P 500 ETF', 'SPY', 'N/A', NOW()),
(2331193, 'Vishay Intertechnology Inc', 'XLK', 'InformationTechnology', NOW()),
(435018, 'Stifel Financial Corp', 'XLF', 'Financials', NOW()),
(430865, 'Cognizant Technology Solutions Corp', 'XLK', 'InformationTechnology', NOW()),
(434758, 'Snowflake Inc', 'SNOW', 'InformationTechnology', NOW()),
(432176, 'The Hartford Financial Services Group Inc', 'XLF', 'Financials', NOW()),
(436015, 'Zebra Technologies Corp', 'XLK', 'InformationTechnology', NOW()),
(433023, 'Liberty Media Corp SiriusXM Group', 'DIA', 'CommunicationServices', NOW()),
(1604614, 'Formula One Group - The Liberty Media Group', 'DIA', 'CommunicationServices', NOW()),
(1689224, 'ETHEREUM', 'ETH-USD', 'N/A', NOW()),
(435175, 'Teledyne Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(433421, 'Mitsubishi UFJ Financial Group', 'XLF', 'Financials', NOW()),
(431504, 'ENN Energy Holdings Ltd', 'XLE', 'Utilities', NOW()),
(434754, 'Snap Inc', 'SNAP', 'CommunicationServices', NOW()),
(431676, 'Fidelity National Financial Inc FNF Group', 'XLF', 'Financials', NOW()),
(432559, 'iShares 3-7 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(436028, 'Zoom Video Communications Inc', 'ZM', 'InformationTechnology', NOW()),
(434913, 'SPX Technologies Inc', 'XLK', 'Industrials', NOW()),
(2334639, 'CITY OF MINNEAPOLIS MN/ST PAUL HOUSING & REDEVELOPMENT AUTHORITY (ALLINA HEALTH SYSTEM)', 'XLV', 'N/A', NOW()),
(435163, 'Techtronic Industries Co Ltd', 'XLK', 'Industrials', NOW()),
(433153, 'MACOM Technology Solutions Holdings Inc', 'XLK', 'InformationTechnology', NOW()),
(2335065, 'GOLDMAN SACHS FINANCIAL SQUARE TREASURY SOLUTIONS FUND', 'SQ', 'N/A', NOW()),
(433177, 'MAI MANAGED VOLATILITY FUND', '^VIX', 'N/A', NOW()),
(433794, 'OceanFirst Financial Corp', 'XLF', 'Financials', NOW()),
(433910, 'Pacer Funds Trust - Pacer Benchmark Data & Infrastructure Real estate SCTR ETF', 'VNQ', 'N/A', NOW()),
(2334541, 'MACOMB INTERMEDIATE SCHOOL DISTRICT', 'DIA', 'N/A', NOW()),
(2334646, 'CANADIAN COUNTY EDUCATIONAL FACILITIES AUTHORITY', 'DIA', 'N/A', NOW()),
(432007, 'Global X NASDAQ-100 Covered Call ETF', 'QQQ', 'N/A', NOW()),
(433180, 'MAINE HEALTH AND HIGHER EDUCATIONAL FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(435447, 'UMB Financial Corp', 'XLF', 'Financials', NOW()),
(435891, 'Wheaton Precious Metals Corp', 'META', 'Materials', NOW()),
(2334144, 'NORTHEAST WISCONSIN TECHNICAL COLLEGE DISTRICT WISCONSIN', 'XLK', 'N/A', NOW()),
(2334874, 'ISHARES BITCOIN TRUST ETF', 'BTC-USD', 'N/A', NOW()),
(2335011, 'FEDERATED TREASURY OBLIGATIONS FUND', '^TNX', 'N/A', NOW()),
(431558, 'Essential Utilities Inc', 'XLU', 'Utilities', NOW()),
(432207, 'Healthcare Realty Trust Inc', 'XLV', 'RealEstate', NOW()),
(433166, 'Madison Square Garden Entertainment Corp', 'SQ', 'CommunicationServices', NOW()),
(435115, 'Tactile Systems Technology Inc', 'XLK', 'Healthcare', NOW()),
(2332216, 'ZoomInfo Technologies Inc', 'ZM', 'CommunicationServices', NOW()),
(2333965, 'ALAMOS GOLD INC', 'GLD', 'Materials', NOW()),
(2334114, 'DAQO NEW ENERGY CORP', 'XLE', 'InformationTechnology', NOW()),
(2334516, 'JPMORGAN BETABULDR EUROP ETF', 'JPM', 'N/A', NOW()),
(2334651, 'SEVEN BRIDGES ENERGY OPPORTUNITIES FUND III LP', 'XLE', 'N/A', NOW()),
(2334989, 'ALKAMI TECHNOLOGY INC', 'XLK', 'InformationTechnology', NOW()),
(2335183, 'NUVEEN REAL ESTATE SECURITIES FUND', 'VNQ', 'N/A', NOW()),
(430578, 'CITY AND COUNTY OF SAN FRANCISCO', 'CSCO', 'N/A', NOW()),
(431695, 'First American Financial Corp', 'XLF', 'Financials', NOW()),
(432058, 'Graftech International Ltd', 'XLK', 'Industrials', NOW()),
(432598, 'iShares iBonds Dec 2026 Term Treasury ETF', '^TNX', 'N/A', NOW()),
(433833, 'Omega Healthcare Investors Inc', 'XLV', 'RealEstate', NOW()),
(434091, 'Pinnacle Financial Partners Inc', 'XLF', 'Financials', NOW()),
(435481, 'United Utilities Group PLC', 'XLU', 'Utilities', NOW()),
(2329948, 'STATE OF CONNECTICUT HEALTH AND EDUCATIONAL FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(2332087, 'United Health Products Inc', 'XLV', 'Healthcare', NOW()),
(2334010, 'PUBLIC UTILITIES COMMISSION OF CITY AND COUNTY OF SAN FRANCISCO', 'CSCO', 'N/A', NOW()),
(2334084, 'JPMORGAN NASDAQ EQTY P I ETF', 'JPM', 'N/A', NOW()),
(2334355, 'CCC INTELLIGENT SOLUTIONS HL', 'INTC', 'InformationTechnology', NOW()),
(2334407, 'DEPARTMENT OF MENTAL HEALTH AND DEPARTMENT OF DEVELOPMENTAL DISABILITIES OF THE STATE OF OHIO', 'XLV', 'N/A', NOW()),
(2334658, 'INDIAN HILL EXEMPTED VILLAGE SCHOOL DISTRICT', 'DIA', 'N/A', NOW()),
(2334826, 'SILVER POINTSILVER POINT DISTRESSED OPPORTUNITY INSTITUTIONAL PARTNERS II LP', 'SLV', 'N/A', NOW()),
(435724, 'VIRGINIA COMMONWEALTH TRANSPORTATION BOARD', 'None', 'N/A', NOW()),
(2332187, 'UNIVERSITY OF OKLAHOMA', 'None', 'N/A', NOW()),
(2333441, 'ARKANSAS DEVELOPMENT FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(2333500, 'MANATEE COUNTY', 'None', 'N/A', NOW()),
(2334079, 'EL PASO WATER & SEWER', 'None', 'N/A', NOW()),
(2334101, 'WASHINGTON COUNTY OREGON', 'None', 'N/A', NOW()),
(2334379, 'CARTERBALDWIN', 'None', 'N/A', NOW()),
(2334594, 'MINNESOTA RURAL WATER FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(2334608, 'HAMPTON ROADS TRANSPORTATION ACCOUNTABILITY COMMISSION', 'None', 'N/A', NOW()),
(2334661, 'FLORIDA HOUSING FINANCE CORP.', 'None', 'N/A', NOW()),
(2334677, 'SOUTH CAROLINA STATE HOUSING FINANCE AND DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(2334703, 'PARAGON 28 INC', 'None', 'Healthcare', NOW()),
(2334858, 'BELLEFONTE AREA SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334859, 'EAGLE MOUNTAIN SAGINAW ISD', 'None', 'N/A', NOW()),
(2335052, '3G FUND VI LP', 'None', 'N/A', NOW()),
(430325, 'CALIFORNIA STATE PUBLIC WORKS BOARD', 'None', 'N/A', NOW()),
(430326, 'CALIFORNIA STATE UNIVERSITY', 'None', 'N/A', NOW()),
(430489, 'CHARLESTON COUNTY SCHOOL DISTRICT SOUTH CAROLINA', 'None', 'N/A', NOW()),
(430720, 'CITY OF OKLAHOMA CITY', 'None', 'N/A', NOW()),
(431012, 'COUNTY OF BROWARD', 'None', 'N/A', NOW()),
(431023, 'COUNTY OF CUYAHOGA', 'None', 'N/A', NOW()),
(431030, 'COUNTY OF HARRIS TEXAS', 'None', 'N/A', NOW()),
(431158, 'CYPRESS FAIRBANKS INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431179, 'DALLAS INDEPENDENT SCHOOL DISTRICT DALLAS COUNTY TEXAS', 'None', 'N/A', NOW()),
(431305, 'DISTRICT OF COLUMBIA WATER AND SEWER AUTHORITY', 'None', 'N/A', NOW()),
(431965, 'GEORGIA HOUSING AND FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(432075, 'GRAPEVINE COLLEYVILLE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(432948, 'LAMAR CONSOLIDATED INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;