INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(433979, 'Paylocity Holding Corp', 'PCTY', 'Industrials', NOW()),
(434000, 'Pembina Pipeline Corp', 'PBA', 'Energy', NOW()),
(434016, 'Pentair PLC', 'LCPNR', 'Industrials', NOW()),
(434061, 'Phreesia Inc', 'PHR', 'Healthcare', NOW()),
(434103, 'Plains All American Pipeline LP', 'LPPAA', 'Energy', NOW()),
(434110, 'PLDT Inc', 'PHI', 'CommunicationServices', NOW()),
(434196, 'Progress Software Corp', 'PRGS', 'InformationTechnology', NOW()),
(434277, 'Qualys Inc', 'QLYS', 'InformationTechnology', NOW()),
(434298, 'Radius Global Infrastructure Inc', 'RADI', 'CommunicationServices', NOW()),
(434304, 'Ralph Lauren Corp', 'RL', 'ConsumerDiscretionary', NOW()),
(434386, 'Rexford Industrial Realty Inc', 'REXR', 'RealEstate', NOW()),
(434406, 'RingCentral Inc', 'RNG', 'InformationTechnology', NOW()),
(434465, 'Royalty Pharma PLC', 'CRPRX', 'Healthcare', NOW()),
(433367, 'MIAMI DADE COUNTY SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433372, 'MICHIGAN FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(433619, 'NEW MEXICO FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(433803, 'OHIO HOUSING FINANCE AGENCY', 'None', 'N/A', NOW()),
(433815, 'OKLAHOMA TURNPIKE AUTHORITY', 'None', 'N/A', NOW()),
(433942, 'PARCHMENT SCHOOL DISTRICT COUNTY OF KALAMAZOO STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(434557, 'SARASOTA COUNTY FLORIDA', 'None', 'N/A', NOW()),
(434572, 'SCHOOL BOARD OF BROWARD COUNTY FLORIDA', 'None', 'N/A', NOW()),
(434633, 'The Industrial Select Sector SPDR Fund', 'XLI', 'N/A', NOW()),
(434642, 'Selective Insurance Group Inc', 'SIGI', 'Financials', NOW()),
(434671, 'SGS Sa', 'SGSOY', 'Industrials', NOW()),
(434681, 'Shin-Etsu Chemical Co Ltd', 'SHECY', 'Materials', NOW()),
(434704, 'Silicon Laboratories Inc', 'SLAB', 'InformationTechnology', NOW()),
(434783, 'Sonova Holding AG', 'SONVY', 'Healthcare', NOW()),
(434838, 'SPDR Bloomberg Barclays Corporate Bond ETF', 'FSPBO', 'N/A', NOW()),
(434871, 'SPDR S&P Regional Banking ETF', 'TFKRE', 'N/A', NOW()),
(434891, 'Splunk Inc', 'SPLK', 'InformationTechnology', NOW()),
(434952, 'STATE OF COLORADO', 'None', 'N/A', NOW()),
(434961, 'STATE OF IOWA', 'None', 'N/A', NOW()),
(434964, 'STATE OF KANSAS DEPARTMENT OF TRANSPORTATION', 'None', 'N/A', NOW()),
(434966, 'STATE OF MAINE', 'None', 'N/A', NOW()),
(434971, 'STATE OF MISSISSIPPI', 'None', 'N/A', NOW()),
(434979, 'STATE OF NEW MEXICO', 'None', 'N/A', NOW()),
(434986, 'STATE OF RHODE ISLAND', 'None', 'N/A', NOW()),
(435226, 'TEXAS STATE UNIVERSITY SYSTEM', 'None', 'N/A', NOW()),
(435401, 'TROY SCHOOL DISTRICT COUNTY OF OAKLAND STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(435437, 'UC4K INVESTMENTS LLC', 'None', 'N/A', NOW()),
(435723, 'VIRGINIA COLLEGE BUILDING AUTHORITY', 'None', 'N/A', NOW()),
(435726, 'VIRGINIA STATE PUBLIC SCHOOL AUTHORITY', 'None', 'N/A', NOW()),
(435791, 'WASHINGTON COUNTY TENNESSEE', 'None', 'N/A', NOW()),
(435793, 'WASHINGTON DC METRO AREA TRANS', 'None', 'N/A', NOW()),
(435803, 'WASHOE COUNTY NEVADA', 'None', 'N/A', NOW()),
(435976, 'UNIFIED GOVERNMENT OF WYANDOTTE COUNTY AND KANSAS CITY KANSAS', 'None', 'N/A', NOW()),
(603019, 'COUNTY OF LOS ANGELES', 'None', 'N/A', NOW()),
(620167, 'STATE OF NEW YORK', 'None', 'N/A', NOW()),
(727175, 'ALAMO COMMUNITY COLLEGE DISTRICT', 'None', 'N/A', NOW()),
(825289, 'STATE OF SOUTH CAROLINA', 'None', 'N/A', NOW()),
(2149018, 'PENNSYLVANIA STATE SYSTEM OF HIGHER EDUCATION', 'None', 'N/A', NOW()),
(2271839, 'CITY OF ST LOUIS MISSOURI', 'None', 'N/A', NOW()),
(2331334, 'LAKE COOK KANE AND MCHENRY COUNTIES ILLINOIS', 'None', 'N/A', NOW()),
(2331393, 'YIHENG CAPITAL PARTNERS LP', 'None', 'N/A', NOW()),
(2331430, 'PORT OF PORTLAND OREGON', 'None', 'N/A', NOW()),
(2332013, 'LOS ANGELES COUNTY METROPOLITAN TRANSPORTATION AUTHORITY', 'None', 'N/A', NOW()),
(2332160, 'DALLAS FORT WORTH INTERNATIONAL AIRPORT', 'None', 'N/A', NOW()),
(2332548, 'WYOMING PUBLIC SCHOOLS', 'None', 'N/A', NOW()),
(2332593, 'ILLINOIS STATE UNIVERSITY', 'None', 'N/A', NOW()),
(2332712, 'CITY OF MIAMI FLORIDA', 'None', 'N/A', NOW()),
(2333290, 'MURFREESBORO CITY OF TENNESSEE', 'None', 'N/A', NOW()),
(435062, 'Suncor Energy Inc', 'XLE', 'Energy', NOW()),
(435172, 'Teladoc Health Inc', 'XLV', 'Healthcare', NOW()),
(435600, 'Vanguard Global ex-U.S. Real Estate ETF', 'VNQ', 'N/A', NOW()),
(435676, 'VERMONT EDUCATIONAL AND HEALTH BUILDINGS FINANCING AGENCY', 'XLV', 'N/A', NOW()),
(435952, 'Woodside Energy Group Ltd', 'XLE', 'Energy', NOW()),
(435995, 'Yamana Gold Inc', 'GLD', 'Materials', NOW()),
(1452871, 'NEW YORK CITY HEALTH AND HOSPITALS CORP', 'XLV', 'N/A', NOW()),
(2274783, 'Northern Oil and Gas Inc', 'USO', 'Energy', NOW()),
(2331192, 'SAN FRANCISCO UNIFIED SCHOOL DISTRICT', 'CSCO', 'N/A', NOW()),
(2331778, 'SOUTH DAKOTA DEPARTMENT OF HEALTH', 'XLV', 'N/A', NOW()),
(2332010, 'Genworth Financial Inc', 'XLF', 'Financials', NOW()),
(2332816, 'SPDR S&P Metals & Mining ETF', 'META', 'N/A', NOW()),
(2333267, 'Fortescue Metals Group Ltd', 'META', 'Materials', NOW()),
(434939, 'Starwood Property Trust Inc', 'STWD', 'Financials', NOW()),
(435066, 'Sunoco LP', 'LPSUN', 'Energy', NOW()),
(435073, 'Supernus Pharmaceuticals Inc', 'SUPN', 'Healthcare', NOW()),
(435083, 'Swedbank AB', 'SWDBY', 'Financials', NOW()),
(435086, 'Sweetgreen Inc', 'SG', 'ConsumerDiscretionary', NOW()),
(435164, 'Teck Resources Ltd', 'TECK', 'Materials', NOW()),
(435181, 'Telenor ASA', 'TELNY', 'CommunicationServices', NOW()),
(435187, 'TELUS Corp', 'TU', 'CommunicationServices', NOW()),
(435233, 'Textron Inc', 'TXT', 'Industrials', NOW()),
(435245, 'Thermon Group Holdings Inc', 'THR', 'Industrials', NOW()),
(435253, 'Thor Industries Inc', 'THO', 'ConsumerDiscretionary', NOW()),
(435290, 'Toray Industries Inc', 'TRYIY', 'Materials', NOW()),
(435296, 'Managed Portfolio Series Tortoise North American Pipeline Fund', 'TPYP', 'N/A', NOW()),
(435298, 'Toshiba Corp', 'TOSYY', 'Industrials', NOW()),
(435332, 'Toyota Motor Credit Corp', 'A', 'Financials', NOW()),
(435354, 'Travel Plus Leisure Co', 'TNL', 'ConsumerDiscretionary', NOW()),
(435377, 'Trinity Industries Inc', 'TRN', 'Industrials', NOW()),
(435523, 'Upm-Kymmene Corp', 'UPMMY', 'Materials', NOW()),
(435527, 'Urban Edge Properties', 'UE', 'RealEstate', NOW()),
(435555, 'Valaris Ltd', 'ESV', 'Energy', NOW()),
(435690, 'ViaSat Inc', 'VSAT', 'InformationTechnology', NOW()),
(435820, 'WD-40 Co', 'WDFC', 'ConsumerStaples', NOW()),
(435875, 'Westpac Banking Corp', 'WBK', 'Financials', NOW()),
(435964, 'World Wrestling Entertainment Inc', 'WWE', 'CommunicationServices', NOW()),
(435966, 'W. P. Carey Inc', 'WPC', 'RealEstate', NOW()),
(435968, 'WPP PLC', 'LCWPP', 'CommunicationServices', NOW())
ON CONFLICT (id) DO NOTHING;