INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(431726, 'First Trust Dow Jones Internet Index Fund', 'DIA', 'N/A', NOW()),
(432133, 'Gulfport Energy Corp', 'XLE', 'Energy', NOW()),
(432228, 'Helios Technologies Inc', 'XLK', 'Industrials', NOW()),
(432229, 'Helix Energy Solutions Group Inc', 'XLE', 'Energy', NOW()),
(432466, 'Intellia Therapeutics Inc', 'INTC', 'Healthcare', NOW()),
(432591, 'iShares Gold Trust', 'GLD', 'N/A', NOW()),
(432808, 'JPMORGAN STRATEGIC INCOME OPPORTUNITIES FUND', 'JPM', 'N/A', NOW()),
(433085, 'Logitech International SA, Apples', 'AAPL', 'InformationTechnology', NOW()),
(430919, 'Commonwealth Bank of Australia', 'CMWAY', 'Financials', NOW()),
(430935, 'CommVault Systems Inc', 'CVLT', 'InformationTechnology', NOW()),
(430959, 'Consolidated Edison Inc', 'ED', 'Utilities', NOW()),
(430996, 'Corporate Office Properties Trust', 'CDP', 'RealEstate', NOW()),
(431131, 'CSL Ltd', 'CSLLY', 'Healthcare', NOW()),
(431150, 'Cushman & Wakefield Ltd', 'CWK', 'RealEstate', NOW()),
(431165, 'Daiichi Sankyo Company Ltd', 'DSNKY', 'Healthcare', NOW()),
(431170, 'Daiwa House Industry Co Ltd', 'DWAHY', 'RealEstate', NOW()),
(431245, 'The Descartes Systems Group Inc', 'DSGX', 'InformationTechnology', NOW()),
(431252, 'Deutsche Post AG', 'DPSGY', 'Industrials', NOW()),
(431276, 'Dick''s Sporting Goods Inc.', 'DKS', 'ConsumerDiscretionary', NOW()),
(431314, 'Dolby Laboratories Inc', 'DLB', 'InformationTechnology', NOW()),
(431335, 'DOUBLELINE EMERGING MARKETS FIXED INCOME FUND', 'DBLEX', 'N/A', NOW()),
(431454, 'EMC Corp', 'EMC', 'InformationTechnology', NOW()),
(431500, 'Engie SA', 'ENGIY', 'Utilities', NOW()),
(431552, 'Erste Group Bank AG', 'EBKDY', 'Financials', NOW()),
(431556, 'Essent Group Ltd', 'ESNT', 'Financials', NOW()),
(431561, 'Essilorluxottica', 'ESLOY', 'Healthcare', NOW()),
(431595, 'Exelixis Inc', 'EXEL', 'Healthcare', NOW()),
(431628, 'Fast Retailing Co Ltd', 'FRCOY', 'ConsumerDiscretionary', NOW()),
(431636, 'Federal Realty Investment Trust', 'FRT', 'RealEstate', NOW()),
(431655, 'FIDELITY ADVISOR FOCUSED EMERGING MARKETS FUND', 'FIMKX', 'N/A', NOW()),
(431704, 'FIRST EAGLE GLOBAL FUND', 'SGENX', 'N/A', NOW()),
(431710, 'First Hawaiian Inc', 'FHB', 'Financials', NOW()),
(431792, 'Floor & Decor Holdings Inc', 'FND', 'ConsumerDiscretionary', NOW()),
(431812, 'F.N.B. Corp', 'FNB', 'Financials', NOW()),
(431932, 'GATX Corp', 'GATX', 'Industrials', NOW()),
(431934, 'GCI Liberty Inc', 'GLIBA', 'CommunicationServices', NOW()),
(431959, 'Gentex Corporation', 'GNTX', 'ConsumerDiscretionary', NOW()),
(432047, 'Golub Capital BDC Inc', 'GBDC', 'Financials', NOW()),
(432103, 'Grifols S.A.', 'GRFS', 'Healthcare', NOW()),
(432153, 'Hannon Armstrong Sustainable Infrastructure Capital Inc', 'HASI', 'Financials', NOW()),
(432188, 'Hawaiian Electric Industries Inc', 'HE', 'Utilities', NOW()),
(432224, 'Heidelbergcement AG', 'HDELY', 'Materials', NOW()),
(432230, 'Helmerich & Payne Inc', 'HP', 'Energy', NOW()),
(432246, 'Hermes International SA', 'HESAY', 'ConsumerDiscretionary', NOW()),
(432257, 'Hexcel Corp', 'HXL', 'Industrials', NOW()),
(432279, 'HNI Corp', 'HNI', 'Industrials', NOW()),
(432295, 'Honda Motor Co Ltd', 'HMC', 'ConsumerDiscretionary', NOW()),
(432322, 'Hoya Corp', 'HOCPY', 'Healthcare', NOW()),
(432342, 'Huntsman Corp', 'HUN', 'Materials', NOW()),
(432359, 'ICU Medical Inc', 'ICUI', 'Healthcare', NOW()),
(432395, 'Industria De Diseno Textil Inditex SA', 'IDEXY', 'ConsumerDiscretionary', NOW()),
(432436, 'Ingredion Inc', 'INGR', 'ConsumerStaples', NOW()),
(432548, 'iRobot Corp', 'IRBT', 'ConsumerDiscretionary', NOW()),
(432580, 'iShares Core S&P U.S. Growth ETF', 'FIUSG', 'N/A', NOW()),
(432583, 'iShares ESG Aware MSCI EAFE ETF', 'FESGD', 'N/A', NOW()),
(432611, 'iShares iBoxx High Yield Corporate Bond ETF', 'TFHYG', 'N/A', NOW()),
(432864, 'Kering', 'PPRUY', 'ConsumerDiscretionary', NOW()),
(432919, 'Koninklijke Philips NV', 'NVPHG', 'Healthcare', NOW()),
(432922, 'Kose Corp', 'KSRYY', 'ConsumerStaples', NOW()),
(432939, 'L''Air Liquide SA', 'AIQUY', 'Materials', NOW()),
(432970, 'Lazard Ltd', 'LAZ', 'Financials', NOW()),
(433009, 'LXP Industrial Trust', 'LXP', 'RealEstate', NOW()),
(433032, 'Life Storage Inc', 'LSI', 'RealEstate', NOW()),
(433041, 'Lincoln Electric Holdings Inc', 'LECO', 'Industrials', NOW()),
(433152, 'Mack-Cali Realty Corp', 'VRE', 'RealEstate', NOW()),
(433155, 'Macquarie Group Ltd', 'MQBKY', 'Financials', NOW()),
(433183, 'MAINE TURNPIKE AUTHORITY', 'None', 'N/A', NOW()),
(433342, 'METROPOLITAN NASHVILLE AIRPORT AUTHORITY', 'None', 'N/A', NOW()),
(433348, 'METROPOLITAN WATER RECLAMATION DISTRICT OF GREATER CHICAGO', 'None', 'N/A', NOW()),
(433264, 'Maxar Technologies Inc', 'XLK', 'Industrials', NOW()),
(433228, 'Marriott Vacations Worldwide Corp', 'VAC', 'ConsumerDiscretionary', NOW()),
(433243, 'Masimo Corp', 'MASI', 'Healthcare', NOW()),
(433399, 'Minerals Technologies Inc', 'XLK', 'Materials', NOW()),
(433408, 'MISSOURI HEALTH AND EDUCATIONAL FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(433412, 'MISSOURI PUBLIC UTILITIES COMMISSION', 'XLU', 'N/A', NOW()),
(433425, 'Mizuho Financial Group Inc', 'XLF', 'Financials', NOW()),
(433605, 'New Gold Inc', 'GLD', 'Materials', NOW()),
(433651, 'NextEra Energy Partners LP', 'XLE', 'Utilities', NOW()),
(433738, 'NRG Energy Inc', 'XLE', 'Utilities', NOW()),
(433801, 'OGE ENERGY CORP', 'XLE', 'Utilities', NOW()),
(433999, 'Peloton Interactive Inc', 'PTON', 'ConsumerDiscretionary', NOW()),
(434393, 'RHODE ISLAND HEALTH AND EDUCATIONAL BUILDING CORP', 'XLV', 'N/A', NOW()),
(434648, 'Semtech Corp', 'XLK', 'InformationTechnology', NOW()),
(434772, 'Solaris Oilfield Infrastructure Inc', 'USO', 'Energy', NOW()),
(434848, 'SPDR Gold Trust', 'GLD', 'N/A', NOW()),
(433362, 'MGIC Investment Corp', 'MTG', 'Financials', NOW()),
(433387, 'The Middleby Corp', 'MIDD', 'Industrials', NOW()),
(433419, 'Mitsubishi Estate Co Ltd', 'MITEY', 'RealEstate', NOW()),
(433449, 'Monotaro Co Ltd', 'MONOY', 'Industrials', NOW()),
(433491, 'MSA Safety Inc', 'MSA', 'Industrials', NOW()),
(433533, 'Naspers Ltd', 'NPSNY', 'ConsumerDiscretionary', NOW()),
(433536, 'National Australia Bank Ltd', 'NABZY', 'Financials', NOW()),
(433539, 'National Beverage Corp', 'FIZZ', 'ConsumerStaples', NOW()),
(433614, 'New Jersey Resources Corp', 'NJR', 'Utilities', NOW()),
(433655, 'Nidec Corp', 'NJDCY', 'Industrials', NOW()),
(433722, 'NorthWestern Corp', 'NWE', 'Utilities', NOW()),
(433729, 'Novanta Inc', 'NOVT', 'InformationTechnology', NOW()),
(433736, 'Novozymes A/S', 'NVZMY', 'Materials', NOW()),
(433748, 'Nutanix Inc', 'NTNX', 'InformationTechnology', NOW()),
(433843, 'ONE Gas Inc', 'OGS', 'Utilities', NOW())
ON CONFLICT (id) DO NOTHING;