INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(433092, 'LONG ISLAND POWER AUTHORITY', 'None', 'N/A', NOW()),
(433345, 'METROPOLITAN TRANSPORTATION AUTHORITY', 'None', 'N/A', NOW()),
(433360, 'MFS VALUE FUND', 'None', 'N/A', NOW()),
(433462, 'MONTGOMERY COUNTY TEXAS', 'None', 'N/A', NOW()),
(433504, 'MULTI-PACK SOLUTIONS LLC', 'None', 'N/A', NOW()),
(433814, 'OKLAHOMA TRANSPORTATION AUTHORITY', 'None', 'N/A', NOW()),
(433832, 'OMAHA PUBLIC POWER DISTRICT', 'None', 'N/A', NOW()),
(432148, 'Hancock (John) Financial Opportunities Fund', 'XLF', 'N/A', NOW()),
(432407, 'INDIANA STATE TOLL FINANCE AUTHORITY', 'DIA', 'N/A', NOW()),
(432582, 'iShares Dow Jones US ETF', 'DIA', 'N/A', NOW()),
(432654, 'iShares Russell Mid-Cap ETF', 'IWM', 'N/A', NOW()),
(432659, 'iShares Silver Trust', 'SLV', 'N/A', NOW()),
(432693, 'iShares U.S. Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(432773, 'John Bean Technologies Corp', 'XLK', 'Industrials', NOW()),
(432985, 'Leggett & Platt Inc', 'T', 'ConsumerDiscretionary', NOW()),
(433231, 'MARTIN COUNTY FLORIDA HEALTH FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(433238, 'MARYLAND HEALTH AND HIGHER EDUCATIONAL FACILITIES AUTHORITY', 'XLV', 'N/A', NOW()),
(433324, 'MERCK Kommanditgesellschaft auf Aktien', 'MRK', 'Healthcare', NOW()),
(433556, 'Nationwide Financial Services Inc', 'XLF', 'Financials', NOW()),
(433611, 'NEW JERSEY HEALTH CARE FACILITIES FINANCING AUTHORITY', 'XLV', 'N/A', NOW()),
(433647, 'Nexstar Media Group Inc', 'DIA', 'CommunicationServices', NOW()),
(433649, 'NextEra Energy Capital Holdings Inc', 'XLE', 'N/A', NOW()),
(433747, 'NuStar Energy LP', 'XLE', 'Energy', NOW()),
(433899, 'Outfront Media Inc', 'DIA', 'RealEstate', NOW()),
(432104, 'Grocery Outlet Inc', 'GO', 'ConsumerStaples', NOW()),
(432154, 'Hannover Rueck SE', 'HVRRY', 'Financials', NOW()),
(432155, 'The Hanover Insurance Group Inc', 'THG', 'Financials', NOW()),
(432219, 'Heartland Express Inc', 'HTLD', 'Industrials', NOW()),
(432222, 'Hecla Mining Co', 'HL', 'Materials', NOW()),
(432225, 'Heineken NV', 'HEINY', 'ConsumerStaples', NOW()),
(432235, 'Henkel AG & Co KGAA', 'HENOY', 'ConsumerStaples', NOW()),
(432300, 'Hope Bancorp Inc', 'HOPE', 'Financials', NOW()),
(432356, 'ICL GROUP LTD', 'TDICL', 'Materials', NOW()),
(432389, 'Imperial Brands PLC', 'IMBBY', 'ConsumerStaples', NOW()),
(432427, 'Informa PLC', 'IFJPY', 'CommunicationServices', NOW()),
(432498, 'INVESCO DEVELOPING MARKETS FUND', 'ODVYX', 'N/A', NOW()),
(432503, 'Invesco Fundamental High Yield Corporate Bond', 'PHB', 'N/A', NOW()),
(432574, 'iShares Core MSCI Europe ETF', 'FIEUR', 'N/A', NOW()),
(432581, 'iShares Core US Aggregate Bond ETF', 'TFAGG', 'N/A', NOW()),
(432608, 'iShares iBonds Dec 2024 Term Corporate ETF', 'FIBDP', 'N/A', NOW()),
(432624, 'iShares MSCI EAFE Small-Cap ETF', 'TFSCZ', 'N/A', NOW()),
(432625, 'iShares MSCI EAFE Value ETF', 'TFEFV', 'N/A', NOW()),
(432638, 'iShares MSCI USA Min Vol Factor ETF', 'FUSMV', 'N/A', NOW()),
(432677, 'iShares Trust iBonds Dec 2029 Term Corporate Etf', 'IBDU', 'N/A', NOW()),
(432689, 'iShares U.S. Pharmaceuticals ETF', 'TFIHE', 'N/A', NOW()),
(432700, 'Isuzu Motors Ltd', 'ISUZY', 'ConsumerDiscretionary', NOW()),
(432741, 'Japan Airlines Co Ltd', 'JAPSY', 'Industrials', NOW()),
(432756, 'Jeronimo Martins Sgps SA, Lisboa', 'JRONY', 'ConsumerStaples', NOW()),
(432837, 'KBC Group SA', 'KBCSY', 'Financials', NOW()),
(432887, 'Kingfisher PLC', 'KGFHY', 'ConsumerDiscretionary', NOW()),
(432892, 'Kirby Corp', 'KEX', 'Industrials', NOW()),
(432907, 'Knorr-Bremse Aktiengesellschaft', 'KNRRY', 'Industrials', NOW()),
(432913, 'Kohl''s Corp', 'KSS', 'ConsumerDiscretionary', NOW()),
(432914, 'Komatsu Ltd', 'KMTUY', 'Industrials', NOW()),
(432917, 'Koninklijke DSM NV', 'RDSMY', 'Materials', NOW()),
(432918, 'Koninklijke Kpn NV', 'KKPNY', 'CommunicationServices', NOW()),
(432938, 'Holcim Ltd', 'HCMLY', 'Materials', NOW()),
(432968, 'Lazard Global Total Return & Income Fund Inc', 'LGI', 'N/A', NOW()),
(432969, 'LAZARD INTERNATIONAL EQUITY PORTFOLIO', 'LZIEX', 'N/A', NOW()),
(432990, 'LendingClub Corp', 'LC', 'Financials', NOW()),
(432997, 'Leslie''s Inc', 'LESL', 'ConsumerDiscretionary', NOW()),
(433026, 'Liberty TripAdvisor Holdings Inc', 'LTRPA', 'CommunicationServices', NOW()),
(433037, 'Limestone Bancorp Inc', 'LMST', 'Financials', NOW()),
(433072, 'LIXIL Corporation', 'JSGRY', 'Industrials', NOW()),
(433157, 'Macy''s Inc', 'M', 'ConsumerDiscretionary', NOW()),
(433192, 'Makita Corp', 'MKTAY', 'Industrials', NOW()),
(433255, 'Matador Resources Co', 'MTDR', 'Energy', NOW()),
(433303, 'Mediobanca - Banca Di Credito Finanziario SPA, Milano', 'MDIBY', 'Financials', NOW()),
(433329, 'Merit Medical Systems Inc', 'MMSI', 'Healthcare', NOW()),
(433418, 'Mitsubishi Electric Corp', 'MIELY', 'Industrials', NOW()),
(433577, 'Neogenomics Inc', 'NEO', 'Healthcare', NOW()),
(433602, 'Newcrest Mining Ltd', 'NCMGY', 'Materials', NOW()),
(433660, 'Nikon Corp', 'NINOY', 'ConsumerDiscretionary', NOW()),
(433669, 'Nissan Motor Co Ltd', 'NSANY', 'ConsumerDiscretionary', NOW()),
(433671, 'Nitto Denko Corp', 'NDEKY', 'Materials', NOW()),
(433676, 'NN Group N.V.', 'NNGRY', 'Financials', NOW()),
(433683, 'Nomura Holdings Inc', 'NMR', 'Financials', NOW()),
(433780, 'OAKMARK INTERNATIONAL FUND', 'OAKIX', 'N/A', NOW()),
(433822, 'Old Republic International Corp', 'ORI', 'Financials', NOW()),
(433826, 'OLD WESTBURY MUNICIPAL BOND FUND', 'OWMBX', 'N/A', NOW()),
(434006, 'PENNSYLVANIA ECONOMIC DEVELOPMENT FINANCING AUTHORITY', 'None', 'N/A', NOW()),
(434053, 'PHILADELPHIA PARKING AUTHORITY', 'None', 'N/A', NOW()),
(434106, 'PLANO INDEPENDENT SCHOOL DISTRICT COLLIN COUNTY TEXAS', 'None', 'N/A', NOW()),
(434184, 'PRIVATE COLLEGES AND UNIVERSITIES AUTHORITY', 'None', 'N/A', NOW()),
(434351, 'REGIONAL TRANSPORTATION AUTHORITY', 'None', 'N/A', NOW()),
(434352, 'REGIONAL TRANSPORTATION DISTRICT', 'None', 'N/A', NOW()),
(434367, 'REOF XX LLC', 'None', 'N/A', NOW()),
(434399, 'RICHARDSON INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(434503, 'SACRAMENTO MUNICIPAL UTILITY DISTRICT', 'None', 'N/A', NOW()),
(434504, 'SACRAMENTO SUBURBAN WATER DISTRICT', 'None', 'N/A', NOW()),
(434528, 'SAN DIEGO COMMUNITY COLLEGE DISTRICT', 'None', 'N/A', NOW()),
(434529, 'SAN DIEGO COUNTY WATER AUTHORITY', 'None', 'N/A', NOW()),
(434550, 'SANTANDER UK GROUP HOLDINGS PLC', 'None', 'N/A', NOW()),
(434584, 'SCHOOL DISTRICT OF HATBORO HORSHAM PENNSYLVANIA', 'None', 'N/A', NOW()),
(434590, 'SCHOOL DISTRICT OF VOLUSIA COUNTY FLORIDA', 'None', 'N/A', NOW()),
(434650, 'SENECA VALLEY SCHOOL DISTRICT BUTLER COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(434951, 'STATE OF CALIFORNIA DEPARTMENT OF WATER RESOURCES', 'None', 'N/A', NOW()),
(434953, 'STATE OF COLORADO DEPARTMENT OF HIGHER EDUCATION', 'None', 'N/A', NOW()),
(434955, 'STATE OF FLORIDA', 'None', 'N/A', NOW()),
(434957, 'STATE OF FLORIDA DEPARTMENT OF MANAGEMENT SERVICES', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;