INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(429794, 'AptarGroup Inc', 'ATR', 'Materials', NOW()),
(429903, 'Atlas Copco AB', 'ATLKY', 'Industrials', NOW()),
(430235, 'British American Tobacco PLC', 'LCBTI', 'ConsumerStaples', NOW()),
(430267, 'Brp Group Inc', 'BWIN', 'Financials', NOW()),
(430541, 'C.H. Robinson Worldwide Inc', 'CHRW', 'Industrials', NOW()),
(430544, 'Chugai Pharmaceutical Co Ltd', 'CHGCY', 'Healthcare', NOW()),
(431472, 'Enbridge Inc', 'ENB', 'Energy', NOW()),
(431542, 'Equinor ASA', 'AEQNR', 'Energy', NOW()),
(431596, 'Exelon Corp', 'EXC', 'Utilities', NOW()),
(431659, 'FIDELITY ADVISOR TOTAL BOND FUND', 'FBKWX', 'N/A', NOW()),
(431846, 'Fox Factory Holding Corp', 'FOXF', 'ConsumerDiscretionary', NOW()),
(432131, 'Guidewire Software Inc', 'GWRE', 'InformationTechnology', NOW()),
(432223, 'HEICO Corp', 'HEI', 'Industrials', NOW()),
(432348, 'Iberdrola SA, Bilbao', 'IBDRY', 'Utilities', NOW()),
(432373, 'Coherent Corp', 'COHR', 'InformationTechnology', NOW()),
(432567, 'iShares CMBS ETF', 'FCMBS', 'N/A', NOW()),
(433171, 'Magellan Midstream Partners LP', 'LPMMP', 'Energy', NOW()),
(433563, 'NatWest Group PLC', 'LCNWG', 'Financials', NOW()),
(433587, 'Netease Inc', 'NTES', 'CommunicationServices', NOW()),
(433806, 'OHIO TURNPIKE COMMISSION', 'None', 'N/A', NOW()),
(434011, 'PENNSYLVANIA STATE UNIVERSITY', 'None', 'N/A', NOW()),
(434394, 'RHODE ISLAND HOUSING AND MORTGAGE FINANCE CORP', 'None', 'N/A', NOW()),
(2333577, 'CITY OF PITTSBURGH PENNSYLVANIA', 'None', 'N/A', NOW()),
(2333920, 'ALLOCATE PREMIER ACCESS FUND LP', 'None', 'N/A', NOW()),
(2334236, 'BDT CAPITAL PARTNERS FUND 3 LP', 'None', 'N/A', NOW()),
(2334352, 'BRAEMONT PARTNERS I LP', 'None', 'N/A', NOW()),
(2334603, 'ALBANY ROAD STRATEGIC OPPORTUNITY FUND LLC', 'None', 'N/A', NOW()),
(2334699, 'US SAVINGS BOND', 'None', 'N/A', NOW()),
(2334770, 'AERODROME FINANCE', 'None', 'N/A', NOW()),
(429830, 'ARIZONA STATE TRANSPORTATION BOARD', 'None', 'N/A', NOW()),
(430166, 'BOFA FINANCE LLC', 'None', 'N/A', NOW()),
(430728, 'CITY OF PHILADELPHIA PENNSYLVANIA', 'None', 'N/A', NOW()),
(431026, 'COUNTY OF FRANKLIN OHIO', 'None', 'N/A', NOW()),
(431063, 'COUNTY OF PALM BEACH', 'None', 'N/A', NOW()),
(431450, 'EL PRADO STONE LP', 'None', 'N/A', NOW()),
(431796, 'FLORIDA DEVELOPMENT FINANCE CORP', 'None', 'N/A', NOW()),
(432145, 'HAMILTON COUNTY OHIO', 'None', 'N/A', NOW()),
(432377, 'ILLINOIS FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(433251, 'MASSACHUSETTS HOUSING FINANCE AGENCY', 'None', 'N/A', NOW()),
(433376, 'MICHIGAN STATE HOUSING DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(433640, 'NEW YORK STATE HOUSING FINANCE AGENCY', 'None', 'N/A', NOW()),
(433701, 'NORTH EAST INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433703, 'NORTHEAST OHIO REGIONAL SEWER DISTRICT', 'None', 'N/A', NOW()),
(433720, 'NORTH TEXAS TOLLWAY AUTHORITY', 'None', 'N/A', NOW()),
(434522, 'SALT RIVER PROJECT AGRICULTURAL IMPROVEMENT AND POWER DISTRICT', 'None', 'N/A', NOW()),
(434794, 'SOUTH CAROLINA STATE PORTS AUTHORITY', 'None', 'N/A', NOW()),
(2331375, 'SEATTLE CITY LIGHT', 'T', 'N/A', NOW()),
(2334216, 'SPDR GOLD MINISHARES TR', 'GLD', 'N/A', NOW()),
(2334634, 'ELLINGTON FINANCIAL INC', 'XLF', 'Financials', NOW()),
(430358, 'Canadian Pacific Railway Ltd', 'DIA', 'Industrials', NOW()),
(432646, 'iShares Russell 1000 ETF', 'IWM', 'N/A', NOW()),
(433174, 'Magnolia Oil & Gas Corp', 'USO', 'Energy', NOW()),
(434852, 'SPDR Portfolio S&P 500 Growth ETF', 'SPY', 'N/A', NOW()),
(433668, 'NiSource Inc', 'NI', 'Utilities', NOW()),
(434439, 'ROLLINS Inc', 'ROL', 'Industrials', NOW()),
(434558, 'Sarepta Therapeutics Inc', 'SRPT', 'Healthcare', NOW()),
(434618, 'Sea Ltd', 'SE', 'ConsumerDiscretionary', NOW()),
(434683, 'Shionogi & Co Ltd', 'SGIOY', 'Healthcare', NOW()),
(434686, 'Shiseido Co Ltd', 'SSDOY', 'ConsumerStaples', NOW()),
(435135, 'Targa Resources Corp', 'TRGP', 'Energy', NOW()),
(435180, 'PT Telekomunikasi Indonesia (Persero) TBK', 'BKTLK', 'CommunicationServices', NOW()),
(435294, 'The Toro Co', 'TTC', 'Industrials', NOW()),
(435300, 'TotalEnergies SE', 'SETTE', 'Energy', NOW()),
(435350, 'TransUnion', 'TRU', 'Industrials', NOW()),
(435521, 'Unum Group', 'UNM', 'Financials', NOW()),
(435893, 'Whirlpool Corp', 'WHR', 'ConsumerDiscretionary', NOW()),
(436029, 'Zscaler Inc', 'ZS', 'InformationTechnology', NOW()),
(438628, 'Globe Life Inc', 'GL', 'Financials', NOW()),
(2296311, 'Stride Inc', 'LRN', 'ConsumerDiscretionary', NOW()),
(2331101, 'Organon & Co', 'OGN', 'Healthcare', NOW()),
(2333439, 'Lucid Group Inc', 'LCID', 'ConsumerDiscretionary', NOW()),
(2333618, 'Kyndryl Holdings Inc', 'KD', 'InformationTechnology', NOW()),
(2333644, 'Bill.com Holdings Inc', 'BILL', 'InformationTechnology', NOW()),
(2334179, 'INSMED INC', 'CINSM', 'Healthcare', NOW()),
(2334215, 'PACER US SM CP CSH COWS ETF', 'FCALF', 'N/A', NOW()),
(2334250, 'AB INTERNATIONAL STRATEGIC EQUITIES PORTFOLIO', 'STEYX', 'N/A', NOW()),
(429536, 'AIA Group Ltd', 'AAGIY', 'Financials', NOW()),
(429596, 'Allegion PLC', 'CALLE', 'Industrials', NOW()),
(429656, 'Amedisys Inc', 'AMED', 'Healthcare', NOW()),
(429719, 'Ameris Bancorp', 'ABCB', 'Financials', NOW()),
(429874, 'Assa Abloy AB', 'ASAZY', 'Industrials', NOW()),
(429971, 'Baker Hughes a GE Co', 'BKR', 'Energy', NOW()),
(429998, 'Barclays PLC', 'LCBCS', 'Financials', NOW()),
(430269, 'Brunswick Corp', 'BC', 'ConsumerDiscretionary', NOW()),
(430504, 'Chemed Corp', 'CHE', 'Healthcare', NOW()),
(430939, 'Compass Group PLC', 'CMPGY', 'ConsumerDiscretionary', NOW()),
(431187, 'Dassault Systemes SA', 'DASTY', 'InformationTechnology', NOW()),
(431302, 'DISH Network Corp', 'DISH', 'CommunicationServices', NOW()),
(431394, 'East West Bancorp Inc', 'EWBC', 'Financials', NOW()),
(431425, 'Elastic N.V.', 'ESTC', 'InformationTechnology', NOW()),
(431438, 'e.l.f. Beauty Inc', 'ELF', 'ConsumerStaples', NOW()),
(432347, 'IAC/InterActiveCorp', 'IAC', 'CommunicationServices', NOW()),
(432355, 'Icici Bank Ltd', 'IBN', 'Financials', NOW()),
(432468, 'Interactive Brokers Group Inc', 'IBKR', 'Financials', NOW()),
(432487, 'Intra-Cellular Therapies Inc', 'ITCI', 'Healthcare', NOW()),
(432513, 'Invesco Optimum Yield Diversified Commodity Strategy No K-1 ETF', 'FPDBC', 'N/A', NOW()),
(432563, 'iShares Agency Bond ETF', 'TFAGZ', 'N/A', NOW()),
(432745, 'Jazz Pharmaceuticals PLC', 'CJAZZ', 'Healthcare', NOW()),
(432850, 'Kennedy-Wilson Holdings Inc', 'KW', 'RealEstate', NOW()),
(432973, 'LCI Industries', 'LCII', 'ConsumerDiscretionary', NOW())
ON CONFLICT (id) DO NOTHING;