INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(431599, 'Expeditors International of Washington Inc', 'EXPD', 'Industrials', NOW()),
(431615, 'Fair Isaac Corporation', 'FICO', 'InformationTechnology', NOW()),
(432149, 'Hanesbrands Inc', 'HBI', 'ConsumerDiscretionary', NOW()),
(433056, 'Lions Gate Entertainment Corp', 'A', 'CommunicationServices', NOW()),
(433089, 'London Stock Exchange Group PLC', 'LDNXF', 'Financials', NOW()),
(433220, 'MarketAxess Holdings Inc', 'MKTX', 'Financials', NOW()),
(433307, 'Medpace Holdings Inc', 'MEDP', 'Healthcare', NOW()),
(433723, 'Northwest Natural Holding Co', 'NWN', 'Utilities', NOW()),
(433845, 'OneMain Holdings Inc', 'OMF', 'Financials', NOW()),
(434376, 'Restaurant Brands International Inc', 'QSR', 'ConsumerDiscretionary', NOW()),
(434656, 'Service Corp International', 'SCI', 'ConsumerDiscretionary', NOW()),
(434693, 'Siemens AG', 'SIEGY', 'Industrials', NOW()),
(435331, 'Toyota Motor Corp', 'TM', 'ConsumerDiscretionary', NOW()),
(435374, 'TriMas Corp', 'TRS', 'Materials', NOW()),
(435375, 'Trimble Inc', 'TRMB', 'InformationTechnology', NOW()),
(2331870, 'Axon Enterprise Inc', 'AXON', 'Industrials', NOW()),
(2333544, 'Haier Smart Home Co Ltd', 'HSHCY', 'ConsumerDiscretionary', NOW()),
(2333614, 'Equity LifeStyle Properties Inc', 'ELS', 'RealEstate', NOW()),
(2333905, 'FULL HOUSE RESORTS INC', 'NCFLL', 'ConsumerDiscretionary', NOW()),
(2334145, 'FRANKLIN FTSE JAPAN ETF', 'FFLJP', 'N/A', NOW()),
(2334836, 'INVESCO SHORT TERM TREAS ETF', 'FTBLL', 'N/A', NOW()),
(429711, 'American Water Works Company Inc', 'AWK', 'Utilities', NOW()),
(430397, 'The Carlyle Group Inc', 'CG', 'Financials', NOW()),
(431114, 'CRH PLC', 'LCCRH', 'Materials', NOW()),
(431342, 'Douglas Emmett Inc', 'DEI', 'RealEstate', NOW()),
(431512, 'Entergy corporation', 'ETR', 'Utilities', NOW()),
(431524, 'EOG Resources Inc', 'EOG', 'Energy', NOW()),
(432380, 'ILLINOIS STATE TOLL HIGHWAY AUTHORITY', 'None', 'N/A', NOW()),
(433615, 'NEW JERSEY STATE TURNPIKE AUTHORITY', 'None', 'N/A', NOW()),
(433639, 'NEW YORK STATE ENVIRONMENTAL FACILITIES CORP', 'None', 'N/A', NOW()),
(434137, 'PORTLAND WATER DISTRICT', 'None', 'N/A', NOW()),
(434588, 'SCHOOL DISTRICT OF PHILADELPHIA', 'None', 'N/A', NOW()),
(434792, 'SOUTH CAROLINA JOBS ECONOMIC DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(434965, 'STATE OF LOUISIANA', 'None', 'N/A', NOW()),
(435774, 'WALLEYE CAPITAL PARTNERS LP', 'None', 'N/A', NOW()),
(435800, 'WASHINGTON SUBURBAN SANITARY DISTRICT', 'None', 'N/A', NOW()),
(1996993, 'SAN ANTONIO TEXAS ELECTRICITY & GAS', 'None', 'N/A', NOW()),
(2331176, 'COMMODORE CAPITAL DOMESTIC LP', 'None', 'N/A', NOW()),
(2333898, 'ELT ASSOCIATES LLC', 'None', 'N/A', NOW()),
(2334199, 'SPRING INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334430, 'BDT CAPITAL PARTNERS FUND 4 LP', 'None', 'N/A', NOW()),
(2334625, 'RECURRING CAPITAL FUND IV LP', 'None', 'N/A', NOW()),
(2334640, 'MYNO CARBON CORP', 'None', 'N/A', NOW()),
(2334824, 'LINCOLN GAINE LLC', 'None', 'N/A', NOW()),
(2334866, 'BROKEDOWN PALACE LTD', 'None', 'N/A', NOW()),
(430620, 'CITY OF CINCINNATI', 'None', 'N/A', NOW()),
(430676, 'CITY OF JACKSONVILLE FLORIDA', 'None', 'N/A', NOW()),
(431013, 'COUNTY OF BROWARD FLORIDA AIRPORT SYSTEM REVENUE', 'None', 'N/A', NOW()),
(432169, 'HARRIS COUNTY CULTURAL EDUCATION FACILITIES FINANCE CORP', 'None', 'N/A', NOW()),
(432417, 'INDUSTRIAL DEVELOPMENT AUTHORITY OF WISE COUNTY', 'None', 'N/A', NOW()),
(433214, 'MARICOPA COUNTY ARIZONA', 'None', 'N/A', NOW()),
(433249, 'MASSACHUSETTS DEVELOPMENT FINANCE AGENCY', 'None', 'N/A', NOW()),
(433630, 'NEW YORK CITY HOUSING DEVELOPMENT CORP', 'None', 'N/A', NOW()),
(433642, 'NEW YORK STATE URBAN DEVELOPMENT CORP', 'None', 'N/A', NOW()),
(432421, 'Infineon Technologies AG', 'XLK', 'InformationTechnology', NOW()),
(432562, 'iShares 7-10 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(432647, 'iShares Russell 1000 Growth ETF', 'IWM', 'N/A', NOW()),
(432964, 'Lattice Semiconductor Corporation', 'T', 'InformationTechnology', NOW()),
(433787, 'Chord Energy Corp', 'XLE', 'Energy', NOW()),
(434461, 'Royal Gold Inc', 'GLD', 'Materials', NOW()),
(435109, 'Synovus Financial Corp', 'XLF', 'Financials', NOW()),
(435421, 'Twilio Inc', 'TWLO', 'InformationTechnology', NOW()),
(435757, 'Voya Financial Inc', 'XLF', 'Financials', NOW()),
(435825, 'WEC Energy Group Inc', 'XLE', 'Utilities', NOW()),
(2332351, 'BioNTech SE', 'XLK', 'Healthcare', NOW()),
(2334346, 'NEXTERA ENERGY CAPITAL HOLDINGS INC', 'XLE', 'N/A', NOW()),
(2334877, 'OUNZ VAN ECK GOLD TRUST ETF', 'GLD', 'N/A', NOW()),
(429908, 'Atmos Energy Corp', 'XLE', 'Utilities', NOW()),
(430759, 'CITY OF SEATTLE', 'T', 'N/A', NOW()),
(430838, 'CMS Energy Corp', 'XLE', 'Utilities', NOW()),
(431363, 'DTE Energy Co', 'XLE', 'Utilities', NOW()),
(431947, 'General Motors Financial Co Inc', 'XLF', 'Financials', NOW()),
(432438, 'Inland Real Estate Income Trust Inc', 'VNQ', 'RealEstate', NOW()),
(432661, 'iShares S&P 500 Growth ETF', 'SPY', 'N/A', NOW()),
(431620, 'Fanuc Corp', 'FANUY', 'Industrials', NOW()),
(432012, 'Globus Medical Inc', 'GMED', 'Healthcare', NOW()),
(432329, 'HubSpot Inc', 'HUBS', 'InformationTechnology', NOW()),
(432620, 'iShares MSCI EAFE ETF', 'TFEFA', 'N/A', NOW()),
(432972, 'Bath & Body Works Inc', 'BBWI', 'ConsumerDiscretionary', NOW()),
(433298, 'Medical Properties Trust Inc', 'MPW', 'RealEstate', NOW()),
(433663, 'Nintendo Co Ltd', 'NTDOY', 'CommunicationServices', NOW()),
(433682, 'Nokia Corp', 'NOK', 'InformationTechnology', NOW()),
(433837, 'Omnicom Group Inc', 'OMC', 'CommunicationServices', NOW()),
(434112, 'Plug Power Inc', 'PLUG', 'Industrials', NOW()),
(434570, 'Schneider Electric SA', 'SBGSY', 'Industrials', NOW()),
(434599, 'Schwab US TIPS ETF', 'FSCHP', 'N/A', NOW()),
(434854, 'SPDR Portfolio Developed World ex-US ETF', 'FSPDW', 'N/A', NOW()),
(434858, 'SPDR S&P 400 Mid Cap Growth ETF', 'FMDYG', 'N/A', NOW()),
(434862, 'SPDR S&P 600 Small Cap Growth ETF', 'FSLYG', 'N/A', NOW()),
(435113, 'Sysmex Corp', 'SSMXY', 'Healthcare', NOW()),
(2294106, 'Kilroy Realty Corp', 'KRC', 'RealEstate', NOW()),
(2331057, 'Ares Management Corp', 'ARES', 'Financials', NOW()),
(2334078, 'ChargePoint Holdings Inc', 'CHPT', 'Industrials', NOW()),
(2334203, 'ATKORE INC', 'CATKR', 'Industrials', NOW()),
(2334389, 'CROSS TIMBERS ROYALTY TRUST', 'STCRT', 'Energy', NOW()),
(2334710, 'SOLVENTUM CORP', 'PSOLV', 'Healthcare', NOW()),
(429533, 'Agree Realty Corp', 'ADC', 'RealEstate', NOW()),
(429597, 'Allegro Microsystems Inc', 'ALGM', 'InformationTechnology', NOW()),
(429613, 'Allianz SE', 'ALIZY', 'Financials', NOW()),
(429651, 'Ambev SA', 'AABEV', 'ConsumerStaples', NOW())
ON CONFLICT (id) DO NOTHING;