INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(432394, 'Incyte Corp', 'INCY', 'Healthcare', NOW()),
(433350, 'Mettler-Toledo International Inc', 'MTD', 'Healthcare', NOW()),
(433427, 'MKS Instruments Inc', 'MKSI', 'InformationTechnology', NOW()),
(433769, 'nVent Electric PLC', 'LCNVT', 'Industrials', NOW()),
(433772, 'NVR Inc', 'NVR', 'ConsumerDiscretionary', NOW()),
(435061, 'Sun Communities Inc', 'SUI', 'RealEstate', NOW()),
(435457, 'Unilever PLC', 'PLCUL', 'ConsumerStaples', NOW()),
(435953, 'Woodward Inc', 'WWD', 'Industrials', NOW()),
(2332090, 'Kellogg Co', 'K', 'ConsumerStaples', NOW()),
(2334768, 'APPLOVIN CORP', 'RPAPP', 'InformationTechnology', NOW()),
(429577, 'Alcoa Corp', 'AA', 'Materials', NOW()),
(429608, 'Alliance Resource Partners LP', 'PARLP', 'Energy', NOW()),
(429848, 'Arthur J. Gallagher & Co', 'AJG', 'Financials', NOW()),
(430439, 'CDW Corp', 'CDW', 'InformationTechnology', NOW()),
(431698, 'FirstCash Holdings Inc', 'FCFS', 'Financials', NOW()),
(432254, 'Hewlett Packard Enterprise Co', 'HPE', 'InformationTechnology', NOW()),
(432879, 'Kinder Morgan Inc', 'KMI', 'Energy', NOW()),
(434343, 'Regal Rexnord Corporation', 'RRX', 'Industrials', NOW()),
(434817, 'Southwest Airlines Co', 'LUV', 'Industrials', NOW()),
(1608657, 'CBRE Group Inc', 'CBRE', 'RealEstate', NOW()),
(2290378, 'Welltower Inc', 'WELL', 'RealEstate', NOW()),
(2334905, 'YIELDMAX SMCI OPTION INCOME STRATEGY ETF', 'SMCY', 'N/A', NOW()),
(429501, 'Advance Auto Parts Inc', 'AAP', 'ConsumerDiscretionary', NOW()),
(429811, 'Arch Capital Group Ltd', 'ACGL', 'Financials', NOW()),
(430056, 'Berkley (W.R.) Corp', 'WRB', 'Financials', NOW()),
(431721, 'First Republic Bank', 'FRC', 'Financials', NOW()),
(431958, 'Genpact Ltd', 'G', 'Industrials', NOW()),
(433043, 'Lincoln National Corp', 'LNC', 'Financials', NOW()),
(434542, 'Sanofi', 'SNY', 'Healthcare', NOW()),
(434726, 'Skechers U S A Inc', 'SKX', 'ConsumerDiscretionary', NOW()),
(435438, 'UDR Inc', 'UDR', 'RealEstate', NOW()),
(1570797, 'HSBC Holdings PLC', 'CHSBC', 'Financials', NOW()),
(429906, 'Atlassian Corp PLC', 'CTEAM', 'InformationTechnology', NOW()),
(430199, 'BP PLC', 'PLCBP', 'Energy', NOW()),
(430308, 'Caesars Entertainment Inc', 'CZR', 'ConsumerDiscretionary', NOW()),
(430978, 'The Cooper Cos Inc', 'COO', 'Healthcare', NOW()),
(431330, 'DoorDash Inc', 'DASH', 'ConsumerDiscretionary', NOW()),
(431611, 'FactSet Research Systems Inc', 'FDS', 'Financials', NOW()),
(431863, 'Franklin Resources Inc', 'BEN', 'Financials', NOW()),
(431940, 'Generac Holdings Inc', 'GNRC', 'Industrials', NOW()),
(432141, 'Halliburton Co', 'HAL', 'Energy', NOW()),
(432185, 'Hasbro Inc', 'HAS', 'ConsumerDiscretionary', NOW()),
(432314, 'Houlihan Lokey Inc', 'HLI', 'Financials', NOW()),
(432707, 'ITT Inc', 'ITT', 'Industrials', NOW()),
(432876, 'Kimco Realty Corp', 'KIM', 'RealEstate', NOW()),
(434426, 'Roche Holding AG', 'RHHBY', 'Healthcare', NOW()),
(434930, 'Stanley Black & Decker Inc', 'SWK', 'Industrials', NOW()),
(435670, 'Verisign Inc', 'VRSN', 'InformationTechnology', NOW()),
(435909, 'The Williams Cos Inc', 'WMB', 'Energy', NOW()),
(2334032, 'FLEX LNG LTD', 'DFLNG', 'Energy', NOW()),
(429941, 'Avery Dennison Corp', 'AVY', 'Materials', NOW()),
(430279, 'Builders FirstSource Inc', 'BLDR', 'Industrials', NOW()),
(431146, 'Cummins Inc', 'CMI', 'Industrials', NOW()),
(431207, 'Deckers Outdoor Corp', 'DECK', 'ConsumerDiscretionary', NOW()),
(431831, 'FORT BEND INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(434012, 'PENNSYLVANIA TURNPIKE COMMISSION', 'None', 'N/A', NOW()),
(434950, 'STATE OF CALIFORNIA', 'None', 'N/A', NOW()),
(2333857, 'CME SOYBEAN', 'None', 'N/A', NOW()),
(2334337, 'CAPPED BUFFERED ENHANCED PARTICIPATION', 'None', 'N/A', NOW()),
(429997, 'Barclays Bank PLC', 'None', 'Financials', NOW()),
(433346, 'METROPOLITAN WASHINGTON AIRPORTS AUTHORITY', 'None', 'N/A', NOW()),
(433811, 'OKLAHOMA DEVELOPMENT FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(434967, 'STATE OF MARYLAND', 'None', 'N/A', NOW()),
(2331163, '3G COURSER ONSHORE FUND LP', 'None', 'N/A', NOW()),
(2334007, 'CME SOYBEAN MEAL', 'None', 'N/A', NOW()),
(2334087, 'SEVEN BRIDGES MULTI STRATEGY FUND LP', 'None', 'N/A', NOW()),
(433003, 'LEWIS & CLARK AGRIFOOD FUND II LP', 'None', 'N/A', NOW()),
(2334794, 'MAYS (J.W.) INC', 'None', 'RealEstate', NOW()),
(431085, 'COUNTY OF WILL ILLINOIS', 'None', 'N/A', NOW()),
(431241, 'DEPARTMENT OF TRANSPORTATION OF MARYLAND', 'None', 'N/A', NOW()),
(433122, 'LPL Financial Holdings Inc', 'XLF', 'Financials', NOW()),
(434901, 'Spotify Technology S.A', 'SPOT', 'CommunicationServices', NOW()),
(435099, 'Synchrony Financial', 'XLF', 'Financials', NOW()),
(435984, 'Xcel Energy Inc', 'XLE', 'Utilities', NOW()),
(429791, 'Applied Industrial Technologies Inc', 'XLK', 'Industrials', NOW()),
(429555, 'AKAMAI TECHNOLOGIES Inc', 'XLK', 'InformationTechnology', NOW()),
(430003, 'Barrick Gold Corp', 'GLD', 'Materials', NOW()),
(430240, 'Broadridge Financial Solutions Inc', 'XLF', 'Industrials', NOW()),
(430560, 'Cincinnati Financial Corp', 'XLF', 'Financials', NOW()),
(432555, 'iShares 1-3 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(434177, 'Principal Financial Group Inc', 'XLF', 'Financials', NOW()),
(434314, 'Raymond James Financial Inc', 'XLF', 'Financials', NOW()),
(434615, 'Seagate Technology Holdings PLC', 'XLK', 'InformationTechnology', NOW()),
(435428, 'Tyler Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(1571408, 'L3Harris Technologies Inc', 'XLK', 'Industrials', NOW()),
(431598, 'Expedia Group Inc', 'DIA', 'ConsumerDiscretionary', NOW()),
(434139, 'PORT OF SEATTLE WASHINGTON', 'T', 'N/A', NOW()),
(434209, 'ProShares Short QQQ', 'QQQ', 'N/A', NOW()),
(432327, 'Hubbell Inc', 'HUBB', 'Industrials', NOW()),
(432434, 'ING Groep NV', 'NVING', 'Financials', NOW()),
(432457, 'Insulet Corp', 'PODD', 'Healthcare', NOW()),
(432906, 'Knight-Swift Transportation Holdings Inc', 'KNX', 'Industrials', NOW()),
(433478, 'The Mosaic Company', 'MOS', 'Materials', NOW()),
(433730, 'Novartis AG', 'AGNVS', 'Healthcare', NOW()),
(433846, 'ONEOK Inc', 'OKE', 'Energy', NOW()),
(435585, 'Vanguard Dividend Appreciation ETF', 'TFVIG', 'N/A', NOW()),
(2334583, 'VERALTO CORP', 'PVLTO', 'Industrials', NOW()),
(430062, 'Best Buy Co Inc', 'BBY', 'ConsumerDiscretionary', NOW()),
(431544, 'Equitable Holdings Inc', 'EQH', 'Financials', NOW()),
(432243, 'Hercules Capital Inc', 'HTGC', 'Financials', NOW()),
(432422, 'Infinera Corp', 'INFN', 'InformationTechnology', NOW()),
(432475, 'The Interpublic Group of Cos Inc', 'IPG', 'CommunicationServices', NOW()),
(433364, 'MGM Resorts International', 'MGM', 'ConsumerDiscretionary', NOW()),
(433594, 'Neurocrine Biosciences Inc', 'NBIX', 'Healthcare', NOW()),
(433724, 'NortonLifeLock Inc', 'GEN', 'InformationTechnology', NOW()),
(433744, 'Nucor Corp', 'NUE', 'Materials', NOW()),
(434647, 'Sempra', 'SRE', 'Utilities', NOW()),
(434737, 'Skyworks Solutions Inc', 'SWKS', 'InformationTechnology', NOW()),
(434763, 'Societe Generale Group', 'SCGLY', 'Financials', NOW()),
(434785, 'Sony Group Corporation', 'SONY', 'ConsumerDiscretionary', NOW()),
(435567, 'Valvoline Inc', 'VVV', 'ConsumerDiscretionary', NOW()),
(435682, 'Vertiv Holdings Co', 'VRT', 'Industrials', NOW()),
(435994, 'Xylem Inc', 'XYL', 'Industrials', NOW()),
(2334588, 'CORE & MAIN INC', 'NCCNM', 'Industrials', NOW()),
(430290, 'Burlington Stores Inc', 'BURL', 'ConsumerDiscretionary', NOW()),
(431625, 'Farmers & Merchants Bancorp Inc', 'FMAO', 'Financials', NOW()),
(431926, 'Garmin Ltd', 'GRMN', 'ConsumerDiscretionary', NOW()),
(433139, 'LVMH Moet Hennessy Louis Vuitton SE', 'LVMHF', 'ConsumerDiscretionary', NOW()),
(433919, 'Packaging Corp Of America', 'PKG', 'Materials', NOW()),
(434255, 'PulteGroup Inc', 'PHM', 'ConsumerDiscretionary', NOW()),
(434747, 'A. O. Smith Corp', 'AOS', 'Industrials', NOW()),
(435205, 'Teradyne Inc', 'TER', 'InformationTechnology', NOW()),
(435353, 'The Travelers Companies Inc', 'TRV', 'Financials', NOW()),
(1869593, 'Liberty Global PLC', 'LBYAV', 'CommunicationServices', NOW()),
(429653, 'Amcor PLC', 'CAMCR', 'Materials', NOW()),
(429845, 'Arrow Electronics Inc', 'ARW', 'InformationTechnology', NOW()),
(430304, 'CACI International Inc', 'CACI', 'Industrials', NOW()),
(430351, 'Campbell Soup Co', 'CPB', 'ConsumerStaples', NOW()),
(430445, 'Celanese Corp', 'CE', 'Materials', NOW()),
(430828, 'Cloudflare Inc', 'NET', 'InformationTechnology', NOW()),
(431326, 'Donaldson Co Inc', 'DCI', 'Industrials', NOW()),
(431559, 'Essex Property Trust Inc', 'ESS', 'RealEstate', NOW()),
(431809, 'FMC Corp', 'FMC', 'Materials', NOW()),
(431930, 'Gates Industrial Corp PLC', 'CGTES', 'Industrials', NOW()),
(432366, 'IDEX Corp', 'IEX', 'Industrials', NOW()),
(432550, 'Iron Mountain Inc', 'IRM', 'RealEstate', NOW()),
(432950, 'Lamb Weston Holdings Inc', 'LW', 'ConsumerStaples', NOW()),
(433066, 'Live Nation Entertainment Inc', 'LYV', 'CommunicationServices', NOW()),
(433440, 'Molson Coors Beverage Company', 'TAP', 'ConsumerStaples', NOW()),
(433446, 'MongoDB Inc', 'MDB', 'InformationTechnology', NOW()),
(433603, 'Newell Brands Inc', 'NWL', 'ConsumerDiscretionary', NOW()),
(433686, 'Nordson Corp', 'NDSN', 'Industrials', NOW()),
(434096, 'Pioneer Natural Resources Co', 'PXD', 'Energy', NOW()),
(434174, 'Primerica Inc', 'PRI', 'Financials', NOW()),
(2333803, 'DEPARTMENT OF STATE PENNSYLVANIA', 'None', 'N/A', NOW()),
(2334327, 'HPS SPECIAL SITUATIONS OPPORTUNITY FUND II LP', 'None', 'N/A', NOW()),
(429898, 'CITY OF ATLANTA', 'None', 'N/A', NOW()),
(433405, 'MISSISSIPPI DEVELOPMENT BANK', 'None', 'N/A', NOW()),
(434960, 'STATE OF ILLINOIS', 'None', 'N/A', NOW()),
(446117, 'WASHINGTON KING COUNTY', 'None', 'N/A', NOW()),
(2331401, 'TRIBOROUGH BRIDGE AND TUNNEL AUTHORITY', 'None', 'N/A', NOW()),
(2333494, 'CME CORN', 'None', 'N/A', NOW()),
(430630, 'CITY OF DALLAS', 'None', 'N/A', NOW()),
(430953, 'CONNECTICUT HOUSING FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(431178, 'CITIES OF DALLAS AND FORT WORTH TEXAS', 'None', 'N/A', NOW()),
(433632, 'NEW YORK CITY MUNICIPAL WATER FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(434969, 'STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(435227, 'TEXAS TRANSPORTATION COMMISSION', 'None', 'N/A', NOW()),
(435982, 'Wynn Resorts Ltd', 'None', 'ConsumerDiscretionary', NOW()),
(443910, 'CITY OF HOUSTON', 'None', 'N/A', NOW()),
(2331058, 'BRAZIL GOVERNMENT BONDS', 'None', 'N/A', NOW()),
(2334849, 'SKI MASK DOG', 'None', 'N/A', NOW()),
(429827, 'ARIZONA INDUSTRIAL DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(433805, 'OHIO STATE UNIVERSITY', 'None', 'N/A', NOW()),
(2334550, 'INTAPP INC', 'None', 'InformationTechnology', NOW()),
(430576, 'CITY AND COUNTY OF DENVER COLORADO', 'None', 'N/A', NOW()),
(430622, 'CITY OF CLEVELAND OHIO', 'None', 'N/A', NOW()),
(431374, 'DXC Technology Co', 'XLK', 'InformationTechnology', NOW()),
(432025, 'Goldman Sachs AccessTreasury 0-1 Year ETF', '^TNX', 'N/A', NOW()),
(434285, 'Quest Diagnostics Inc', 'DIA', 'Healthcare', NOW()),
(431586, 'Eversource Energy', 'XLE', 'Utilities', NOW()),
(432553, 'iShares 10-20 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(432649, 'iShares Trust - iShares Russell 2000 ETF', 'IWM', 'N/A', NOW()),
(433019, 'Liberty Media Corp Braves Group', 'DIA', 'CommunicationServices', NOW()),
(434755, 'Snap-On Inc', 'SNAP', 'Industrials', NOW()),
(430092, 'BITCOIN', 'BTC-USD', 'N/A', NOW()),
(431272, 'Diamondback Energy Inc', 'XLE', 'Energy', NOW()),
(432344, 'Hyatt Hotels Corp', 'T', 'ConsumerDiscretionary', NOW()),
(432648, 'iShares Russell 1000 Value ETF', 'IWM', 'N/A', NOW()),
(2334180, 'SHOALS TECHNOLOGIES GRP INC', 'XLK', 'Industrials', NOW()),
(430457, 'CenterPoint Energy Inc', 'XLE', 'Utilities', NOW()),
(2332102, 'Southern States Bancshares Inc', 'SSBK', 'Financials', NOW()),
(2334019, 'CONSTELLATION ENE CORP', 'RPCEG', 'Utilities', NOW()),
(430035, 'Beacon Roofing Supply Inc', 'BECN', 'Industrials', NOW()),
(430075, 'BHP Group Ltd', 'BHP', 'Materials', NOW()),
(430175, 'Booz Allen Hamilton Holding Corporation', 'BAH', 'Industrials', NOW()),
(431343, 'Dover Corp', 'DOV', 'Industrials', NOW()),
(432203, 'H D F C Bank Ltd', 'HDB', 'Financials', NOW()),
(432717, 'Jabil Inc', 'JBL', 'InformationTechnology', NOW()),
(433067, 'Livent Corp', 'LTHM', 'Materials', NOW()),
(434459, 'Royal Caribbean Group', 'RCL', 'ConsumerDiscretionary', NOW()),
(434751, 'The J M Smucker Company', 'SJM', 'ConsumerStaples', NOW()),
(435663, 'Ventas Inc', 'VTR', 'RealEstate', NOW()),
(2331138, 'NU HOLDINGS LTD', 'LTDNU', 'Financials', NOW()),
(2334103, 'Ranger Equity Bear ETF', 'FHDGE', 'N/A', NOW()),
(2334228, 'HALEON PLC', 'LCHLN', 'Healthcare', NOW()),
(430342, 'Camden Property Trust', 'CPT', 'RealEstate', NOW()),
(430418, 'Catalent Inc', 'CTLT', 'Healthcare', NOW()),
(431413, 'Edison International', 'EIX', 'Utilities', NOW()),
(431986, 'Glaxosmithkline PLC', 'LCGSK', 'Healthcare', NOW())
ON CONFLICT (id) DO NOTHING;