INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(431320, 'Dominion Energy Inc', 'XLE', 'Utilities', NOW()),
(432199, 'HCA Healthcare Inc', 'XLV', 'Healthcare', NOW()),
(431121, 'CrowdStrike Holdings Inc', 'CRWD', 'InformationTechnology', NOW()),
(431527, 'EPAM Systems Inc', 'EPAM', 'InformationTechnology', NOW()),
(431946, 'General Motors Co', 'GM', 'ConsumerDiscretionary', NOW()),
(432899, 'KKR & Co Inc', 'KKR', 'Financials', NOW()),
(433952, 'Parker-Hannifin Corp', 'PH', 'Industrials', NOW()),
(431772, 'Fiserv Inc', 'FI', 'Financials', NOW()),
(433586, 'NetApp Inc', 'NTAP', 'InformationTechnology', NOW()),
(431208, 'DEERE & COMPANY', 'ANYDE', 'Industrials', NOW()),
(431819, 'Ford Motor Co', 'F', 'ConsumerDiscretionary', NOW()),
(431998, 'GLOBAL PAYMENTS Inc', 'GPN', 'Financials', NOW()),
(432491, 'Intuitive Surgical Inc', 'ISRG', 'Healthcare', NOW()),
(429725, 'Amgen Inc', 'AMGN', 'Healthcare', NOW()),
(431833, 'Fortinet Inc', 'FTNT', 'InformationTechnology', NOW()),
(433927, 'Palo Alto Networks Inc', 'PANW', 'InformationTechnology', NOW()),
(429708, 'American Tower Corp', 'AMT', 'RealEstate', NOW()),
(2334695, 'GE VERNOVA INC', 'NCGEV', 'Industrials', NOW()),
(430231, 'Bristol-Myers Squibb Co', 'BMY', 'Healthcare', NOW()),
(431124, 'Crown Castle International Corp', 'CCI', 'RealEstate', NOW()),
(431944, 'General Electric Co', 'GE', 'Industrials', NOW()),
(429741, 'Analog Devices Inc', 'ADI', 'InformationTechnology', NOW()),
(434348, 'Regeneron Pharmaceuticals Inc', 'REGN', 'Healthcare', NOW()),
(435112, 'Sysco Corporation', 'SYY', 'ConsumerStaples', NOW()),
(433227, 'Marriott International Inc', 'MAR', 'ConsumerDiscretionary', NOW()),
(435040, 'Stryker Corp', 'SYK', 'Healthcare', NOW()),
(429677, 'American Express Co', 'AXP', 'Financials', NOW()),
(429932, 'Automatic Data Processing Inc', 'ADP', 'Industrials', NOW()),
(430041, 'Becton Dickinson and Co', 'BDX', 'Healthcare', NOW()),
(430133, 'Blackstone Group Inc', 'BX', 'Financials', NOW()),
(430994, 'Corning Inc', 'GLW', 'InformationTechnology', NOW()),
(431608, 'Exxon Mobil Corp', 'XOM', 'Energy', NOW()),
(432965, 'The Estee Lauder Cos Inc', 'EL', 'ConsumerStaples', NOW()),
(433456, 'Monster Beverage Corp', 'MNST', 'ConsumerStaples', NOW()),
(433568, 'NCR Corp', 'NCR', 'InformationTechnology', NOW()),
(430305, 'Cadence Design Systems Inc', 'CDNS', 'InformationTechnology', NOW()),
(433229, 'Marsh & McLennan Companies Inc', 'MMC', 'Financials', NOW()),
(434055, 'Philip Morris International Inc', 'PM', 'ConsumerStaples', NOW()),
(435611, 'VANGUARD LONG TERM TAX EXEMPT FUND', 'VWLUX', 'N/A', NOW()),
(431315, 'Dollar General Corporation', 'DG', 'ConsumerStaples', NOW()),
(435282, 'T-Mobile US Inc', 'TMUS', 'CommunicationServices', NOW()),
(432298, 'Honeywell International Inc', 'HON', 'Industrials', NOW()),
(433444, 'Mondelez International Inc', 'MDLZ', 'ConsumerStaples', NOW()),
(435532, 'U.S. Bancorp', 'USB', 'Financials', NOW()),
(431346, 'Dow Inc', 'DOW', 'Materials', NOW()),
(431395, 'Eaton Corp PLC', 'LCETN', 'Industrials', NOW()),
(433130, 'Lululemon Athletica Inc', 'LULU', 'ConsumerDiscretionary', NOW()),
(433283, 'McKesson Corp', 'MCK', 'Healthcare', NOW()),
(435808, 'Waste Management Inc', 'WM', 'Industrials', NOW()),
(433735, 'Novo Nordisk A/S', 'SNVO', 'Healthcare', NOW()),
(429428, '3M Co', 'MMM', 'Industrials', NOW()),
(429939, 'Avantor Inc', 'AVTR', 'Healthcare', NOW()),
(431299, 'Warner Bros Discover Inc', 'WBD', 'CommunicationServices', NOW()),
(434316, 'RTX Corp', 'RTX', 'Industrials', NOW()),
(434562, 'SBA Communications Corp', 'SBAC', 'RealEstate', NOW()),
(435958, 'Workday Inc', 'WDAY', 'InformationTechnology', NOW()),
(430543, 'Chubb Ltd', 'CB', 'Financials', NOW()),
(435639, 'Vanguard Total Stock Market ETF', 'TFVTI', 'N/A', NOW()),
(431607, 'Extra Space Storage Inc', 'EXR', 'RealEstate', NOW()),
(432924, 'The Kraft Heinz Co', 'KHC', 'ConsumerStaples', NOW()),
(433688, 'Norfolk Southern Corp', 'NSC', 'Industrials', NOW()),
(434883, 'S&P Global Inc', 'SPGI', 'Financials', NOW()),
(436020, 'Zimmer Biomet Holdings Inc', 'ZBH', 'Healthcare', NOW()),
(430554, 'Cigna Corp', 'CI', 'Healthcare', NOW()),
(433081, 'Lockheed Martin Corp', 'LMT', 'Industrials', NOW()),
(434460, 'Shell PLC', 'CSHEL', 'Energy', NOW()),
(430834, 'CME Group Inc', 'CME', 'Financials', NOW()),
(430875, 'Colgate-Palmolive Co', 'CL', 'ConsumerStaples', NOW()),
(432250, 'The Hershey Co', 'HSY', 'ConsumerStaples', NOW()),
(434151, 'PPG Industries Inc', 'PPG', 'Materials', NOW()),
(435281, 'The TJX Companies Inc', 'TJX', 'ConsumerDiscretionary', NOW()),
(435430, 'Tyson Foods Inc', 'TSN', 'ConsumerStaples', NOW()),
(430962, 'Constellation Brands Inc', 'STZ', 'ConsumerStaples', NOW()),
(433338, 'Metlife Inc', 'MET', 'Financials', NOW()),
(434194, 'The Progressive Corp', 'PGR', 'Financials', NOW()),
(431418, 'Edwards Lifesciences Corp', 'EW', 'Healthcare', NOW()),
(432866, 'Keurig Dr Pepper Inc', 'KDP', 'ConsumerStaples', NOW()),
(432937, 'Laboratory Corp of America Holdings', 'LH', 'Healthcare', NOW()),
(433819, 'Old Dominion Freight Line Inc', 'ODFL', 'Industrials', NOW()),
(433977, 'Paychex Inc', 'PAYX', 'Industrials', NOW()),
(429720, 'Cencora Inc', 'COR', 'Healthcare', NOW()),
(434954, 'STATE OF CONNECTICUT', 'None', 'N/A', NOW()),
(431333, 'DORMITORY AUTHORITY OF THE STATE OF NEW YORK', 'None', 'N/A', NOW()),
(434327, 'Realty Income Corp', 'None', 'RealEstate', NOW()),
(2334898, 'MH FOUR WINDS LLC', 'None', 'N/A', NOW()),
(433232, 'Martin Marietta Materials Inc', 'XLB', 'Materials', NOW()),
(429583, 'Alexandria Real Estate Equities Inc', 'VNQ', 'RealEstate', NOW()),
(431506, 'Enphase Energy Inc', 'XLE', 'InformationTechnology', NOW()),
(433817, 'OKTA Inc', 'OKTA', 'InformationTechnology', NOW()),
(434353, 'Regions Financial Corp', 'XLF', 'Financials', NOW()),
(433379, 'Microchip Technology Inc', 'XLK', 'InformationTechnology', NOW()),
(2331336, 'Palantir Technologies Inc', 'PLTR', 'InformationTechnology', NOW()),
(431298, 'Discover Financial Services', 'XLF', 'Financials', NOW()),
(431783, 'FleetCor Technologies Inc', 'XLK', 'Financials', NOW()),
(433236, 'Marvell Technology Inc', 'XLK', 'InformationTechnology', NOW()),
(435342, 'Trane Technologies PLC', 'XLK', 'Industrials', NOW()),
(430573, 'Citizens Financial Group Inc', 'XLF', 'Financials', NOW()),
(434233, 'Prudential Financial Inc', 'XLF', 'Financials', NOW()),
(435765, 'Westinghouse Air Brake Technologies Corp', 'XLK', 'Industrials', NOW()),
(432382, 'Illumina Inc', 'ILMN', 'Healthcare', NOW())
ON CONFLICT (id) DO NOTHING;