INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(432394, 'Incyte Corp', 'INCY', 'Healthcare', NOW()),
(433350, 'Mettler-Toledo International Inc', 'MTD', 'Healthcare', NOW()),
(433427, 'MKS Instruments Inc', 'MKSI', 'InformationTechnology', NOW()),
(433769, 'nVent Electric PLC', 'LCNVT', 'Industrials', NOW()),
(433772, 'NVR Inc', 'NVR', 'ConsumerDiscretionary', NOW()),
(435061, 'Sun Communities Inc', 'SUI', 'RealEstate', NOW()),
(435457, 'Unilever PLC', 'PLCUL', 'ConsumerStaples', NOW()),
(435953, 'Woodward Inc', 'WWD', 'Industrials', NOW()),
(2332090, 'Kellogg Co', 'K', 'ConsumerStaples', NOW()),
(2334768, 'APPLOVIN CORP', 'RPAPP', 'InformationTechnology', NOW()),
(429577, 'Alcoa Corp', 'AA', 'Materials', NOW()),
(429608, 'Alliance Resource Partners LP', 'PARLP', 'Energy', NOW()),
(429848, 'Arthur J. Gallagher & Co', 'AJG', 'Financials', NOW()),
(430439, 'CDW Corp', 'CDW', 'InformationTechnology', NOW()),
(431698, 'FirstCash Holdings Inc', 'FCFS', 'Financials', NOW()),
(432254, 'Hewlett Packard Enterprise Co', 'HPE', 'InformationTechnology', NOW()),
(432879, 'Kinder Morgan Inc', 'KMI', 'Energy', NOW()),
(434343, 'Regal Rexnord Corporation', 'RRX', 'Industrials', NOW()),
(434817, 'Southwest Airlines Co', 'LUV', 'Industrials', NOW()),
(1608657, 'CBRE Group Inc', 'CBRE', 'RealEstate', NOW()),
(2290378, 'Welltower Inc', 'WELL', 'RealEstate', NOW()),
(2334905, 'YIELDMAX SMCI OPTION INCOME STRATEGY ETF', 'SMCY', 'N/A', NOW()),
(429501, 'Advance Auto Parts Inc', 'AAP', 'ConsumerDiscretionary', NOW()),
(429811, 'Arch Capital Group Ltd', 'ACGL', 'Financials', NOW()),
(430056, 'Berkley (W.R.) Corp', 'WRB', 'Financials', NOW()),
(431721, 'First Republic Bank', 'FRC', 'Financials', NOW()),
(431958, 'Genpact Ltd', 'G', 'Industrials', NOW()),
(433043, 'Lincoln National Corp', 'LNC', 'Financials', NOW()),
(434542, 'Sanofi', 'SNY', 'Healthcare', NOW()),
(434726, 'Skechers U S A Inc', 'SKX', 'ConsumerDiscretionary', NOW()),
(435438, 'UDR Inc', 'UDR', 'RealEstate', NOW()),
(1570797, 'HSBC Holdings PLC', 'CHSBC', 'Financials', NOW()),
(429906, 'Atlassian Corp PLC', 'CTEAM', 'InformationTechnology', NOW()),
(430199, 'BP PLC', 'PLCBP', 'Energy', NOW()),
(430308, 'Caesars Entertainment Inc', 'CZR', 'ConsumerDiscretionary', NOW()),
(430978, 'The Cooper Cos Inc', 'COO', 'Healthcare', NOW()),
(431330, 'DoorDash Inc', 'DASH', 'ConsumerDiscretionary', NOW()),
(431611, 'FactSet Research Systems Inc', 'FDS', 'Financials', NOW()),
(431863, 'Franklin Resources Inc', 'BEN', 'Financials', NOW()),
(431940, 'Generac Holdings Inc', 'GNRC', 'Industrials', NOW()),
(432141, 'Halliburton Co', 'HAL', 'Energy', NOW()),
(432185, 'Hasbro Inc', 'HAS', 'ConsumerDiscretionary', NOW()),
(432314, 'Houlihan Lokey Inc', 'HLI', 'Financials', NOW()),
(432707, 'ITT Inc', 'ITT', 'Industrials', NOW()),
(432876, 'Kimco Realty Corp', 'KIM', 'RealEstate', NOW()),
(434426, 'Roche Holding AG', 'RHHBY', 'Healthcare', NOW()),
(434930, 'Stanley Black & Decker Inc', 'SWK', 'Industrials', NOW()),
(435670, 'Verisign Inc', 'VRSN', 'InformationTechnology', NOW()),
(435909, 'The Williams Cos Inc', 'WMB', 'Energy', NOW()),
(2334032, 'FLEX LNG LTD', 'DFLNG', 'Energy', NOW()),
(429941, 'Avery Dennison Corp', 'AVY', 'Materials', NOW()),
(430279, 'Builders FirstSource Inc', 'BLDR', 'Industrials', NOW()),
(431146, 'Cummins Inc', 'CMI', 'Industrials', NOW()),
(431207, 'Deckers Outdoor Corp', 'DECK', 'ConsumerDiscretionary', NOW()),
(431831, 'FORT BEND INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(434012, 'PENNSYLVANIA TURNPIKE COMMISSION', 'None', 'N/A', NOW()),
(434950, 'STATE OF CALIFORNIA', 'None', 'N/A', NOW()),
(2333857, 'CME SOYBEAN', 'None', 'N/A', NOW()),
(2334337, 'CAPPED BUFFERED ENHANCED PARTICIPATION', 'None', 'N/A', NOW()),
(429997, 'Barclays Bank PLC', 'None', 'Financials', NOW()),
(433346, 'METROPOLITAN WASHINGTON AIRPORTS AUTHORITY', 'None', 'N/A', NOW()),
(433811, 'OKLAHOMA DEVELOPMENT FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(434967, 'STATE OF MARYLAND', 'None', 'N/A', NOW()),
(2331163, '3G COURSER ONSHORE FUND LP', 'None', 'N/A', NOW()),
(2334007, 'CME SOYBEAN MEAL', 'None', 'N/A', NOW()),
(2334087, 'SEVEN BRIDGES MULTI STRATEGY FUND LP', 'None', 'N/A', NOW()),
(433003, 'LEWIS & CLARK AGRIFOOD FUND II LP', 'None', 'N/A', NOW()),
(2334794, 'MAYS (J.W.) INC', 'None', 'RealEstate', NOW()),
(431085, 'COUNTY OF WILL ILLINOIS', 'None', 'N/A', NOW()),
(431241, 'DEPARTMENT OF TRANSPORTATION OF MARYLAND', 'None', 'N/A', NOW()),
(433122, 'LPL Financial Holdings Inc', 'XLF', 'Financials', NOW()),
(434901, 'Spotify Technology S.A', 'SPOT', 'CommunicationServices', NOW()),
(435099, 'Synchrony Financial', 'XLF', 'Financials', NOW()),
(435984, 'Xcel Energy Inc', 'XLE', 'Utilities', NOW()),
(429791, 'Applied Industrial Technologies Inc', 'XLK', 'Industrials', NOW()),
(429555, 'AKAMAI TECHNOLOGIES Inc', 'XLK', 'InformationTechnology', NOW()),
(430003, 'Barrick Gold Corp', 'GLD', 'Materials', NOW()),
(430240, 'Broadridge Financial Solutions Inc', 'XLF', 'Industrials', NOW()),
(430560, 'Cincinnati Financial Corp', 'XLF', 'Financials', NOW()),
(432555, 'iShares 1-3 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(434177, 'Principal Financial Group Inc', 'XLF', 'Financials', NOW()),
(434314, 'Raymond James Financial Inc', 'XLF', 'Financials', NOW()),
(434615, 'Seagate Technology Holdings PLC', 'XLK', 'InformationTechnology', NOW()),
(435428, 'Tyler Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(1571408, 'L3Harris Technologies Inc', 'XLK', 'Industrials', NOW()),
(431598, 'Expedia Group Inc', 'DIA', 'ConsumerDiscretionary', NOW()),
(434139, 'PORT OF SEATTLE WASHINGTON', 'T', 'N/A', NOW()),
(434209, 'ProShares Short QQQ', 'QQQ', 'N/A', NOW()),
(432327, 'Hubbell Inc', 'HUBB', 'Industrials', NOW()),
(432434, 'ING Groep NV', 'NVING', 'Financials', NOW()),
(432457, 'Insulet Corp', 'PODD', 'Healthcare', NOW()),
(432906, 'Knight-Swift Transportation Holdings Inc', 'KNX', 'Industrials', NOW()),
(433478, 'The Mosaic Company', 'MOS', 'Materials', NOW()),
(433730, 'Novartis AG', 'AGNVS', 'Healthcare', NOW()),
(433846, 'ONEOK Inc', 'OKE', 'Energy', NOW()),
(435585, 'Vanguard Dividend Appreciation ETF', 'TFVIG', 'N/A', NOW()),
(2334583, 'VERALTO CORP', 'PVLTO', 'Industrials', NOW()),
(430062, 'Best Buy Co Inc', 'BBY', 'ConsumerDiscretionary', NOW()),
(431544, 'Equitable Holdings Inc', 'EQH', 'Financials', NOW()),
(432243, 'Hercules Capital Inc', 'HTGC', 'Financials', NOW())
ON CONFLICT (id) DO NOTHING;