INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(431589, 'Evolution AB (publ)', 'EVVTY', 'ConsumerDiscretionary', NOW()),
(431597, 'ExlService Holdings Inc', 'EXLS', 'Industrials', NOW()),
(431632, 'Federal Home Loan Mortgage Corp', 'FMCC', 'Financials', NOW()),
(431649, 'Ferrari NV', 'VRACE', 'ConsumerDiscretionary', NOW()),
(432026, 'Goldman Sachs ActiveBeta Emerging Markets Equity ETF', 'GLD', 'N/A', NOW()),
(432371, 'iHeartMedia Inc', 'DIA', 'CommunicationServices', NOW()),
(432692, 'iShares US Technology ETF', 'XLK', 'N/A', NOW()),
(434438, 'Roku Inc', 'ROKU', 'CommunicationServices', NOW()),
(434499, 'Sabra Health Care REIT Inc', 'VNQ', 'RealEstate', NOW()),
(434630, 'The Consumer Staples Select Sector SPDR Fund', 'XLP', 'N/A', NOW()),
(434631, 'The Select Sector SPDR Trust - The Energy Select Sector SPDR Fund', 'XLE', 'N/A', NOW()),
(434866, 'SPDR S&P Biotech ETF', 'XLK', 'N/A', NOW()),
(434909, 'Sprott Physical Gold & Silver Trust', 'GLD', 'N/A', NOW()),
(431801, 'FLORIDA STATE BOARD OF EDUCATION', 'None', 'N/A', NOW()),
(435147, 'TC Energy Corp', 'XLE', 'Energy', NOW()),
(431661, 'FIDELITY CONTRAFUND', 'FCNTX', 'N/A', NOW()),
(431663, 'Fidelity Covington Trust - Fidelity Dividend ETF for Rising Rates', 'FDRR', 'N/A', NOW()),
(431786, 'Flex Ltd', 'FLEX', 'InformationTechnology', NOW()),
(431894, 'FTI Consulting Inc', 'FCN', 'Industrials', NOW()),
(431970, 'Getty Realty Corp', 'GTY', 'RealEstate', NOW()),
(431978, 'Givaudan SA', 'GVDNY', 'Materials', NOW()),
(432049, 'Goodyear Tire & Rubber Co', 'GT', 'ConsumerDiscretionary', NOW()),
(432063, 'Grand Canyon Education Inc', 'LOPE', 'ConsumerDiscretionary', NOW()),
(432097, 'Green Plains Partners LP', 'LPGPP', 'Energy', NOW()),
(432226, 'Helen of Troy Ltd', 'HELE', 'ConsumerDiscretionary', NOW()),
(432242, 'Herc Holdings Inc', 'HRI', 'Industrials', NOW()),
(432256, 'Hexagon AB', 'HXGBY', 'InformationTechnology', NOW()),
(432275, 'Hitachi Ltd', 'HTHIY', 'Industrials', NOW()),
(432299, 'Hong Kong Exchanges and Clearing Ltd', 'HKXCY', 'Financials', NOW()),
(432305, 'Horizon Therapeutics Public Ltd Co', 'HZNP', 'Healthcare', NOW()),
(432319, 'The Howard Hughes Corp', 'HHC', 'RealEstate', NOW()),
(432358, 'Icon PLC', 'CICLR', 'Healthcare', NOW()),
(432360, 'IDACORP Inc', 'IDA', 'Utilities', NOW()),
(432472, 'Intercontinental Hotels Group PLC', 'LCIHG', 'ConsumerDiscretionary', NOW()),
(432479, 'Intesa Sanpaolo SPA', 'ISNPY', 'Financials', NOW()),
(432537, 'Ionis Pharmaceuticals Inc', 'IONS', 'Healthcare', NOW()),
(432569, 'iShares Core Dividend Growth ETF', 'FDGRO', 'N/A', NOW()),
(432571, 'iShares Core MSCI EAFE ETF', 'FIEFA', 'N/A', NOW()),
(432727, 'James Hardie Industries PLC', 'LCJHX', 'Materials', NOW()),
(432742, 'Japan Tobacco Inc', 'JAPAY', 'ConsumerStaples', NOW()),
(432746, 'JBG SMITH Properties', 'JBGS', 'RealEstate', NOW()),
(432840, 'Kddi Corp', 'KDDIY', 'CommunicationServices', NOW()),
(432931, 'Kubota Corp', 'KUBTY', 'Industrials', NOW()),
(433058, 'Lithia Motors Inc', 'LAD', 'ConsumerDiscretionary', NOW()),
(433060, 'Littelfuse Inc', 'LFUS', 'InformationTechnology', NOW()),
(433075, 'Lloyds Banking Group PLC', 'LCLYG', 'Financials', NOW()),
(433094, 'Lonza Group AG, Zuerich', 'LZAGY', 'Healthcare', NOW()),
(433172, 'Magna International Inc', 'MGA', 'ConsumerDiscretionary', NOW()),
(433475, 'Morningstar Inc', 'MORN', 'Financials', NOW()),
(433490, 'MS&AD Insurance Group Holdings Inc', 'MSADY', 'Financials', NOW()),
(433550, 'National Retail Properties Inc', 'NNN', 'RealEstate', NOW()),
(433643, 'The New York Times Company', 'NYT', 'CommunicationServices', NOW()),
(433654, 'NICE Ltd', 'NICE', 'InformationTechnology', NOW()),
(433743, 'NUANCE MID CAP VALUE FUND', 'NMVZX', 'N/A', NOW()),
(433757, 'Nushares ETF Trust - Nuveen ESG Large Cap ETF', 'FNULC', 'N/A', NOW()),
(433831, 'Olympus Corp', 'OLYMY', 'Healthcare', NOW()),
(433887, 'Orsted A/S', 'DNNGY', 'Utilities', NOW()),
(433896, 'Otsuka Holdings Co Ltd', 'OTSKY', 'Healthcare', NOW()),
(433953, 'Park Hotels & Resorts Inc', 'PK', 'RealEstate', NOW()),
(433969, 'Patrick Industries Inc', 'PATK', 'ConsumerDiscretionary', NOW()),
(434121, 'Polaris Inc', 'PII', 'ConsumerDiscretionary', NOW()),
(434146, 'PotlatchDeltic Corp', 'PCH', 'RealEstate', NOW()),
(434317, 'RBC Bearings Inc', 'RBC', 'Industrials', NOW()),
(434346, 'Regency Centers Corp', 'REG', 'RealEstate', NOW()),
(434596, 'Schwab US Large-Cap ETF', 'FSCHX', 'N/A', NOW()),
(434662, 'Seven & I Holdings Co Ltd', 'SVNDY', 'ConsumerStaples', NOW()),
(434748, 'Smith & Nephew PLC', 'LCSNN', 'Healthcare', NOW()),
(434767, 'Softbank Group Corp', 'SFTBY', 'CommunicationServices', NOW()),
(434813, 'SouthState Corporation', 'SSB', 'Financials', NOW()),
(434820, 'Southwest Gas Holdings Inc', 'SWX', 'Utilities', NOW()),
(435048, 'Sumitomo Chemical Co Ltd', 'SOMMY', 'Materials', NOW()),
(435070, 'Suntory Beverage & Food Ltd', 'STBFY', 'ConsumerStaples', NOW()),
(435095, 'Symrise AG', 'SYIEY', 'Materials', NOW()),
(435206, 'Terex Corp', 'TEX', 'Industrials', NOW()),
(435222, 'Texas Pacific Land Corp', 'TPL', 'Energy', NOW()),
(435247, 'The Shyft Group Inc', 'SHYF', 'Industrials', NOW()),
(435284, 'Tokio Marine Holdings Inc', 'TKOMY', 'Financials', NOW()),
(435433, 'Ubiquiti Inc', 'UI', 'InformationTechnology', NOW()),
(432120, 'GS FINANCE CORP', 'None', 'N/A', NOW()),
(432539, 'IOWA FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(432894, 'KIRKOSWALD GLOBAL MACRO FUND LP', 'None', 'N/A', NOW()),
(433144, 'LYNETT CAPITAL PARTNERS II LP', 'None', 'N/A', NOW()),
(433341, 'METROPOLITAN GOVERNMENT OF NASHVILLE AND DAVIDSON COUNTY TENNESSEE', 'None', 'N/A', NOW()),
(433347, 'METROPOLITAN WATER DISTRICT OF SOUTHERN CALIFORNIA', 'None', 'N/A', NOW()),
(433690, 'NORTH ALLEGHENY SCHOOL DISTRICT ALLEGHENY COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(433816, 'OKLAHOMA WATER RESOURCES BOARD', 'None', 'N/A', NOW()),
(433959, 'PARTNERRE FINANCE B LLC', 'None', 'N/A', NOW()),
(434974, 'STATE OF NEVADA', 'None', 'N/A', NOW()),
(434984, 'STATE OF OKLAHOMA', 'None', 'N/A', NOW()),
(434985, 'STATE OF OREGON', 'None', 'N/A', NOW()),
(435129, 'TAMPA FLORIDA SOLID WASTE SYSTEM', 'None', 'N/A', NOW()),
(435516, 'UNIVERSITY OF TEXAS', 'None', 'N/A', NOW()),
(435817, 'WAXAHACHIE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(478121, 'FLORIDA HOMELOAN CORP', 'None', 'N/A', NOW()),
(2019743, 'CITY OF SAN ANTONIO TEXAS WATER SYSTEM', 'None', 'N/A', NOW()),
(2265164, 'CITY OF PHOENIX ARIZONA', 'None', 'N/A', NOW()),
(2331603, 'CITY OF OMAHA NEBRASKA', 'None', 'N/A', NOW()),
(2331863, 'NEW JERSEY EDUCATIONAL FACILITIES AUTHORITY', 'None', 'N/A', NOW()),
(2331987, 'PFLUGERVILLE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2332587, 'IBM INTERNATIONAL GROUP CAPITAL', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;