INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(432453, 'Insight Enterprises Inc', 'NSIT', 'InformationTechnology', NOW()),
(435914, 'Willis Towers Watson PLC', 'LCWTW', 'Financials', NOW()),
(1734510, 'CF Industries Holdings Inc', 'CF', 'Materials', NOW()),
(432239, 'Henry (Jack) & Associates Inc', 'JKHY', 'Financials', NOW()),
(435895, 'White Mountains Insurance Group Ltd', 'WTM', 'Financials', NOW()),
(433257, 'Match Group Inc', 'MTCH', 'CommunicationServices', NOW()),
(431403, 'eBay Inc', 'EBAY', 'ConsumerDiscretionary', NOW()),
(434714, 'Simpson Manufacturing Co. Inc', 'SSD', 'Industrials', NOW()),
(429803, 'Aramark', 'ARMK', 'ConsumerDiscretionary', NOW()),
(432737, 'Janus Henderson Mortgage-Backed Securities ETF', 'FJMBS', 'N/A', NOW()),
(2334924, 'REDDIT INC', 'CRDDT', 'CommunicationServices', NOW()),
(432311, 'Host Hotels & Resorts Inc', 'HST', 'RealEstate', NOW()),
(435121, 'Takeda Pharmaceutical Co Ltd', 'TAK', 'Healthcare', NOW()),
(429818, 'ARES CAPITAL CORPORATION', 'NARCC', 'Financials', NOW()),
(431700, 'First Citizens BancShares Inc', 'FCNCA', 'Financials', NOW()),
(435192, 'Tempur Sealy International Inc', 'SGI', 'ConsumerDiscretionary', NOW()),
(431199, 'DBS Group Holdings Ltd', 'DBSDY', 'Financials', NOW()),
(431778, 'Five Below Inc', 'FIVE', 'ConsumerDiscretionary', NOW()),
(434247, 'Public Service Enterprise Group Inc', 'PEG', 'Utilities', NOW()),
(2333903, 'ISHARES BB RAT CORP BOND ETF', 'FHYBB', 'N/A', NOW()),
(429655, 'Amdocs Ltd', 'DOX', 'InformationTechnology', NOW()),
(431475, 'Endava PLC', 'CDAVA', 'InformationTechnology', NOW()),
(432352, 'ICF International Inc', 'ICFI', 'Industrials', NOW()),
(435449, 'Under Armour Inc', 'UAA', 'ConsumerDiscretionary', NOW()),
(2334194, 'SPRINGWORKS THERAPEUTICS INC', 'CSWTX', 'Healthcare', NOW()),
(430375, 'Capri Holdings Ltd', 'CPRI', 'ConsumerDiscretionary', NOW()),
(431484, 'Enel Ente Nazionale Per L''Energia Elettrica SPA, Roma', 'ENLAY', 'Utilities', NOW()),
(433915, 'Pacific Premier Bancorp Inc', 'PPBI', 'Financials', NOW()),
(2332314, 'Direxion Shares ETF Trust - Direxion Daily Small Cap Bear 3X Shares', 'TZA', 'N/A', NOW()),
(431235, 'DENTSPLY SIRONA Inc', 'XRAY', 'Healthcare', NOW()),
(432162, 'HARDING LOEVNER INTERNATIONAL EQUITY PORTFOLIO', 'HLMIX', 'N/A', NOW()),
(433628, 'News Corp', 'NWSA', 'CommunicationServices', NOW()),
(434309, 'Rapid7 Inc', 'RPD', 'InformationTechnology', NOW()),
(435849, 'Western Alliance Bancorporation', 'WAL', 'Financials', NOW()),
(2334329, 'SCHNEIDER NATIONAL INC', 'CSNDR', 'Industrials', NOW()),
(429526, 'AGCO Corp', 'AGCO', 'Industrials', NOW()),
(430217, 'BRIDGE BUILDER LARGE CAP GROWTH FUND', 'BBGLX', 'N/A', NOW()),
(431601, 'Exponent Inc', 'EXPO', 'Industrials', NOW()),
(432333, 'Hudson Pacific Properties Inc', 'HPP', 'RealEstate', NOW()),
(434435, 'Rogers Communications Inc', 'RCI', 'CommunicationServices', NOW()),
(435664, 'Veracyte Inc', 'VCYT', 'Healthcare', NOW()),
(2332207, 'CyberArk Software Ltd', 'CYBR', 'InformationTechnology', NOW()),
(2333776, 'UNITY SOFTWARE INC', 'INCU', 'InformationTechnology', NOW()),
(2334605, 'LAZARD INTERNATIONAL STRATEGIC EQUITY PORTFOLIO', 'LISIX', 'N/A', NOW()),
(429595, 'Allegiant Travel Co', 'ALGT', 'Industrials', NOW()),
(430030, 'Banco Bilbao Vizcaya Argentaria SA (BBVA)', 'BBVA', 'Financials', NOW()),
(431167, 'Mercedes-Benz Group AG', 'MBGYY', 'ConsumerDiscretionary', NOW()),
(431656, 'FIDELITY ADVISOR INTERNATIONAL CAPITAL APPRECIATION FUND', 'FCPIX', 'N/A', NOW()),
(432115, 'Grupo Financiero Banorte SA De CV Gfnorte', 'GBOOY', 'Financials', NOW()),
(432572, 'iShares Core MSCI Emerging Markets ETF', 'FIEMG', 'N/A', NOW()),
(433512, 'Murata Manufacturing Co Ltd', 'MRAAY', 'InformationTechnology', NOW()),
(435177, 'Telefonaktiebolaget LM Ericsson', 'ERIC', 'InformationTechnology', NOW()),
(2331363, 'Primo Water Corp', 'PRMW', 'ConsumerStaples', NOW()),
(2331999, 'Fidelity Covington Trust - Fidelity Quality Factor ETF', 'FFQAL', 'N/A', NOW()),
(2334023, 'PROSHARES MSCI EAFE DIV GRWR', 'REFAD', 'N/A', NOW()),
(2334292, 'RENTOKIL INITIAL PLC', 'LCRTO', 'Industrials', NOW()),
(2334528, 'WIRELESS TELECOM GROUP INC', 'NCWTT', 'InformationTechnology', NOW()),
(2335151, 'HYSTER YALE INC', 'INCHY', 'Industrials', NOW()),
(429714, 'Americold Realty Trust', 'COLD', 'RealEstate', NOW()),
(429960, 'AXIS Capital Holdings Ltd', 'AXS', 'Financials', NOW()),
(430412, 'Casey''s General Stores Inc.', 'CASY', 'ConsumerStaples', NOW()),
(431585, 'EVERGY Inc', 'EVRG', 'Utilities', NOW()),
(431712, 'First Industrial Realty Trust Inc', 'FR', 'RealEstate', NOW()),
(432108, 'Group 1 Automotive Inc', 'GPI', 'ConsumerDiscretionary', NOW()),
(432354, 'Ichor Holdings Ltd', 'ICHR', 'InformationTechnology', NOW()),
(432953, 'Landstar System Inc', 'LSTR', 'Industrials', NOW()),
(435186, 'Telstra Corporation Ltd', 'TLSYY', 'CommunicationServices', NOW()),
(435794, 'Washington Federal Inc', 'WAFD', 'Financials', NOW()),
(436011, 'Yum China Holdings Inc', 'YUMC', 'ConsumerDiscretionary', NOW()),
(2331130, 'FIDELITY FLOATING RATE HIGH INCOME FUND', 'FFRHX', 'N/A', NOW()),
(2333078, 'BioCryst Pharmaceuticals Inc', 'BCRX', 'Healthcare', NOW()),
(2333296, 'Digital World Acquisition Corp', 'DWAC', 'CommunicationServices', NOW()),
(2334162, 'PIMCO INVST GRADE CP BD ETF', 'FCORP', 'N/A', NOW()),
(2334279, 'KERRY GROUP PLC', 'KRYAY', 'ConsumerStaples', NOW()),
(2334319, 'SALMAR ASA', 'SALRY', 'ConsumerStaples', NOW()),
(2334384, 'THE ADVISORS INNER CIRCLE FUND WESTWOOD GLOBAL EQUITY FUND', 'WWGEX', 'N/A', NOW()),
(2334819, 'FIRST WATCH RESTAURA GRO INC', 'CFWRG', 'ConsumerDiscretionary', NOW()),
(2335152, 'YIELDMAX MSTR OPTION INCOME STRATEGY ETF', 'FMSTY', 'N/A', NOW()),
(429603, 'AllianceBernstein Holding LP', 'LPAB', 'Financials', NOW()),
(429851, 'ARTISAN INTERNATIONAL VALUE FUND', 'APDKX', 'N/A', NOW()),
(429968, 'BAE Systems PLC', 'BAESY', 'Industrials', NOW()),
(430100, 'Black Knight Inc', 'BKI', 'InformationTechnology', NOW()),
(430224, 'Bright Horizons Family Solutions Inc', 'BFAM', 'ConsumerDiscretionary', NOW()),
(430474, 'Century Casinos Inc', 'CNTY', 'ConsumerDiscretionary', NOW()),
(430551, 'CIE Generale Des Etablissements Michelin SA, Clermont-Ferrand', 'MGDDY', 'ConsumerDiscretionary', NOW()),
(431306, 'Diversey Holdings Ltd', 'DSEY', 'Materials', NOW()),
(431459, 'Emergent BioSolutions Inc', 'EBS', 'Healthcare', NOW()),
(431567, 'ETF Managers Trust - ETFMG Prime Cyber Security ETF', 'FHACK', 'N/A', NOW()),
(431972, 'GFL Environmental Inc', 'GFL', 'Industrials', NOW()),
(432339, 'Huntington Ingalls Industries Inc', 'HII', 'Industrials', NOW()),
(432617, 'iShares Trust - iShares Long-Term Corporate Bond ETF', 'FIGLB', 'N/A', NOW()),
(432888, 'Kingspan Group PLC', 'KGSPY', 'Industrials', NOW()),
(432932, 'Kulicke and Soffa Industries Inc', 'KLIC', 'InformationTechnology', NOW()),
(433273, 'Mazda Motor Corp', 'MZDAY', 'ConsumerDiscretionary', NOW()),
(433508, 'Muenchener Rueckversicherungs-Gesellschaft Aktiengesellschaft In Muenchen', 'MURGY', 'Financials', NOW()),
(433993, 'Pearson PLC', 'LCPSO', 'ConsumerDiscretionary', NOW()),
(434210, 'ProShares Short S&P500', 'SH', 'N/A', NOW()),
(434388, 'Reynolds American Inc', 'RAI', 'ConsumerStaples', NOW()),
(434637, 'SEI Investments Co', 'SEIC', 'Financials', NOW()),
(434742, 'SMART Global Holdings Inc', 'SGH', 'InformationTechnology', NOW()),
(435053, 'Sumitomo Mitsui Trust Holdings Inc', 'SUTNY', 'Financials', NOW()),
(435471, 'United Overseas Bank Ltd', 'UOVEY', 'Financials', NOW()),
(435623, 'Vanguard Scottsdale Funds Vanguard Long-Term Corporate Bond ETF', 'FVCLT', 'N/A', NOW()),
(436019, 'Zillow Group Inc', 'ZG', 'RealEstate', NOW()),
(2302654, 'SeaWorld Entertainment Inc', 'SEAS', 'ConsumerDiscretionary', NOW()),
(2332496, 'Bridgestone Corp', 'BRDCY', 'ConsumerDiscretionary', NOW()),
(2332917, 'SPDR S&P Global Natural Resources ETF', 'TFGNR', 'N/A', NOW()),
(2333490, 'Construction Partners Inc', 'ROAD', 'Industrials', NOW()),
(2333667, 'Franklin Templeton ETF Trust - Franklin FTSE United Kingdom ETF', 'FFLGB', 'N/A', NOW()),
(2334044, 'VIRTUS VONTOBEL FOREIGN OPPORTUNITIES FUND', 'JVIAX', 'N/A', NOW()),
(2334107, 'BLACKROCK 2037 MUNICIPAL TARGET TERM TRUST', 'BMN', 'N/A', NOW()),
(2334159, 'FEDERATED HRM SRT DUR HI ETF', 'FFHYS', 'N/A', NOW()),
(2334209, 'COHERUS ONCOLOGY INC', 'CCHRS', 'Healthcare', NOW()),
(2334291, 'RECRUIT HOLDINGS CO LTD', 'RCRUY', 'Industrials', NOW()),
(2334393, 'NATIONWIDE INTERNATIONAL SMALL CAP FUND', 'NWXVX', 'N/A', NOW()),
(2334452, 'CELLNEX TELECOM SA', 'CLLNY', 'CommunicationServices', NOW()),
(2334468, 'NEXPOINT RESIDENTIAL TR INC', 'CNXRT', 'RealEstate', NOW()),
(2334480, 'SEKISUI HOUSE LTD', 'SKHSY', 'ConsumerDiscretionary', NOW()),
(2334493, 'YAMAHA MOTOR CO LTD', 'YAMHY', 'ConsumerDiscretionary', NOW()),
(2334736, 'PACER DV MK IN CS CW 100 ETF', 'FICOW', 'N/A', NOW()),
(2334992, 'CREXENDO INC', 'CCXDO', 'InformationTechnology', NOW()),
(433610, 'NEW JERSEY ECONOMIC DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(433713, 'NORTHSIDE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433812, 'OKLAHOMA SCHOOL DISTRICTS', 'None', 'N/A', NOW()),
(433820, 'OLDHAM COUNTY SCHOOL DISTRICT FINANCE CORP', 'None', 'N/A', NOW()),
(434009, 'PENNSYLVANIA HOUSING FINANCE AGENCY', 'None', 'N/A', NOW()),
(434453, 'ROUND ROCK INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(434958, 'STATE OF GEORGIA', 'None', 'N/A', NOW()),
(434980, 'STATE OF NEW YORK MORTGAGE AGENCY', 'None', 'N/A', NOW()),
(434982, 'STATE OF NORTH CAROLINA', 'None', 'N/A', NOW()),
(435199, 'TENNESSEE HOUSING DEVELOPMENT AGENCY', 'None', 'N/A', NOW()),
(435230, 'TEXAS WATER DEVELOPMENT BOARD', 'None', 'N/A', NOW()),
(435496, 'UNIVERSITY OF CINCINNATI', 'None', 'N/A', NOW()),
(435501, 'UNIVERSITY OF MARYLAND', 'None', 'N/A', NOW()),
(435727, 'VIRGINIA RESOURCES AUTHORITY', 'None', 'N/A', NOW()),
(435946, 'W L GORE & ASSOCIATES INC', 'None', 'N/A', NOW()),
(436009, 'YSLETA INDEPENDENT SCHOOL DISTRICT EL PASO COUNTY TEXAS', 'None', 'N/A', NOW()),
(1311252, 'CSPC Pharmaceutical Group Ltd', 'None', 'Healthcare', NOW()),
(2314313, 'KATY INDEPENDENT SCHOOL DISTRICT FORT BEND HARRIS AND WALLER COUNTIES TEXAS', 'None', 'N/A', NOW()),
(2317519, 'WYOMING COMMUNITY DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(2331428, 'AB PRIVATE CREDIT INVESTORS CORP', 'None', 'N/A', NOW()),
(2331979, 'CITY OF FRISCO', 'None', 'N/A', NOW()),
(2333799, 'HOUSTON TEXAS AIRPORT SYSTEM', 'None', 'N/A', NOW()),
(2333804, 'METRO WASHINGTON AIRPORTS AUTH DC', 'None', 'N/A', NOW()),
(2333806, 'NEW HAMPSHIRE HOUSING FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(2333837, 'CITY OF LEANDER TEXAS', 'None', 'N/A', NOW()),
(2333899, 'TIGER GLOBAL CROSSOVER ACCESS LLC', 'None', 'N/A', NOW()),
(2333901, 'CAREBRIDGE', 'None', 'N/A', NOW()),
(2334169, 'STATE OF FLORIDA BOARD OF GOVERNORS', 'None', 'N/A', NOW()),
(2334171, 'INDUSTRIAL DEVELOPMENT AUTHORITY OF MOBILE COUNTY', 'None', 'N/A', NOW()),
(2334175, 'SEVEN BRIDGES STRATEGIC EQUITY FUND LP', 'None', 'N/A', NOW()),
(2334208, 'CONSOLIDATED SCHOOL DISTRICT OF AIKEN COUNTY', 'None', 'N/A', NOW()),
(2334301, 'SPOKANE SCHOOL DISTRICT NO 81 SPOKANE COUNTY WASHINGTON', 'None', 'N/A', NOW()),
(2334413, 'UBIQUITY VENTURES III', 'None', 'N/A', NOW()),
(2334499, 'DEL VALLE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334534, 'SCHOOL DISTRICT OF LEON COUNTY FLORIDA', 'None', 'N/A', NOW()),
(435101, 'Syneos Health Inc', 'XLV', 'Healthcare', NOW()),
(435130, 'Tandem Diabetes Care Inc', 'DIA', 'Healthcare', NOW()),
(435196, 'Tenet Healthcare Corp', 'XLV', 'Healthcare', NOW()),
(435824, 'Webster Financial Corp', 'XLF', 'Financials', NOW()),
(2334345, 'ENERGY TRANSFER OPERATING LP', 'XLE', 'N/A', NOW()),
(2334426, 'CME SOYBEAN OIL', 'USO', 'N/A', NOW()),
(2334511, 'SOFI TECHNOLOGIES INC', 'XLK', 'Financials', NOW()),
(433627, 'New Residential Investment Corp', 'RITM', 'Financials', NOW()),
(433634, 'New York Community Bancorp Inc', 'NYCB', 'Financials', NOW()),
(433667, 'Nippon Telegraph & Telephone Corp Ntt', 'NTTYY', 'CommunicationServices', NOW()),
(433670, 'Nitori Holdings Co Ltd', 'NCLTY', 'ConsumerDiscretionary', NOW()),
(433684, 'Nordea Bank Abp', 'NRDBY', 'Financials', NOW()),
(433733, 'NOV Inc', 'NOV', 'Energy', NOW()),
(433830, 'Ollie''s Bargain Outlet Holdings Inc', 'OLLI', 'ConsumerDiscretionary', NOW()),
(434043, 'PG&E Corp', 'PCG', 'Utilities', NOW()),
(434089, 'Ping An Insurance Group', 'PNGAY', 'Financials', NOW()),
(434175, 'Primoris Services Corp', 'PRIM', 'Industrials', NOW()),
(434281, 'QuantumScape Corp', 'QS', 'ConsumerDiscretionary', NOW()),
(434308, 'Range Resources Corp', 'RRC', 'Energy', NOW()),
(434355, 'Reinsurance Group of America Inc', 'RGA', 'Financials', NOW()),
(434357, 'Reliance Steel & Aluminum Co', 'RS', 'Materials', NOW()),
(434424, 'Roblox Corp', 'RBLX', 'CommunicationServices', NOW()),
(434474, 'RPM International Inc', 'RPM', 'Materials', NOW()),
(434495, 'Ryman Hospitality Properties Inc', 'RHP', 'RealEstate', NOW()),
(434703, 'Silgan Holdings Inc', 'SLGN', 'Materials', NOW()),
(434752, 'Smurfit Kappa Group PLC', 'SMFKY', 'Materials', NOW()),
(434849, 'SPDR MidCap 400 ETF Trust', 'MDY', 'N/A', NOW()),
(434863, 'SPDR S&P 600 Small Cap Value ETF', 'FSLYV', 'N/A', NOW()),
(434924, 'STAG Industrial Inc', 'STAG', 'RealEstate', NOW()),
(435285, 'Tokyo Electron Ltd', 'TOELY', 'InformationTechnology', NOW()),
(435381, 'Tri Pointe Homes Inc', 'TPH', 'ConsumerDiscretionary', NOW()),
(435452, 'Uni-Charm Corp', 'UNICY', 'ConsumerStaples', NOW()),
(435614, 'Vanguard Mid-Cap ETF', 'ETFVO', 'N/A', NOW()),
(435692, 'Viavi Solutions Inc', 'VIAV', 'InformationTechnology', NOW()),
(435752, 'Vontier Corp', 'VNT', 'InformationTechnology', NOW()),
(435807, 'Waste Connections Inc', 'WCN', 'Industrials', NOW()),
(435871, 'West Japan Railway Company', 'WJRYY', 'Industrials', NOW()),
(2331206, 'VANECK EMERGING MARKETS FUND', 'EMRIX', 'N/A', NOW()),
(2331365, 'Stellantis NV', 'VSTLA', 'ConsumerDiscretionary', NOW()),
(2332051, 'Arch Coal Inc', 'ARCH', 'Materials', NOW()),
(2332120, 'CBIZ Inc', 'CBZ', 'Industrials', NOW()),
(2332221, 'RH', 'RHRH', 'ConsumerDiscretionary', NOW()),
(2332432, 'Arlington Asset Investment Corp', 'AAIC', 'Financials', NOW()),
(2332605, 'Global X Uranium ETF', 'TFURA', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;