INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(435681, 'Vertex Pharmaceuticals Inc', 'VRTX', 'Healthcare', NOW()),
(429639, 'Altria Group Inc', 'MO', 'ConsumerStaples', NOW()),
(431879, 'Freeport-McMoRan Inc', 'FCX', 'Materials', NOW()),
(433773, 'NXP Semiconductors NV', 'VNXPI', 'InformationTechnology', NOW()),
(434825, 'CBOE SPX INDEX', 'EXSPX', 'N/A', NOW()),
(431316, 'Dollar Tree Inc', 'DLTR', 'ConsumerStaples', NOW()),
(431352, 'D.R. Horton Inc', 'DHI', 'ConsumerDiscretionary', NOW()),
(434429, 'Rockwell Automation Inc', 'ROK', 'Industrials', NOW()),
(430491, 'Charter Communications Inc', 'CHTR', 'CommunicationServices', NOW()),
(431135, 'CSX Corp', 'CSX', 'Industrials', NOW()),
(431372, 'DuPont  De Nemours Inc', 'DD', 'Materials', NOW()),
(435295, 'The Toronto-Dominion Bank', 'TD', 'Financials', NOW()),
(431262, 'DexCom Inc', 'DXCM', 'Healthcare', NOW()),
(432868, 'KeyCorp', 'KEY', 'Financials', NOW()),
(433147, 'LyondellBasell Industries NV', 'NVLYB', 'Materials', NOW()),
(434554, 'SAP SE', 'SESAP', 'InformationTechnology', NOW()),
(429569, 'Albemarle Corp', 'ALB', 'Materials', NOW()),
(429796, 'Aptiv PLC', 'CAPTV', 'ConsumerDiscretionary', NOW()),
(430944, 'Conagra Brands Inc', 'CAG', 'ConsumerStaples', NOW()),
(432274, 'Hilton Worldwide Holdings Inc', 'HLT', 'ConsumerDiscretionary', NOW()),
(432367, 'IDEXX Laboratories Inc', 'IDXX', 'Healthcare', NOW()),
(433434, 'Moderna Inc', 'MRNA', 'Healthcare', NOW()),
(433790, 'Occidental Petroleum Corp', 'OXY', 'Energy', NOW()),
(435473, 'United Rentals Inc', 'URI', 'Industrials', NOW()),
(432077, 'Graphic Packaging Holding Co', 'GPK', 'Materials', NOW()),
(432482, 'International Flavors & Fragrances Inc', 'IFF', 'Materials', NOW()),
(433493, 'MSCI Inc', 'MSCI', 'Financials', NOW()),
(431370, 'The Dun & Bradstreet Corp', 'DNB', 'Industrials', NOW()),
(434712, 'Simon Property Group Inc', 'SPG', 'RealEstate', NOW()),
(435122, 'Take-Two Interactive Software Inc', 'TTWO', 'CommunicationServices', NOW()),
(435529, 'Urban Outfitters Inc', 'URBN', 'ConsumerDiscretionary', NOW()),
(435886, 'Weyerhaeuser Co', 'WY', 'RealEstate', NOW()),
(429812, 'Archer-Daniels-Midland Co', 'ADM', 'ConsumerStaples', NOW()),
(429992, 'The Bank of New York Mellon Corp', 'BK', 'Financials', NOW()),
(430082, 'Biogen Inc', 'BIIB', 'Healthcare', NOW()),
(430399, 'CarMax Inc', 'KMX', 'ConsumerDiscretionary', NOW()),
(430827, 'The Clorox Co', 'CLX', 'ConsumerStaples', NOW()),
(432993, 'Lennar Corp', 'LEN', 'ConsumerDiscretionary', NOW()),
(433909, 'PACCAR Inc', 'PCAR', 'Industrials', NOW()),
(434004, 'Penn National Gaming Inc', 'PENN', 'ConsumerDiscretionary', NOW()),
(435477, 'United States Steel Corp', 'X', 'Materials', NOW()),
(429957, 'Axalta Coating Systems Ltd', 'AXTA', 'Materials', NOW()),
(429993, 'The Bank of Nova Scotia', 'BNS', 'Financials', NOW()),
(430093, 'BJ''s Wholesale Club Holdings Inc', 'BJ', 'ConsumerStaples', NOW()),
(430403, 'Carrier Global Corp', 'CARR', 'Industrials', NOW()),
(431375, 'Dynatrace Inc', 'DT', 'InformationTechnology', NOW()),
(431835, 'Fortive Corp', 'FTV', 'Industrials', NOW()),
(434278, 'Quanta Services Inc', 'PWR', 'Industrials', NOW()),
(435877, 'West Pharmaceutical Services Inc', 'WST', 'Healthcare', NOW()),
(430019, 'Bayer AG', 'BAYRY', 'Healthcare', NOW()),
(431282, 'Digital Realty Trust Inc', 'DLR', 'RealEstate', NOW()),
(429782, 'Apollo Global Management Inc', 'APO', 'Financials', NOW()),
(431002, 'CoStar Group Inc', 'CSGP', 'RealEstate', NOW()),
(432381, 'Illinois Tool Works Inc', 'ITW', 'Industrials', NOW()),
(432432, 'Ingersoll Rand Inc', 'IR', 'Industrials', NOW()),
(432543, 'Iqvia Holdings Inc', 'IQV', 'Healthcare', NOW()),
(432930, 'The Kroger Co', 'KR', 'ConsumerStaples', NOW()),
(434248, 'Public Storage', 'PSA', 'RealEstate', NOW()),
(435134, 'Tapestry Inc', 'TPR', 'ConsumerDiscretionary', NOW()),
(435166, 'TE Connectivity Ltd', 'TEL', 'InformationTechnology', NOW()),
(2331444, 'MillerKnoll Inc', 'MLKN', 'Industrials', NOW()),
(2334585, 'ISHARES MONTH TREAS BOND ETF', 'FSGOV', 'N/A', NOW()),
(2334903, 'DIREXION DAILY SMALL CAP BULL 3X ETF', 'TFTNA', 'N/A', NOW()),
(432900, 'KLA Corp', 'KLAC', 'InformationTechnology', NOW()),
(433712, 'Northrop Grumman Corp', 'NOC', 'Industrials', NOW()),
(434507, 'Safran SA', 'SAFRY', 'Industrials', NOW()),
(2333561, 'Block Inc', 'SQ', 'Financials', NOW()),
(430155, 'BNP Paribas', 'BNPQY', 'Financials', NOW()),
(430999, 'Corteva Inc', 'CTVA', 'Materials', NOW()),
(431648, 'Ferguson PLC', 'CFERG', 'Industrials', NOW()),
(431977, 'Gilead Sciences Inc', 'GILD', 'Healthcare', NOW()),
(2334051, 'STATE OF MASSACHUSETTS', 'None', 'N/A', NOW()),
(430922, 'COMMONWEALTH OF PENNSYLVANIA', 'None', 'N/A', NOW()),
(579351, 'OHIO WATER DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(431222, 'Dell Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(431367, 'Duke Energy Corp', 'XLE', 'Utilities', NOW()),
(432516, 'Invesco QQQ Trust Series 1', 'QQQ', 'N/A', NOW()),
(433439, 'Molina Healthcare Inc', 'XLV', 'Healthcare', NOW()),
(433653, 'NGL Energy Partners LP', 'XLE', 'Energy', NOW()),
(429528, 'Agilent Technologies Inc', 'XLK', 'Healthcare', NOW()),
(434446, 'Roper Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(432872, 'Keysight Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(434771, 'SolarEdge Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(434860, 'SPDR S&P 500 ETF Trust', 'SPY', 'N/A', NOW()),
(2334178, 'GE HEALTHCARE TECHNOLOGI INC', 'XLK', 'Healthcare', NOW()),
(429717, 'Ameriprise Financial Inc', 'XLF', 'Financials', NOW()),
(431260, 'Devon Energy Corp', 'XLE', 'Energy', NOW()),
(430355, 'Canadian Imperial Bank of Commerce', 'DIA', 'Financials', NOW()),
(430479, 'Ceridian HCM Holding Inc', 'DIA', 'Industrials', NOW()),
(432216, 'Healthpeak Properties Inc', 'XLV', 'RealEstate', NOW()),
(433513, 'Murphy Oil Corp', 'USO', 'Energy', NOW()),
(430086, 'Bio-Techne Corp', 'XLK', 'Healthcare', NOW()),
(431270, 'Diageo PLC', 'DIA', 'ConsumerStaples', NOW()),
(432290, 'Hologic Inc', 'HOLX', 'Healthcare', NOW()),
(433624, 'Newmont Corporation', 'NEM', 'Materials', NOW()),
(434171, 'T. Rowe Price Group Inc', 'TROW', 'Financials', NOW()),
(2334504, 'KENVUE INC', 'CKVUE', 'ConsumerStaples', NOW()),
(429760, 'ANSYS Inc', 'ANSS', 'InformationTechnology', NOW()),
(431548, 'Equity Residential', 'EQR', 'RealEstate', NOW()),
(432164, 'Harley-Davidson Inc', 'HOG', 'ConsumerDiscretionary', NOW())
ON CONFLICT (id) DO NOTHING;