INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(433181, 'MAINE MUNICIPAL BOND BANK', 'None', 'N/A', NOW()),
(433216, 'MARICOPA UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433246, 'MASSACHUSETTS BAY TRANSPORTATION AUTHORITY', 'None', 'N/A', NOW()),
(429609, 'Alliant Energy Corporation', 'XLE', 'Utilities', NOW()),
(430303, 'Coterra Energy Inc', 'XLE', 'Energy', NOW()),
(430356, 'Canadian National Railway Co', 'DIA', 'Industrials', NOW()),
(431761, 'First Trust North American Energy Infrastructure Fund', 'XLE', 'N/A', NOW()),
(432404, 'INDIANA FINANCE AUTHORITY', 'DIA', 'N/A', NOW()),
(432519, 'Invesco S&P 500 Equal Weight ETF', 'SPY', 'N/A', NOW()),
(432749, 'Jefferies Financial Group Inc', 'XLF', 'Financials', NOW()),
(432929, 'Krispy Kreme Inc', 'SPY', 'ConsumerDiscretionary', NOW()),
(433198, 'Manhattan Associates Inc', 'T', 'InformationTechnology', NOW()),
(433260, 'Mattel Inc', 'T', 'ConsumerDiscretionary', NOW()),
(435672, 'Veritex Holdings Inc', 'VBTX', 'Financials', NOW()),
(435720, 'Vinci SA', 'VCISY', 'Industrials', NOW()),
(435739, 'Vistra Corp', 'VST', 'Utilities', NOW()),
(435747, 'VMware Inc', 'VMW', 'InformationTechnology', NOW()),
(435814, 'Watsco Inc', 'WSO', 'Industrials', NOW()),
(435857, 'Western Asset Inflation-Linked Opportunities & Income Fund', 'WIW', 'N/A', NOW()),
(2331406, 'Koninklijke Ahold Delhaize NV', 'ADRNY', 'ConsumerStaples', NOW()),
(2331758, 'iShares 1-5 Year Investment Grade Corp Bond ETF', 'FIGSB', 'N/A', NOW()),
(2333597, 'Independence Realty Trust Inc', 'IRT', 'RealEstate', NOW()),
(2333864, 'THOUGHTWORKS HOLDG INC', 'CTWKS', 'InformationTechnology', NOW()),
(2333995, 'GEVO INC', 'CGEVO', 'Energy', NOW()),
(2334117, 'PIMCO 25 YR ZERO CPN US ETF', 'FZROZ', 'N/A', NOW()),
(2334357, 'UTZ BRANDS INC', 'NCUTZ', 'ConsumerStaples', NOW()),
(2334381, 'LORD ABBETT SHORT DURATION HIGH YIELD FUND', 'LSYIX', 'N/A', NOW()),
(2334398, 'EMERA INC', 'EMRAF', 'Utilities', NOW()),
(2334405, 'ACUREN CORP', 'PADMR', 'Industrials', NOW()),
(2334414, 'NATIONAL STORAGE AFFILIATES', 'ESNSA', 'RealEstate', NOW()),
(2334498, 'BONDBLOXX B O Y T D US T ETF', 'FXONE', 'N/A', NOW()),
(2334828, 'AMENTUM HOLDINGS INC', 'CAMTM', 'Industrials', NOW()),
(2334838, 'VAPOTHERM INC', 'CVAPO', 'Healthcare', NOW()),
(2334869, 'CADRE HOLDINGS INC', 'CCDRE', 'Industrials', NOW()),
(429493, 'Adidas AG', 'ADDYY', 'ConsumerDiscretionary', NOW()),
(429531, 'AGNC Investment Corp', 'AGNC', 'Financials', NOW()),
(429764, 'Antero Resources Corporation', 'AR', 'Energy', NOW()),
(429784, 'Apollo Medical Holdings Inc', 'AMEH', 'Healthcare', NOW()),
(429944, 'Avient Corp', 'AVNT', 'Materials', NOW()),
(429967, 'Badger Meter Inc', 'BMI', 'InformationTechnology', NOW()),
(430060, 'Berry Global Group Inc', 'BERY', 'Materials', NOW()),
(430256, 'Azenta Inc', 'AZTA', 'Healthcare', NOW()),
(430553, 'Ciena Corp', 'CIEN', 'InformationTechnology', NOW()),
(430914, 'Commerce Bancshares Inc', 'CBSH', 'Financials', NOW()),
(431089, 'Cousins Properties Incorporated', 'CUZ', 'RealEstate', NOW()),
(431102, 'Credicorp Ltd', 'BAP', 'Financials', NOW()),
(431127, 'Artivion Inc', 'AORT', 'Healthcare', NOW()),
(431249, 'Deutsche Bank AG', 'AGDB', 'Financials', NOW()),
(431530, 'Epiroc AB', 'EPOKY', 'Industrials', NOW()),
(431536, 'EQT Corp', 'EQT', 'Energy', NOW()),
(431919, 'Gaming and Leisure Properties Inc', 'GLPI', 'RealEstate', NOW()),
(432144, 'Halozyme Therapeutics Inc', 'HALO', 'Healthcare', NOW()),
(432252, 'Hess Corp', 'HES', 'Energy', NOW()),
(432292, 'Home Bancshares Inc', 'HOMB', 'Financials', NOW()),
(432391, 'Impinj Inc', 'PI', 'InformationTechnology', NOW()),
(432455, 'Insperity Inc', 'NSP', 'Industrials', NOW()),
(432579, 'iShares Core S&P Total U.S. Stock Market ETF', 'FITOT', 'N/A', NOW()),
(432747, 'JD.com Inc', 'JD', 'ConsumerDiscretionary', NOW()),
(432838, 'KB Home', 'KBH', 'ConsumerDiscretionary', NOW()),
(432896, 'Kite Realty Group Trust', 'KRG', 'RealEstate', NOW()),
(432947, 'Lamar Advertising Co', 'LAMR', 'RealEstate', NOW()),
(433202, 'ManpowerGroup Inc', 'MAN', 'Industrials', NOW()),
(433253, 'MasTec Inc', 'MTZ', 'Industrials', NOW()),
(433486, 'MPLX LP', 'PMPLX', 'Energy', NOW()),
(429929, 'AUTODESK Inc', 'ADSK', 'InformationTechnology', NOW()),
(435119, 'Taiwan Semiconductor Manufacturing Co Ltd', 'TSM', 'InformationTechnology', NOW()),
(430182, 'Boston Scientific Corp', 'BSX', 'Healthcare', NOW()),
(2334013, 'VANGUARD FEDERAL MONEY MARKET FUND', 'VMFXX', 'N/A', NOW()),
(435108, 'Synopsys Inc', 'SNPS', 'InformationTechnology', NOW()),
(434201, 'Prologis Inc', 'PLD', 'RealEstate', NOW()),
(431945, 'General Mills Inc', 'GIS', 'ConsumerStaples', NOW()),
(429550, 'Air Products and Chemicals Inc', 'APD', 'Materials', NOW()),
(432874, 'Kimberly-Clark Corp', 'KMB', 'ConsumerStaples', NOW()),
(435771, 'Walgreens Boots Alliance Inc', 'WBA', 'ConsumerStaples', NOW()),
(431433, 'Electronic Arts Inc', 'EA', 'CommunicationServices', NOW()),
(431462, 'Emerson Electric Co', 'EMR', 'Industrials', NOW()),
(435001, 'State Street Corporation', 'STT', 'Financials', NOW()),
(431265, 'DFA EMERGING MARKETS CORE EQUITY PORTFOLIO', 'DFCEX', 'N/A', NOW()),
(430328, 'Topgolf Callaway Brands Corp', 'MODG', 'ConsumerDiscretionary', NOW()),
(433854, 'ON Semiconductor Corp', 'ON', 'InformationTechnology', NOW()),
(433437, 'Mohawk Industries Inc', 'MHK', 'ConsumerDiscretionary', NOW()),
(431961, 'Genuine Parts Co', 'GPC', 'ConsumerDiscretionary', NOW()),
(429731, 'Amphenol Corp', 'APH', 'InformationTechnology', NOW()),
(2334687, 'SUPER MICRO COMPUTER INC', 'CSMCI', 'InformationTechnology', NOW()),
(2335008, 'TENABLE HOLDINGS INC', 'CTENB', 'InformationTechnology', NOW()),
(430545, 'Church & Dwight Co Inc', 'CHD', 'ConsumerStaples', NOW()),
(431148, 'Curtiss-Wright Corp', 'CW', 'Industrials', NOW()),
(430266, 'Brown-Forman Corp', 'A', 'ConsumerStaples', NOW()),
(431224, 'Delta Air Lines Inc', 'DAL', 'Industrials', NOW()),
(429482, 'Activision Blizzard Inc', 'ATVI', 'CommunicationServices', NOW()),
(435862, 'Western Digital Corp', 'WDC', 'InformationTechnology', NOW()),
(429663, 'American Airlines Group Inc', 'AAL', 'Industrials', NOW()),
(432578, 'iShares Core S&P Small-Cap ETF', 'TFIJR', 'N/A', NOW()),
(436010, 'YUM BRANDS  Inc', 'YUM', 'ConsumerDiscretionary', NOW()),
(436022, 'Zions Bancorporation National Association', 'ZION', 'Financials', NOW()),
(2333558, 'Robinhood Markets Inc', 'HOOD', 'Financials', NOW()),
(432017, 'GoDaddy Inc', 'GDDY', 'InformationTechnology', NOW()),
(429659, 'Ameren Corporation', 'AEE', 'Utilities', NOW()),
(431576, 'Etsy Inc', 'ETSY', 'ConsumerDiscretionary', NOW()),
(434125, 'Pool Corp', 'POOL', 'ConsumerDiscretionary', NOW())
ON CONFLICT (id) DO NOTHING;