INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(433083, 'Loews Corp', 'L', 'Financials', NOW()),
(433212, 'Marathon Petroleum Corp', 'MPC', 'Energy', NOW()),
(433543, 'National Grid PLC', 'LCNGG', 'Utilities', NOW()),
(434056, 'Phillips 66', 'PSX', 'Energy', NOW()),
(434410, 'Rio Tinto Group', 'RIO', 'Materials', NOW()),
(435009, 'Steel Dynamics Inc', 'STLD', 'Materials', NOW()),
(435013, 'Steris PLC', 'LCSTE', 'Healthcare', NOW()),
(435344, 'TransDigm Group Inc', 'TDG', 'Industrials', NOW()),
(435480, 'United Therapeutics Corp', 'UTHR', 'Healthcare', NOW()),
(435755, 'Vornado Realty Trust', 'VNO', 'RealEstate', NOW()),
(2269470, 'STMicroelectronics NV', 'NVSTM', 'InformationTechnology', NOW()),
(2334270, 'APPFOLIO INC', 'CAPPF', 'InformationTechnology', NOW()),
(2334412, 'FABRINET', 'NETFN', 'InformationTechnology', NOW()),
(429441, 'ABB Ltd', 'ABB', 'Industrials', NOW()),
(430484, 'Championx Corp', 'CHX', 'Energy', NOW()),
(430873, 'Coinbase Global Inc', 'COIN', 'Financials', NOW()),
(431390, 'Eastman Chemical Co', 'EMN', 'Materials', NOW()),
(432341, 'J.B. Hunt Transport Services Inc', 'JBHT', 'Industrials', NOW()),
(432726, 'Jacobs Engineering Group Inc', 'J', 'Industrials', NOW()),
(432818, 'Juniper Networks Inc', 'JNPR', 'InformationTechnology', NOW()),
(432988, 'Leidos Holdings Inc', 'LDOS', 'Industrials', NOW()),
(434568, 'Schlumberger Ltd', 'SLB', 'Energy', NOW()),
(435176, 'Teleflex Inc', 'TFX', 'Healthcare', NOW()),
(435194, 'Tencent Holdings LTD', 'TCEHY', 'CommunicationServices', NOW()),
(435275, 'The Timken Co', 'TKR', 'Industrials', NOW()),
(435593, 'Vanguard FTSE Developed Markets ETF', 'TFVEA', 'N/A', NOW()),
(435749, 'Vodafone Group Public Limited Company', 'VOD', 'CommunicationServices', NOW()),
(435878, 'WestRock Company', 'WRK', 'Materials', NOW()),
(2298434, 'Chart Industries Inc', 'GTLS', 'Industrials', NOW()),
(2333855, 'HUMACYTE INC', 'CHUMA', 'Healthcare', NOW()),
(2334224, 'CELSIUS HOLDINGS INC', 'CCELH', 'ConsumerStaples', NOW()),
(2334673, 'ARDMORE SHIPPING CORP', 'RPASC', 'Energy', NOW()),
(429513, 'Adyen N.V', 'ADYEY', 'Financials', NOW()),
(429514, 'AECOM', 'OMACM', 'Industrials', NOW()),
(429517, 'AerCap Holdings NV', 'NVAER', 'Industrials', NOW()),
(429755, 'Anheuser-Busch InBev SA/NV', 'NVBUD', 'ConsumerStaples', NOW()),
(430085, 'Bio-Rad Laboratories Inc', 'BIO', 'Healthcare', NOW()),
(430702, 'CITY OF MEMPHIS TENNESSEE', 'None', 'N/A', NOW()),
(431631, 'FEDERAL HOME LOAN BANKS', 'None', 'N/A', NOW()),
(432316, 'HOUSTON INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433613, 'NEW JERSEY HOUSING AND MORTGAGE FINANCE AGENCY', 'None', 'N/A', NOW()),
(434970, 'STATE OF MINNESOTA', 'None', 'N/A', NOW()),
(434976, 'STATE OF NEW JERSEY', 'None', 'N/A', NOW()),
(435928, 'WISCONSIN HOUSING AND ECONOMIC DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(2070399, 'STATE OF OHIO HIGHER EDUCATIONAL FACILITY', 'None', 'N/A', NOW()),
(2333391, 'VIRGINIA HOUSING DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(2334206, 'NEW WATER CAPITAL PARTNERS II LP', 'None', 'N/A', NOW()),
(2334570, 'AIX VENTURES FUND II LP', 'None', 'N/A', NOW()),
(429593, 'COUNTY OF ALLEGHANY PENNSYLVANIA', 'None', 'N/A', NOW()),
(430769, 'CITY OF TALLAHASSEE FLORIDA', 'None', 'N/A', NOW()),
(431020, 'COUNTY OF CLARK NEVADA', 'None', 'N/A', NOW()),
(431048, 'COUNTY OF MIAMI DADE', 'None', 'N/A', NOW()),
(431065, 'COUNTY OF PRINCE GEORGES MARYLAND', 'None', 'N/A', NOW()),
(431238, 'DEPARTMENT OF AIRPORTS OF THE CITY OF LOS ANGELES CALIFORNIA', 'None', 'N/A', NOW()),
(434007, 'PENNSYLVANIA HIGHER EDUCATIONAL FACILITIES AUTHORITY', 'None', 'N/A', NOW()),
(434997, 'STATE OF WEST VIRGINIA', 'None', 'N/A', NOW()),
(434998, 'STATE OF WISCONSIN', 'None', 'N/A', NOW()),
(2334235, 'ALLOCATE ALPHA FUND II LP', 'None', 'N/A', NOW()),
(430518, 'CHICAGO O''HARE AIRPORT', 'None', 'N/A', NOW()),
(431613, 'FAIRFAX COUNTY OF VIRGINIA', 'None', 'N/A', NOW()),
(432557, 'iShares Trust iShares 20 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(432576, 'iShares Core S&P 500 ETF', 'SPY', 'N/A', NOW()),
(435052, 'Sumitomo Mitsui Financial Group Inc', 'XLF', 'Financials', NOW()),
(435489, 'Universal Health Services Inc', 'XLV', 'Healthcare', NOW()),
(982285, 'Lumen Technologies Inc', 'XLK', 'CommunicationServices', NOW()),
(430509, 'Cheniere Energy Inc', 'XLE', 'Energy', NOW()),
(431489, 'ENERGY NORTHWEST', 'XLE', 'N/A', NOW()),
(432212, 'HealthEquity Inc', 'XLV', 'Healthcare', NOW()),
(433211, 'Marathon Oil Corp', 'USO', 'Energy', NOW()),
(2320240, 'Goldman Sachs Access Investment Grade Corporate Bond ETF', 'GLD', 'N/A', NOW()),
(2334875, 'CREDO TECH GROUP HOLDING LTD', 'XLK', 'InformationTechnology', NOW()),
(430912, 'Comerica Incorporated', 'CMA', 'Financials', NOW()),
(431125, 'Crown Holdings Inc', 'CCK', 'Materials', NOW()),
(431186, 'Darden Restaurants Inc', 'DRI', 'ConsumerDiscretionary', NOW()),
(431311, 'DocuSign Inc', 'DOCU', 'InformationTechnology', NOW()),
(431593, 'Exact Sciences Corporation', 'EXAS', 'Healthcare', NOW()),
(431956, 'Genmab A/S', 'SGMAB', 'Healthcare', NOW()),
(432508, 'Invesco Ltd', 'IVZ', 'Financials', NOW()),
(432784, 'Jones Lang LaSalle Inc', 'JLL', 'RealEstate', NOW()),
(433242, 'Masco Corporation', 'MAS', 'Industrials', NOW()),
(433725, 'Norwegian Cruise Line Holdings Ltd', 'NCLH', 'ConsumerDiscretionary', NOW()),
(434111, 'Plexus Corp', 'PLXS', 'InformationTechnology', NOW()),
(434418, 'RLI Corp', 'RLI', 'Financials', NOW()),
(434601, 'Science Applications International Corp', 'SAIC', 'Industrials', NOW()),
(434611, 'Seacoast Banking Corp of Florida', 'SBCF', 'Financials', NOW()),
(434719, 'Sirius XM Holdings Inc', 'SIRI', 'CommunicationServices', NOW()),
(435462, 'United Airlines Holdings Inc', 'UAL', 'Industrials', NOW()),
(435659, 'Veeva Systems Inc', 'VEEV', 'Healthcare', NOW()),
(2334495, 'LOUISIANA-PACIFIC CORP', 'RPLPX', 'Materials', NOW()),
(429503, 'Advanced Drainage Systems Inc', 'WMS', 'Industrials', NOW()),
(429520, 'The AES Corp', 'AES', 'Utilities', NOW()),
(429546, 'Air Lease Corp', 'AL', 'Industrials', NOW()),
(429563, 'ALASKA AIR GROUP Inc', 'ALK', 'Industrials', NOW()),
(429620, 'Alnylam Pharmaceuticals Inc', 'ALNY', 'Healthcare', NOW()),
(429674, 'American Electric Power Co Inc', 'AEP', 'Utilities', NOW()),
(430430, 'Cboe Global Markets Inc', 'CBOE', 'Financials', NOW()),
(431140, 'CTS Corp', 'CTS', 'InformationTechnology', NOW()),
(431195, 'DaVita Inc', 'DVA', 'Healthcare', NOW()),
(431323, 'Domino''s Pizza Inc', 'DPZ', 'ConsumerDiscretionary', NOW()),
(431584, 'Everest Re Group Ltd', 'RE', 'Financials', NOW()),
(431599, 'Expeditors International of Washington Inc', 'EXPD', 'Industrials', NOW()),
(431615, 'Fair Isaac Corporation', 'FICO', 'InformationTechnology', NOW()),
(432149, 'Hanesbrands Inc', 'HBI', 'ConsumerDiscretionary', NOW()),
(433056, 'Lions Gate Entertainment Corp', 'A', 'CommunicationServices', NOW()),
(433089, 'London Stock Exchange Group PLC', 'LDNXF', 'Financials', NOW()),
(433220, 'MarketAxess Holdings Inc', 'MKTX', 'Financials', NOW()),
(433307, 'Medpace Holdings Inc', 'MEDP', 'Healthcare', NOW()),
(433723, 'Northwest Natural Holding Co', 'NWN', 'Utilities', NOW()),
(433845, 'OneMain Holdings Inc', 'OMF', 'Financials', NOW()),
(434376, 'Restaurant Brands International Inc', 'QSR', 'ConsumerDiscretionary', NOW()),
(434656, 'Service Corp International', 'SCI', 'ConsumerDiscretionary', NOW()),
(434693, 'Siemens AG', 'SIEGY', 'Industrials', NOW()),
(435331, 'Toyota Motor Corp', 'TM', 'ConsumerDiscretionary', NOW()),
(435374, 'TriMas Corp', 'TRS', 'Materials', NOW()),
(435375, 'Trimble Inc', 'TRMB', 'InformationTechnology', NOW()),
(2331870, 'Axon Enterprise Inc', 'AXON', 'Industrials', NOW()),
(2333544, 'Haier Smart Home Co Ltd', 'HSHCY', 'ConsumerDiscretionary', NOW()),
(2333614, 'Equity LifeStyle Properties Inc', 'ELS', 'RealEstate', NOW()),
(2333905, 'FULL HOUSE RESORTS INC', 'NCFLL', 'ConsumerDiscretionary', NOW()),
(2334145, 'FRANKLIN FTSE JAPAN ETF', 'FFLJP', 'N/A', NOW()),
(2334836, 'INVESCO SHORT TERM TREAS ETF', 'FTBLL', 'N/A', NOW()),
(429711, 'American Water Works Company Inc', 'AWK', 'Utilities', NOW()),
(430397, 'The Carlyle Group Inc', 'CG', 'Financials', NOW()),
(431114, 'CRH PLC', 'LCCRH', 'Materials', NOW()),
(431342, 'Douglas Emmett Inc', 'DEI', 'RealEstate', NOW()),
(431512, 'Entergy corporation', 'ETR', 'Utilities', NOW()),
(431524, 'EOG Resources Inc', 'EOG', 'Energy', NOW()),
(432380, 'ILLINOIS STATE TOLL HIGHWAY AUTHORITY', 'None', 'N/A', NOW()),
(433615, 'NEW JERSEY STATE TURNPIKE AUTHORITY', 'None', 'N/A', NOW()),
(433639, 'NEW YORK STATE ENVIRONMENTAL FACILITIES CORP', 'None', 'N/A', NOW()),
(434137, 'PORTLAND WATER DISTRICT', 'None', 'N/A', NOW()),
(434588, 'SCHOOL DISTRICT OF PHILADELPHIA', 'None', 'N/A', NOW()),
(434792, 'SOUTH CAROLINA JOBS ECONOMIC DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(434965, 'STATE OF LOUISIANA', 'None', 'N/A', NOW()),
(435774, 'WALLEYE CAPITAL PARTNERS LP', 'None', 'N/A', NOW()),
(435800, 'WASHINGTON SUBURBAN SANITARY DISTRICT', 'None', 'N/A', NOW()),
(1996993, 'SAN ANTONIO TEXAS ELECTRICITY & GAS', 'None', 'N/A', NOW()),
(2331176, 'COMMODORE CAPITAL DOMESTIC LP', 'None', 'N/A', NOW()),
(2333898, 'ELT ASSOCIATES LLC', 'None', 'N/A', NOW()),
(2334199, 'SPRING INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334430, 'BDT CAPITAL PARTNERS FUND 4 LP', 'None', 'N/A', NOW()),
(2334625, 'RECURRING CAPITAL FUND IV LP', 'None', 'N/A', NOW()),
(2334640, 'MYNO CARBON CORP', 'None', 'N/A', NOW()),
(2334824, 'LINCOLN GAINE LLC', 'None', 'N/A', NOW()),
(2334866, 'BROKEDOWN PALACE LTD', 'None', 'N/A', NOW()),
(430620, 'CITY OF CINCINNATI', 'None', 'N/A', NOW()),
(430676, 'CITY OF JACKSONVILLE FLORIDA', 'None', 'N/A', NOW()),
(431013, 'COUNTY OF BROWARD FLORIDA AIRPORT SYSTEM REVENUE', 'None', 'N/A', NOW()),
(432169, 'HARRIS COUNTY CULTURAL EDUCATION FACILITIES FINANCE CORP', 'None', 'N/A', NOW()),
(432417, 'INDUSTRIAL DEVELOPMENT AUTHORITY OF WISE COUNTY', 'None', 'N/A', NOW()),
(433214, 'MARICOPA COUNTY ARIZONA', 'None', 'N/A', NOW()),
(433249, 'MASSACHUSETTS DEVELOPMENT FINANCE AGENCY', 'None', 'N/A', NOW()),
(433630, 'NEW YORK CITY HOUSING DEVELOPMENT CORP', 'None', 'N/A', NOW()),
(433642, 'NEW YORK STATE URBAN DEVELOPMENT CORP', 'None', 'N/A', NOW()),
(432421, 'Infineon Technologies AG', 'XLK', 'InformationTechnology', NOW()),
(432562, 'iShares 7-10 Year Treasury Bond ETF', '^TNX', 'N/A', NOW()),
(432647, 'iShares Russell 1000 Growth ETF', 'IWM', 'N/A', NOW()),
(432964, 'Lattice Semiconductor Corporation', 'T', 'InformationTechnology', NOW()),
(433787, 'Chord Energy Corp', 'XLE', 'Energy', NOW()),
(434461, 'Royal Gold Inc', 'GLD', 'Materials', NOW()),
(435109, 'Synovus Financial Corp', 'XLF', 'Financials', NOW()),
(435421, 'Twilio Inc', 'TWLO', 'InformationTechnology', NOW()),
(435757, 'Voya Financial Inc', 'XLF', 'Financials', NOW()),
(435825, 'WEC Energy Group Inc', 'XLE', 'Utilities', NOW()),
(2332351, 'BioNTech SE', 'XLK', 'Healthcare', NOW()),
(2334346, 'NEXTERA ENERGY CAPITAL HOLDINGS INC', 'XLE', 'N/A', NOW()),
(2334877, 'OUNZ VAN ECK GOLD TRUST ETF', 'GLD', 'N/A', NOW()),
(429908, 'Atmos Energy Corp', 'XLE', 'Utilities', NOW()),
(430759, 'CITY OF SEATTLE', 'T', 'N/A', NOW()),
(430838, 'CMS Energy Corp', 'XLE', 'Utilities', NOW()),
(431363, 'DTE Energy Co', 'XLE', 'Utilities', NOW()),
(431947, 'General Motors Financial Co Inc', 'XLF', 'Financials', NOW()),
(432438, 'Inland Real Estate Income Trust Inc', 'VNQ', 'RealEstate', NOW()),
(432661, 'iShares S&P 500 Growth ETF', 'SPY', 'N/A', NOW()),
(431620, 'Fanuc Corp', 'FANUY', 'Industrials', NOW()),
(432012, 'Globus Medical Inc', 'GMED', 'Healthcare', NOW()),
(432329, 'HubSpot Inc', 'HUBS', 'InformationTechnology', NOW()),
(432620, 'iShares MSCI EAFE ETF', 'TFEFA', 'N/A', NOW()),
(432972, 'Bath & Body Works Inc', 'BBWI', 'ConsumerDiscretionary', NOW()),
(433298, 'Medical Properties Trust Inc', 'MPW', 'RealEstate', NOW()),
(433663, 'Nintendo Co Ltd', 'NTDOY', 'CommunicationServices', NOW()),
(433682, 'Nokia Corp', 'NOK', 'InformationTechnology', NOW()),
(433837, 'Omnicom Group Inc', 'OMC', 'CommunicationServices', NOW()),
(434112, 'Plug Power Inc', 'PLUG', 'Industrials', NOW()),
(434570, 'Schneider Electric SA', 'SBGSY', 'Industrials', NOW()),
(434599, 'Schwab US TIPS ETF', 'FSCHP', 'N/A', NOW()),
(434854, 'SPDR Portfolio Developed World ex-US ETF', 'FSPDW', 'N/A', NOW()),
(434858, 'SPDR S&P 400 Mid Cap Growth ETF', 'FMDYG', 'N/A', NOW()),
(434862, 'SPDR S&P 600 Small Cap Growth ETF', 'FSLYG', 'N/A', NOW()),
(435113, 'Sysmex Corp', 'SSMXY', 'Healthcare', NOW()),
(2294106, 'Kilroy Realty Corp', 'KRC', 'RealEstate', NOW()),
(2331057, 'Ares Management Corp', 'ARES', 'Financials', NOW()),
(2334078, 'ChargePoint Holdings Inc', 'CHPT', 'Industrials', NOW()),
(2334203, 'ATKORE INC', 'CATKR', 'Industrials', NOW()),
(2334389, 'CROSS TIMBERS ROYALTY TRUST', 'STCRT', 'Energy', NOW()),
(2334710, 'SOLVENTUM CORP', 'PSOLV', 'Healthcare', NOW()),
(429533, 'Agree Realty Corp', 'ADC', 'RealEstate', NOW()),
(429597, 'Allegro Microsystems Inc', 'ALGM', 'InformationTechnology', NOW()),
(429613, 'Allianz SE', 'ALIZY', 'Financials', NOW()),
(429651, 'Ambev SA', 'AABEV', 'ConsumerStaples', NOW())
ON CONFLICT (id) DO NOTHING;