INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(430585, 'CITY OF ANKENY IOWA', 'None', 'N/A', NOW()),
(430648, 'CITY OF FORT SMITH ARKANSAS', 'None', 'N/A', NOW()),
(430686, 'CITY OF LAREDO TEXAS', 'None', 'N/A', NOW()),
(430700, 'CITY OF MCKINNEY', 'None', 'N/A', NOW()),
(430707, 'CITY OF MILWAUKEE WISCONSIN', 'None', 'N/A', NOW()),
(430734, 'CITY OF PORTLAND OREGON', 'None', 'N/A', NOW()),
(430737, 'CITY OF RALEIGH NORTH CAROLINA', 'None', 'N/A', NOW()),
(430750, 'CITY OF SAN JOSE', 'None', 'N/A', NOW()),
(430762, 'CITY OF SPOKANE WASHINGTON', 'None', 'N/A', NOW()),
(430763, 'CITY OF STOCKTON SAN JOAQUIN COUNTY CALIFORNIA', 'None', 'N/A', NOW()),
(430764, 'CITY OF ST PETERSBURG FLORIDA', 'None', 'N/A', NOW()),
(430771, 'CITY OF TEMPLE TEXAS', 'None', 'N/A', NOW()),
(430774, 'CITY OF TOLEDO OHIO', 'None', 'N/A', NOW()),
(430793, 'CITY OF WINSTON SALEM NORTH CAROLINA', 'None', 'N/A', NOW()),
(430802, 'CLARK COUNTY NEVADA SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430817, 'CLEAR CREEK INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430845, 'COAST COMMUNITY COLLEGE DISTRICT', 'None', 'N/A', NOW()),
(430891, 'COLORADO SPRINGS COLO UTILS REV', 'None', 'N/A', NOW()),
(431018, 'COUNTY OF CHESTER', 'None', 'N/A', NOW()),
(431038, 'COUNTY OF LAKE', 'None', 'N/A', NOW()),
(431044, 'COUNTY OF MARIN', 'None', 'N/A', NOW()),
(431052, 'COUNTY OF MONTGOMERY MARYLAND', 'None', 'N/A', NOW()),
(431056, 'COUNTY OF NASSAU NEW YORK', 'None', 'N/A', NOW()),
(431060, 'COUNTY OF ORANGE CALIFORNIA', 'None', 'N/A', NOW()),
(431069, 'COUNTY OF RIVERSIDE CALIFORNIA', 'None', 'N/A', NOW()),
(431082, 'COUNTY OF WAKE NORTH CAROLINA', 'None', 'N/A', NOW()),
(431116, 'CRISPR Therapeutics AG', 'None', 'Healthcare', NOW()),
(431173, 'DALLAS AREA RAPID TRANSIT', 'None', 'N/A', NOW()),
(431174, 'DALLAS COUNTY HOSPITAL DISTRICT', 'None', 'N/A', NOW()),
(431209, 'Deere (John) Capital Corp', 'None', 'Financials', NOW()),
(431216, 'DELAWARE COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(431337, 'DOUGLAS COUNTY GEORGIA', 'None', 'N/A', NOW()),
(431365, 'DUBLIN UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431383, 'EAST BAY MUNICIPAL UTILITY DISTRICT', 'None', 'N/A', NOW()),
(431432, 'Electrolux AB', 'None', 'ConsumerDiscretionary', NOW()),
(431445, 'EL PASO COUNTY TEXAS', 'None', 'N/A', NOW()),
(431577, 'euNetworks Group Ltd', 'None', 'CommunicationServices', NOW()),
(431795, 'FLORIDA DEPARTMENT OF TRANSPORTATION', 'None', 'N/A', NOW()),
(431813, 'FOLSOM CORDOVA UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431826, 'FORNEY INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(431847, 'FOXTROT VENTURES INC', 'None', 'N/A', NOW()),
(430809, 'Clean Energy Fuels Corp', 'XLE', 'Energy', NOW()),
(431294, 'Direxion Daily Financial Bull 3X', 'XLF', 'N/A', NOW()),
(431591, 'Evoqua Water Technologies Corp', 'XLK', 'Industrials', NOW()),
(431673, 'Fidelity Nasdaq Composite Index ETF', 'QQQ', 'N/A', NOW()),
(431736, 'First Trust MLP and Energy Income Fund', 'XLE', 'N/A', NOW()),
(431739, 'First Trust NASDAQ-100 Technology Sector Index Fund', 'XLK', 'N/A', NOW()),
(431897, 'FuelCell Energy Inc', 'XLE', 'Industrials', NOW()),
(432003, 'Global X FinTech ETF', 'XLK', 'N/A', NOW()),
(432033, 'GOLDMAN SACHS FS GOVERNMENT FUND', 'GLD', 'N/A', NOW()),
(432034, 'GOLDMAN SACHS GQG PARTNERS INTERNATIONAL OPPORTUNITIES FUND', 'GLD', 'N/A', NOW()),
(430857, 'Cochlear Ltd', 'CHEOY', 'Healthcare', NOW()),
(430866, 'Cohen & Steers Inc', 'CNS', 'Financials', NOW()),
(430913, 'Comfort Systems USA Inc', 'FIX', 'Industrials', NOW()),
(430940, 'Compass Minerals International Inc', 'CMP', 'Materials', NOW()),
(430970, 'Continental Resources Inc', 'CLR', 'Energy', NOW()),
(431008, 'Coty Inc', 'COTY', 'ConsumerStaples', NOW()),
(431087, 'Coupa Software Inc', 'COUP', 'InformationTechnology', NOW()),
(431099, 'Crane Co', 'CR', 'Industrials', NOW()),
(431112, 'Crestwood Equity Partners LP', 'PCEQP', 'Energy', NOW()),
(431128, 'Cryoport Inc', 'CYRX', 'Healthcare', NOW()),
(431163, 'Daifuku Co Ltd', 'DFKCY', 'Industrials', NOW()),
(431168, 'Dai Nippon Printing Co Ltd', 'DNPLY', 'Industrials', NOW()),
(431184, 'Danone SA', 'DANOY', 'ConsumerStaples', NOW()),
(431215, 'DELAWARE CORPORATE BOND FUND', 'DGCAX', 'N/A', NOW()),
(431217, 'DELAWARE SMALL CAP CORE FUND', 'DCCIX', 'N/A', NOW()),
(431231, 'Denso Corp', 'DNZOY', 'ConsumerDiscretionary', NOW()),
(431250, 'Deutsche Boerse AG', 'DBOEY', 'Financials', NOW()),
(431332, 'Dorman Products Inc', 'DORM', 'ConsumerDiscretionary', NOW()),
(431348, 'DraftKings Inc', 'DKNG', 'ConsumerDiscretionary', NOW()),
(431368, 'Duke Realty Corp', 'DRE', 'RealEstate', NOW()),
(431411, 'EDGEWOOD GROWTH FUND', 'EGFIX', 'N/A', NOW()),
(431414, 'Editas Medicine Inc', 'EDIT', 'Healthcare', NOW()),
(431416, 'EDP-Energias de Portugal SA', 'EDPFY', 'Utilities', NOW()),
(431437, 'Element Solutions Inc', 'ESI', 'Materials', NOW()),
(431453, 'Embraer SA', 'SAERJ', 'Industrials', NOW()),
(431466, 'Empire State Realty Trust Inc', 'ESRT', 'RealEstate', NOW()),
(431470, 'Enanta Pharmaceuticals Inc', 'ENTA', 'Healthcare', NOW()),
(431533, 'EPR Properties', 'EPR', 'RealEstate', NOW()),
(431550, 'Erie Indemnity Co', 'ERIE', 'Financials', NOW()),
(431557, 'Essential Properties Realty Trust Inc', 'EPRT', 'RealEstate', NOW()),
(431581, 'Everbridge Inc', 'EVBG', 'InformationTechnology', NOW()),
(431635, 'Federal National Mortgage Association', 'FNMA', 'Financials', NOW()),
(431696, 'First BanCorp (Puerto Rico)', 'FBP', 'Financials', NOW()),
(431720, 'First Pacific Co Ltd', 'FPAFY', 'ConsumerStaples', NOW()),
(431756, 'First Trust Indxx NextG ETF', 'FNXTG', 'N/A', NOW()),
(431880, 'Fresenius Medical Care AG &Co KGAA', 'AAFMS', 'Healthcare', NOW()),
(431898, 'Fujifilm Holdings Corp', 'FUJIY', 'InformationTechnology', NOW()),
(431918, 'GameStop Corp', 'GME', 'ConsumerDiscretionary', NOW()),
(431923, 'Gap Inc', 'GPS', 'ConsumerDiscretionary', NOW()),
(431968, 'Getinge AB', 'GNGBY', 'Healthcare', NOW()),
(431982, 'Glacier Bancorp Inc', 'GBCI', 'Financials', NOW()),
(432170, 'HARRIS COUNTY FLOOD CONTROL DISTRICT', 'None', 'N/A', NOW()),
(432269, 'HILLSBOROUGH COUNTY FLORIDA', 'None', 'N/A', NOW()),
(432363, 'IDAHO STATE BUILDING AUTHORITY', 'None', 'N/A', NOW()),
(432750, 'JEFFERSON COUNTY TEXAS', 'None', 'N/A', NOW()),
(432827, 'KANSAS DEVELOPMENT FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(432962, 'LAS VEGAS VALLEY WATER DISTRICT', 'None', 'N/A', NOW()),
(433002, 'LEWIS AND CLARK COUNTY', 'None', 'N/A', NOW()),
(433005, 'LEWISVILLE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;