INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(2334860, 'EQV VENTURES ACQN CORP -REDH', 'DHEQV', 'N/A', NOW()),
(2334870, 'TEMPUS AI INC', 'NCTEM', 'Healthcare', NOW()),
(2334934, 'SIMCORP A/S', 'SMCYY', 'InformationTechnology', NOW()),
(2334966, 'TRADEWEB MARKETS INC', 'INCTW', 'Financials', NOW()),
(2334967, 'MITSUBISHI HEAVY INDUST LTD', 'MHVIY', 'Industrials', NOW()),
(2334968, 'UNICREDIT SPA', 'UNCRY', 'Financials', NOW()),
(2334976, 'INNOVIVA INC', 'CINVA', 'Healthcare', NOW()),
(2335003, 'ARIZONA GAME AND FISH DEPARTMENT', 'None', 'N/A', NOW()),
(2335005, 'RCP DIRECT V', 'None', 'N/A', NOW()),
(2335013, 'NORTHAMPTON BORO PENNSYLVANIA', 'None', 'N/A', NOW()),
(2335090, 'CYTOKINETICS INC', 'None', 'Healthcare', NOW()),
(2335092, 'EMPLOYERS HOLDINGS INC', 'None', 'Financials', NOW()),
(2335093, 'FRANKLIN BSP REALTY TRUST IN', 'None', 'Financials', NOW()),
(2335094, 'HILLTOP HOLDINGS INC', 'None', 'Financials', NOW()),
(2335095, 'L''ANSE CREUSE PUBLIC SCHOOLS COUNTY OF MACOMB STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(2335101, 'SOUTHSIDE BANCSHARES INC', 'None', 'Financials', NOW()),
(2335105, 'ROMEO COMMUNITY SCHOOLS', 'None', 'N/A', NOW()),
(2335106, 'CITY OF GRANDVILLE MICHIGAN', 'None', 'N/A', NOW()),
(2335160, 'COREWEAVE INC', 'None', 'InformationTechnology', NOW()),
(429486, 'ADAMS 12 FIVE STAR SCHOOLS COLORADO', 'None', 'N/A', NOW()),
(429559, 'ALABAMA PUBLIC SCHOOL AND COLLEGE AUTHORITY', 'None', 'N/A', NOW()),
(429611, 'ALLIANT HOLDINGS LP', 'None', 'N/A', NOW()),
(429838, 'ARLINGTON HIGHER EDUCATION FINANCE CORP', 'None', 'N/A', NOW()),
(430017, 'BAY AREA TOLL AUTHORITY', 'None', 'N/A', NOW()),
(430054, 'BERGEN COUNTY NEW JERSEY', 'None', 'N/A', NOW()),
(430153, 'BMO HARRIS BANK NA', 'None', 'N/A', NOW()),
(430275, 'BUCKEYE CENTRAL LOCAL SCHOOL DISTRICT OHIO', 'None', 'N/A', NOW()),
(430295, 'BUTLER COUNTY OHIO', 'None', 'N/A', NOW()),
(430338, 'CAMBRIAN SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(430398, 'CARMAN AINSWORTH COMMUNITY SCHOOLS COUNTY OF GENESEE STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(430465, 'CENTRAL KITSAP SCHOOL DISTRICT NO 401 KITSAP COUNTY WASHINGTON', 'None', 'N/A', NOW()),
(430511, 'CHEROKEE COUNTY SCHOOL SYSTEM', 'None', 'N/A', NOW()),
(2335059, 'SPDR DOW JONES INDUSTRIAL AVERAGE ETF TRUST', 'DIA', 'N/A', NOW()),
(2335086, 'BEACON FINANCIAL CORP', 'XLF', 'Financials', NOW()),
(2335102, 'VIPER ENERGY INC', 'XLE', 'Energy', NOW()),
(429460, 'Acadia Healthcare Co Inc', 'XLV', 'Healthcare', NOW()),
(430143, 'Bloom Energy Corp', 'XLE', 'Industrials', NOW()),
(430510, 'Cheniere Energy Partners LP', 'XLE', 'Energy', NOW()),
(430512, 'Chesapeake Energy Corp', 'XLE', 'Energy', NOW()),
(432045, 'GOLDMAN SACHS SMALL MID CAP GROWTH FUND', 'GLD', 'N/A', NOW()),
(2335000, 'INVESCO CURRENCYSHARES SWISS FRANC TRUST', 'STFXF', 'N/A', NOW()),
(2335077, 'ARM HOLDINGS PLC', 'LCARM', 'InformationTechnology', NOW()),
(2335119, 'BLUE OWL CAPITAL INC', 'NCOWL', 'Financials', NOW()),
(429440, 'ABBEY CAPITAL FUTURES STRATEGY FUND', 'ABYAX', 'N/A', NOW()),
(429453, 'ABIOMED Inc', 'ABMD', 'Healthcare', NOW()),
(429456, 'ABN AMRO Bank NV', 'AAVMY', 'Financials', NOW()),
(429477, 'ACI Worldwide Inc', 'ACIW', 'InformationTechnology', NOW()),
(429490, 'Adecco Group AG', 'AHEXY', 'Industrials', NOW()),
(429543, 'Airbus SE', 'EADSY', 'Industrials', NOW()),
(429557, 'Akzo Nobel NV', 'AKZOY', 'Materials', NOW()),
(429602, 'ALLETE Inc', 'ALE', 'Utilities', NOW()),
(429628, 'ALPS Alerian MLP ETF', 'FAMLP', 'N/A', NOW()),
(429643, 'Amadeus IT Group SA', 'AMADY', 'ConsumerDiscretionary', NOW()),
(429652, 'AMC Networks Inc', 'AMCX', 'CommunicationServices', NOW()),
(429665, 'American Assets Trust Inc', 'AAT', 'RealEstate', NOW()),
(429718, 'AMERISAFE Inc', 'AMSF', 'Financials', NOW()),
(429728, 'AMG YACKTMAN FUND', 'YACKX', 'N/A', NOW()),
(429750, 'The Andersons Inc', 'ANDE', 'ConsumerStaples', NOW()),
(429753, 'Anglo American PLC', 'NGLOY', 'Materials', NOW()),
(429779, 'A.P. Moller - Maersk A/S', 'AMKBY', 'Industrials', NOW()),
(429813, 'Archrock Inc', 'AROC', 'Energy', NOW()),
(429833, 'Arkema', 'ARKAY', 'Materials', NOW()),
(429855, 'Asahi Kasei Corp', 'AHKSY', 'Materials', NOW()),
(429871, 'Aspen Insurance Holdings Ltd', 'AHL', 'Financials', NOW()),
(429880, 'Assured Guaranty Ltd', 'AGO', 'Financials', NOW()),
(429896, 'Athene Holding Ltd', 'ATH', 'Financials', NOW()),
(429900, 'Atlantica Sustainable Infrastructure PLC', 'PLCAY', 'Utilities', NOW()),
(429937, 'Avangrid Inc', 'AGR', 'Utilities', NOW()),
(429945, 'Avis Budget Group Inc', 'CAR', 'Industrials', NOW()),
(429946, 'Aviva PLC', 'AVVIY', 'Financials', NOW()),
(429969, 'Baidu Inc', 'BIDU', 'CommunicationServices', NOW()),
(429972, 'Baker Hughes Inc', 'BHI', 'Energy', NOW()),
(429974, 'Balchem Corp', 'BCPC', 'Materials', NOW()),
(429977, 'Ballard Power Systems Inc', 'BLDP', 'Industrials', NOW()),
(429989, 'Bank of Hawaii Corp', 'BOH', 'Financials', NOW()),
(430101, 'BlackLine Inc', 'BL', 'InformationTechnology', NOW()),
(430141, 'Block H&R Inc', 'HRB', 'ConsumerDiscretionary', NOW()),
(430162, 'BOC Hong Kong (Holdings) Ltd', 'BHKLY', 'Financials', NOW()),
(430203, 'Brambles Ltd', 'BXBLY', 'Industrials', NOW()),
(430215, 'BRIDGE BUILDER CORE BOND FUND', 'BBTBX', 'N/A', NOW()),
(430216, 'BRIDGE BUILDER CORE PLUS BOND FUND', 'BBCPX', 'N/A', NOW()),
(430218, 'BRIDGE BUILDER LARGE CAP VALUE FUND', 'BBVLX', 'N/A', NOW()),
(430236, 'The British Land Co PLC', 'BTLCY', 'RealEstate', NOW()),
(430237, 'Brixmor Property Group Inc', 'BRX', 'RealEstate', NOW()),
(430253, 'Brookfield Renewable Corp', 'BEPC', 'Utilities', NOW()),
(430262, 'BROWN ADVISORY SUSTAINABLE GROWTH FUND', 'BAWAX', 'N/A', NOW()),
(430286, 'Burberry Group PLC', 'BURBY', 'ConsumerDiscretionary', NOW()),
(430287, 'Bureau Veritas SA', 'BVVBY', 'Industrials', NOW()),
(430300, 'C3.ai Inc', 'AI', 'InformationTechnology', NOW()),
(430335, 'CALVERT SMALL CAP FUND', 'CCVAX', 'N/A', NOW()),
(430336, 'CALVERT US LARGE CAP VALUE RESPONSIBLE INDEX', 'CFJAX', 'N/A', NOW()),
(430386, 'CareDx Inc', 'CDNA', 'Healthcare', NOW()),
(430410, 'Carvana Co', 'CVNA', 'ConsumerDiscretionary', NOW()),
(430411, 'Casella Waste Systems Inc', 'CWST', 'Industrials', NOW()),
(430424, 'Cathay General Bancorp', 'CATY', 'Financials', NOW()),
(430443, 'Cedar Fair LP', 'LPFUN', 'ConsumerDiscretionary', NOW()),
(430539, 'Choice Hotels International Inc', 'CHH', 'ConsumerDiscretionary', NOW()),
(430548, 'Chuy''s Holdings Inc', 'CHUY', 'ConsumerDiscretionary', NOW()),
(430581, 'CITY OF AKRON OHIO', 'None', 'N/A', NOW()),
(430583, 'CITY OF AMES IOWA', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;