INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(435053, 'Sumitomo Mitsui Trust Holdings Inc', 'SUTNY', 'Financials', NOW()),
(435471, 'United Overseas Bank Ltd', 'UOVEY', 'Financials', NOW()),
(435623, 'Vanguard Scottsdale Funds Vanguard Long-Term Corporate Bond ETF', 'FVCLT', 'N/A', NOW()),
(436019, 'Zillow Group Inc', 'ZG', 'RealEstate', NOW()),
(2302654, 'SeaWorld Entertainment Inc', 'SEAS', 'ConsumerDiscretionary', NOW()),
(2332496, 'Bridgestone Corp', 'BRDCY', 'ConsumerDiscretionary', NOW()),
(2332917, 'SPDR S&P Global Natural Resources ETF', 'TFGNR', 'N/A', NOW()),
(2333490, 'Construction Partners Inc', 'ROAD', 'Industrials', NOW()),
(2333667, 'Franklin Templeton ETF Trust - Franklin FTSE United Kingdom ETF', 'FFLGB', 'N/A', NOW()),
(2334044, 'VIRTUS VONTOBEL FOREIGN OPPORTUNITIES FUND', 'JVIAX', 'N/A', NOW()),
(2334107, 'BLACKROCK 2037 MUNICIPAL TARGET TERM TRUST', 'BMN', 'N/A', NOW()),
(2334159, 'FEDERATED HRM SRT DUR HI ETF', 'FFHYS', 'N/A', NOW()),
(2334209, 'COHERUS ONCOLOGY INC', 'CCHRS', 'Healthcare', NOW()),
(2334291, 'RECRUIT HOLDINGS CO LTD', 'RCRUY', 'Industrials', NOW()),
(2334393, 'NATIONWIDE INTERNATIONAL SMALL CAP FUND', 'NWXVX', 'N/A', NOW()),
(2334452, 'CELLNEX TELECOM SA', 'CLLNY', 'CommunicationServices', NOW()),
(2334468, 'NEXPOINT RESIDENTIAL TR INC', 'CNXRT', 'RealEstate', NOW()),
(2334480, 'SEKISUI HOUSE LTD', 'SKHSY', 'ConsumerDiscretionary', NOW()),
(2334493, 'YAMAHA MOTOR CO LTD', 'YAMHY', 'ConsumerDiscretionary', NOW()),
(2334736, 'PACER DV MK IN CS CW 100 ETF', 'FICOW', 'N/A', NOW()),
(2334992, 'CREXENDO INC', 'CCXDO', 'InformationTechnology', NOW()),
(433610, 'NEW JERSEY ECONOMIC DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(433713, 'NORTHSIDE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(433812, 'OKLAHOMA SCHOOL DISTRICTS', 'None', 'N/A', NOW()),
(433820, 'OLDHAM COUNTY SCHOOL DISTRICT FINANCE CORP', 'None', 'N/A', NOW()),
(434009, 'PENNSYLVANIA HOUSING FINANCE AGENCY', 'None', 'N/A', NOW()),
(434453, 'ROUND ROCK INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(434958, 'STATE OF GEORGIA', 'None', 'N/A', NOW()),
(434980, 'STATE OF NEW YORK MORTGAGE AGENCY', 'None', 'N/A', NOW()),
(434982, 'STATE OF NORTH CAROLINA', 'None', 'N/A', NOW()),
(435199, 'TENNESSEE HOUSING DEVELOPMENT AGENCY', 'None', 'N/A', NOW()),
(435230, 'TEXAS WATER DEVELOPMENT BOARD', 'None', 'N/A', NOW()),
(435496, 'UNIVERSITY OF CINCINNATI', 'None', 'N/A', NOW()),
(435501, 'UNIVERSITY OF MARYLAND', 'None', 'N/A', NOW()),
(435727, 'VIRGINIA RESOURCES AUTHORITY', 'None', 'N/A', NOW()),
(435946, 'W L GORE & ASSOCIATES INC', 'None', 'N/A', NOW()),
(436009, 'YSLETA INDEPENDENT SCHOOL DISTRICT EL PASO COUNTY TEXAS', 'None', 'N/A', NOW()),
(1311252, 'CSPC Pharmaceutical Group Ltd', 'None', 'Healthcare', NOW()),
(2314313, 'KATY INDEPENDENT SCHOOL DISTRICT FORT BEND HARRIS AND WALLER COUNTIES TEXAS', 'None', 'N/A', NOW()),
(2317519, 'WYOMING COMMUNITY DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(2331428, 'AB PRIVATE CREDIT INVESTORS CORP', 'None', 'N/A', NOW()),
(2331979, 'CITY OF FRISCO', 'None', 'N/A', NOW()),
(2333799, 'HOUSTON TEXAS AIRPORT SYSTEM', 'None', 'N/A', NOW()),
(2333804, 'METRO WASHINGTON AIRPORTS AUTH DC', 'None', 'N/A', NOW()),
(2333806, 'NEW HAMPSHIRE HOUSING FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(2333837, 'CITY OF LEANDER TEXAS', 'None', 'N/A', NOW()),
(2333899, 'TIGER GLOBAL CROSSOVER ACCESS LLC', 'None', 'N/A', NOW()),
(2333901, 'CAREBRIDGE', 'None', 'N/A', NOW()),
(2334169, 'STATE OF FLORIDA BOARD OF GOVERNORS', 'None', 'N/A', NOW()),
(2334171, 'INDUSTRIAL DEVELOPMENT AUTHORITY OF MOBILE COUNTY', 'None', 'N/A', NOW()),
(2334175, 'SEVEN BRIDGES STRATEGIC EQUITY FUND LP', 'None', 'N/A', NOW()),
(2334208, 'CONSOLIDATED SCHOOL DISTRICT OF AIKEN COUNTY', 'None', 'N/A', NOW()),
(2334301, 'SPOKANE SCHOOL DISTRICT NO 81 SPOKANE COUNTY WASHINGTON', 'None', 'N/A', NOW()),
(2334413, 'UBIQUITY VENTURES III', 'None', 'N/A', NOW()),
(2334499, 'DEL VALLE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2334534, 'SCHOOL DISTRICT OF LEON COUNTY FLORIDA', 'None', 'N/A', NOW()),
(435101, 'Syneos Health Inc', 'XLV', 'Healthcare', NOW()),
(435130, 'Tandem Diabetes Care Inc', 'DIA', 'Healthcare', NOW()),
(435196, 'Tenet Healthcare Corp', 'XLV', 'Healthcare', NOW()),
(435824, 'Webster Financial Corp', 'XLF', 'Financials', NOW()),
(2334345, 'ENERGY TRANSFER OPERATING LP', 'XLE', 'N/A', NOW()),
(2334426, 'CME SOYBEAN OIL', 'USO', 'N/A', NOW()),
(2334511, 'SOFI TECHNOLOGIES INC', 'XLK', 'Financials', NOW()),
(433627, 'New Residential Investment Corp', 'RITM', 'Financials', NOW()),
(433634, 'New York Community Bancorp Inc', 'NYCB', 'Financials', NOW()),
(433667, 'Nippon Telegraph & Telephone Corp Ntt', 'NTTYY', 'CommunicationServices', NOW()),
(433670, 'Nitori Holdings Co Ltd', 'NCLTY', 'ConsumerDiscretionary', NOW()),
(433684, 'Nordea Bank Abp', 'NRDBY', 'Financials', NOW()),
(433733, 'NOV Inc', 'NOV', 'Energy', NOW()),
(433830, 'Ollie''s Bargain Outlet Holdings Inc', 'OLLI', 'ConsumerDiscretionary', NOW()),
(434043, 'PG&E Corp', 'PCG', 'Utilities', NOW()),
(434089, 'Ping An Insurance Group', 'PNGAY', 'Financials', NOW()),
(434175, 'Primoris Services Corp', 'PRIM', 'Industrials', NOW()),
(434281, 'QuantumScape Corp', 'QS', 'ConsumerDiscretionary', NOW()),
(434308, 'Range Resources Corp', 'RRC', 'Energy', NOW()),
(434355, 'Reinsurance Group of America Inc', 'RGA', 'Financials', NOW()),
(434357, 'Reliance Steel & Aluminum Co', 'RS', 'Materials', NOW()),
(434424, 'Roblox Corp', 'RBLX', 'CommunicationServices', NOW()),
(434474, 'RPM International Inc', 'RPM', 'Materials', NOW()),
(434495, 'Ryman Hospitality Properties Inc', 'RHP', 'RealEstate', NOW()),
(434703, 'Silgan Holdings Inc', 'SLGN', 'Materials', NOW()),
(434752, 'Smurfit Kappa Group PLC', 'SMFKY', 'Materials', NOW()),
(434849, 'SPDR MidCap 400 ETF Trust', 'MDY', 'N/A', NOW()),
(434863, 'SPDR S&P 600 Small Cap Value ETF', 'FSLYV', 'N/A', NOW()),
(434924, 'STAG Industrial Inc', 'STAG', 'RealEstate', NOW()),
(435285, 'Tokyo Electron Ltd', 'TOELY', 'InformationTechnology', NOW()),
(435381, 'Tri Pointe Homes Inc', 'TPH', 'ConsumerDiscretionary', NOW()),
(435452, 'Uni-Charm Corp', 'UNICY', 'ConsumerStaples', NOW()),
(435614, 'Vanguard Mid-Cap ETF', 'ETFVO', 'N/A', NOW()),
(435692, 'Viavi Solutions Inc', 'VIAV', 'InformationTechnology', NOW()),
(435752, 'Vontier Corp', 'VNT', 'InformationTechnology', NOW()),
(435807, 'Waste Connections Inc', 'WCN', 'Industrials', NOW()),
(435871, 'West Japan Railway Company', 'WJRYY', 'Industrials', NOW()),
(2331206, 'VANECK EMERGING MARKETS FUND', 'EMRIX', 'N/A', NOW()),
(2331365, 'Stellantis NV', 'VSTLA', 'ConsumerDiscretionary', NOW()),
(2332051, 'Arch Coal Inc', 'ARCH', 'Materials', NOW()),
(2332120, 'CBIZ Inc', 'CBZ', 'Industrials', NOW()),
(2332221, 'RH', 'RHRH', 'ConsumerDiscretionary', NOW()),
(2332432, 'Arlington Asset Investment Corp', 'AAIC', 'Financials', NOW()),
(2332605, 'Global X Uranium ETF', 'TFURA', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;