INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(432453, 'Insight Enterprises Inc', 'NSIT', 'InformationTechnology', NOW()),
(435914, 'Willis Towers Watson PLC', 'LCWTW', 'Financials', NOW()),
(1734510, 'CF Industries Holdings Inc', 'CF', 'Materials', NOW()),
(432239, 'Henry (Jack) & Associates Inc', 'JKHY', 'Financials', NOW()),
(435895, 'White Mountains Insurance Group Ltd', 'WTM', 'Financials', NOW()),
(433257, 'Match Group Inc', 'MTCH', 'CommunicationServices', NOW()),
(431403, 'eBay Inc', 'EBAY', 'ConsumerDiscretionary', NOW()),
(434714, 'Simpson Manufacturing Co. Inc', 'SSD', 'Industrials', NOW()),
(429803, 'Aramark', 'ARMK', 'ConsumerDiscretionary', NOW()),
(432737, 'Janus Henderson Mortgage-Backed Securities ETF', 'FJMBS', 'N/A', NOW()),
(2334924, 'REDDIT INC', 'CRDDT', 'CommunicationServices', NOW()),
(432311, 'Host Hotels & Resorts Inc', 'HST', 'RealEstate', NOW()),
(435121, 'Takeda Pharmaceutical Co Ltd', 'TAK', 'Healthcare', NOW()),
(429818, 'ARES CAPITAL CORPORATION', 'NARCC', 'Financials', NOW()),
(431700, 'First Citizens BancShares Inc', 'FCNCA', 'Financials', NOW()),
(435192, 'Tempur Sealy International Inc', 'SGI', 'ConsumerDiscretionary', NOW()),
(431199, 'DBS Group Holdings Ltd', 'DBSDY', 'Financials', NOW()),
(431778, 'Five Below Inc', 'FIVE', 'ConsumerDiscretionary', NOW()),
(434247, 'Public Service Enterprise Group Inc', 'PEG', 'Utilities', NOW()),
(2333903, 'ISHARES BB RAT CORP BOND ETF', 'FHYBB', 'N/A', NOW()),
(429655, 'Amdocs Ltd', 'DOX', 'InformationTechnology', NOW()),
(431475, 'Endava PLC', 'CDAVA', 'InformationTechnology', NOW()),
(432352, 'ICF International Inc', 'ICFI', 'Industrials', NOW()),
(435449, 'Under Armour Inc', 'UAA', 'ConsumerDiscretionary', NOW()),
(2334194, 'SPRINGWORKS THERAPEUTICS INC', 'CSWTX', 'Healthcare', NOW()),
(430375, 'Capri Holdings Ltd', 'CPRI', 'ConsumerDiscretionary', NOW()),
(431484, 'Enel Ente Nazionale Per L''Energia Elettrica SPA, Roma', 'ENLAY', 'Utilities', NOW()),
(433915, 'Pacific Premier Bancorp Inc', 'PPBI', 'Financials', NOW()),
(2332314, 'Direxion Shares ETF Trust - Direxion Daily Small Cap Bear 3X Shares', 'TZA', 'N/A', NOW()),
(431235, 'DENTSPLY SIRONA Inc', 'XRAY', 'Healthcare', NOW()),
(432162, 'HARDING LOEVNER INTERNATIONAL EQUITY PORTFOLIO', 'HLMIX', 'N/A', NOW()),
(433628, 'News Corp', 'NWSA', 'CommunicationServices', NOW()),
(434309, 'Rapid7 Inc', 'RPD', 'InformationTechnology', NOW()),
(435849, 'Western Alliance Bancorporation', 'WAL', 'Financials', NOW()),
(2334329, 'SCHNEIDER NATIONAL INC', 'CSNDR', 'Industrials', NOW()),
(429526, 'AGCO Corp', 'AGCO', 'Industrials', NOW()),
(430217, 'BRIDGE BUILDER LARGE CAP GROWTH FUND', 'BBGLX', 'N/A', NOW()),
(431601, 'Exponent Inc', 'EXPO', 'Industrials', NOW()),
(432333, 'Hudson Pacific Properties Inc', 'HPP', 'RealEstate', NOW()),
(434435, 'Rogers Communications Inc', 'RCI', 'CommunicationServices', NOW()),
(435664, 'Veracyte Inc', 'VCYT', 'Healthcare', NOW()),
(2332207, 'CyberArk Software Ltd', 'CYBR', 'InformationTechnology', NOW()),
(2333776, 'UNITY SOFTWARE INC', 'INCU', 'InformationTechnology', NOW()),
(2334605, 'LAZARD INTERNATIONAL STRATEGIC EQUITY PORTFOLIO', 'LISIX', 'N/A', NOW()),
(429595, 'Allegiant Travel Co', 'ALGT', 'Industrials', NOW()),
(430030, 'Banco Bilbao Vizcaya Argentaria SA (BBVA)', 'BBVA', 'Financials', NOW()),
(431167, 'Mercedes-Benz Group AG', 'MBGYY', 'ConsumerDiscretionary', NOW()),
(431656, 'FIDELITY ADVISOR INTERNATIONAL CAPITAL APPRECIATION FUND', 'FCPIX', 'N/A', NOW()),
(432115, 'Grupo Financiero Banorte SA De CV Gfnorte', 'GBOOY', 'Financials', NOW()),
(432572, 'iShares Core MSCI Emerging Markets ETF', 'FIEMG', 'N/A', NOW()),
(433512, 'Murata Manufacturing Co Ltd', 'MRAAY', 'InformationTechnology', NOW()),
(435177, 'Telefonaktiebolaget LM Ericsson', 'ERIC', 'InformationTechnology', NOW()),
(2331363, 'Primo Water Corp', 'PRMW', 'ConsumerStaples', NOW()),
(2331999, 'Fidelity Covington Trust - Fidelity Quality Factor ETF', 'FFQAL', 'N/A', NOW()),
(2334023, 'PROSHARES MSCI EAFE DIV GRWR', 'REFAD', 'N/A', NOW()),
(2334292, 'RENTOKIL INITIAL PLC', 'LCRTO', 'Industrials', NOW()),
(2334528, 'WIRELESS TELECOM GROUP INC', 'NCWTT', 'InformationTechnology', NOW()),
(2335151, 'HYSTER YALE INC', 'INCHY', 'Industrials', NOW()),
(429714, 'Americold Realty Trust', 'COLD', 'RealEstate', NOW()),
(429960, 'AXIS Capital Holdings Ltd', 'AXS', 'Financials', NOW()),
(430412, 'Casey''s General Stores Inc.', 'CASY', 'ConsumerStaples', NOW()),
(431585, 'EVERGY Inc', 'EVRG', 'Utilities', NOW()),
(431712, 'First Industrial Realty Trust Inc', 'FR', 'RealEstate', NOW()),
(432108, 'Group 1 Automotive Inc', 'GPI', 'ConsumerDiscretionary', NOW()),
(432354, 'Ichor Holdings Ltd', 'ICHR', 'InformationTechnology', NOW()),
(432953, 'Landstar System Inc', 'LSTR', 'Industrials', NOW()),
(435186, 'Telstra Corporation Ltd', 'TLSYY', 'CommunicationServices', NOW()),
(435794, 'Washington Federal Inc', 'WAFD', 'Financials', NOW()),
(436011, 'Yum China Holdings Inc', 'YUMC', 'ConsumerDiscretionary', NOW()),
(2331130, 'FIDELITY FLOATING RATE HIGH INCOME FUND', 'FFRHX', 'N/A', NOW()),
(2333078, 'BioCryst Pharmaceuticals Inc', 'BCRX', 'Healthcare', NOW()),
(2333296, 'Digital World Acquisition Corp', 'DWAC', 'CommunicationServices', NOW()),
(2334162, 'PIMCO INVST GRADE CP BD ETF', 'FCORP', 'N/A', NOW()),
(2334279, 'KERRY GROUP PLC', 'KRYAY', 'ConsumerStaples', NOW()),
(2334319, 'SALMAR ASA', 'SALRY', 'ConsumerStaples', NOW()),
(2334384, 'THE ADVISORS INNER CIRCLE FUND WESTWOOD GLOBAL EQUITY FUND', 'WWGEX', 'N/A', NOW()),
(2334819, 'FIRST WATCH RESTAURA GRO INC', 'CFWRG', 'ConsumerDiscretionary', NOW()),
(2335152, 'YIELDMAX MSTR OPTION INCOME STRATEGY ETF', 'FMSTY', 'N/A', NOW()),
(429603, 'AllianceBernstein Holding LP', 'LPAB', 'Financials', NOW()),
(429851, 'ARTISAN INTERNATIONAL VALUE FUND', 'APDKX', 'N/A', NOW()),
(429968, 'BAE Systems PLC', 'BAESY', 'Industrials', NOW()),
(430100, 'Black Knight Inc', 'BKI', 'InformationTechnology', NOW()),
(430224, 'Bright Horizons Family Solutions Inc', 'BFAM', 'ConsumerDiscretionary', NOW()),
(430474, 'Century Casinos Inc', 'CNTY', 'ConsumerDiscretionary', NOW()),
(430551, 'CIE Generale Des Etablissements Michelin SA, Clermont-Ferrand', 'MGDDY', 'ConsumerDiscretionary', NOW()),
(431306, 'Diversey Holdings Ltd', 'DSEY', 'Materials', NOW()),
(431459, 'Emergent BioSolutions Inc', 'EBS', 'Healthcare', NOW()),
(431567, 'ETF Managers Trust - ETFMG Prime Cyber Security ETF', 'FHACK', 'N/A', NOW()),
(431972, 'GFL Environmental Inc', 'GFL', 'Industrials', NOW()),
(432339, 'Huntington Ingalls Industries Inc', 'HII', 'Industrials', NOW()),
(432617, 'iShares Trust - iShares Long-Term Corporate Bond ETF', 'FIGLB', 'N/A', NOW()),
(432888, 'Kingspan Group PLC', 'KGSPY', 'Industrials', NOW()),
(432932, 'Kulicke and Soffa Industries Inc', 'KLIC', 'InformationTechnology', NOW()),
(433273, 'Mazda Motor Corp', 'MZDAY', 'ConsumerDiscretionary', NOW()),
(433508, 'Muenchener Rueckversicherungs-Gesellschaft Aktiengesellschaft In Muenchen', 'MURGY', 'Financials', NOW()),
(433993, 'Pearson PLC', 'LCPSO', 'ConsumerDiscretionary', NOW()),
(434210, 'ProShares Short S&P500', 'SH', 'N/A', NOW()),
(434388, 'Reynolds American Inc', 'RAI', 'ConsumerStaples', NOW()),
(434637, 'SEI Investments Co', 'SEIC', 'Financials', NOW()),
(434742, 'SMART Global Holdings Inc', 'SGH', 'InformationTechnology', NOW())
ON CONFLICT (id) DO NOTHING;