INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(434991, 'STATE OF TENNESSEE', 'None', 'N/A', NOW()),
(434994, 'STATE OF VERMONT', 'None', 'N/A', NOW()),
(434999, 'KENTUCKY STATE PROPERTY AND BUILDINGS COMMISSION', 'None', 'N/A', NOW()),
(435026, 'ST LOUIS COUNTY', 'None', 'N/A', NOW()),
(435127, 'TAMPA BAY WATER', 'None', 'N/A', NOW()),
(434372, 'Resideo Technologies Inc', 'XLK', 'Industrials', NOW()),
(434536, 'Sandstorm Gold Ltd', 'GLD', 'Materials', NOW()),
(434604, 'Scottish and Southern Energy PLC', 'XLE', 'Utilities', NOW()),
(434628, 'The Health Care Select Sector SPDR Fund', 'XLV', 'N/A', NOW()),
(434694, 'Siemens Healthineers AG', 'XLV', 'Healthcare', NOW()),
(434709, 'Silvergate Capital Corporation', 'SLV', 'Financials', NOW()),
(434780, 'Sonic Healthcare Ltd', 'XLV', 'Healthcare', NOW()),
(433902, 'Owens Corning', 'OC', 'Industrials', NOW()),
(433922, 'PacWest Bancorp', 'BANC', 'Financials', NOW()),
(433932, 'Pandora AS', 'PANDY', 'ConsumerDiscretionary', NOW()),
(433955, 'PARNASSUS MID CAP FUND', 'PARMX', 'N/A', NOW()),
(433996, 'Pebblebrook Hotel Trust', 'PEB', 'RealEstate', NOW()),
(434015, 'Penske Automotive Group Inc', 'PAG', 'ConsumerDiscretionary', NOW()),
(434017, 'Penumbra Inc', 'PEN', 'Healthcare', NOW()),
(434057, 'Phillips 66 Partners LP', 'PPSXP', 'Energy', NOW()),
(434104, 'Plains GP Holdings LP', 'PPAGP', 'Energy', NOW()),
(434105, 'Planet Fitness Inc', 'PLNT', 'ConsumerDiscretionary', NOW()),
(434120, 'PNM Resources Inc', 'PNM', 'Utilities', NOW()),
(434132, 'Portland General Electric Co', 'POR', 'Utilities', NOW()),
(434197, 'Progyny Inc', 'PGNY', 'Healthcare', NOW()),
(434213, 'Proshares Trust - ProShares S&P MidCap 400 Dividend Aristocrats ETF', 'FREGL', 'N/A', NOW()),
(434234, 'Prudential PLC', 'LCPUK', 'Financials', NOW()),
(434245, 'Publicis Groupe SA', 'PUBGY', 'CommunicationServices', NOW()),
(434264, 'Qbe Insurance Group Ltd', 'QBIEY', 'Financials', NOW()),
(434305, 'Rambus Inc', 'RMBS', 'InformationTechnology', NOW()),
(434324, 'RealNetworks Inc', 'RNWK', 'InformationTechnology', NOW()),
(434476, 'RPT Realty', 'RPT', 'RealEstate', NOW()),
(434483, 'Rush Enterprises Inc', 'RUSHA', 'Industrials', NOW()),
(434493, 'Ryder System Inc', 'R', 'Industrials', NOW()),
(434511, 'Saia Inc', 'SAIA', 'Industrials', NOW()),
(434513, 'J.Sainsbury PLC', 'JSAIY', 'ConsumerStaples', NOW()),
(434515, 'Compagnie de Saint Gobain SA', 'CODYY', 'Industrials', NOW()),
(434524, 'Sampo PLC', 'SAXPY', 'Financials', NOW()),
(434595, 'Schwab US Dividend Equity ETF', 'FSCHD', 'N/A', NOW()),
(434605, 'The Scotts Miracle-Gro Co', 'SMG', 'Materials', NOW()),
(434659, 'Service Properties Trust', 'SVC', 'RealEstate', NOW()),
(434679, 'Shift4 Payments Inc', 'FOUR', 'Financials', NOW()),
(434702, 'Sika AG, Baar', 'SXYAY', 'Materials', NOW()),
(434716, 'Sinclair Broadcast Group Inc', 'SBGI', 'CommunicationServices', NOW()),
(434717, 'Singapore Telecommunications Ltd', 'SGAPY', 'CommunicationServices', NOW()),
(434724, 'Six Flags Entertainment Corp', 'SIX', 'ConsumerDiscretionary', NOW()),
(434728, 'Svenska Kullagerfabriken Skf AB', 'SKFRY', 'Industrials', NOW()),
(434743, 'Smc Corp', 'SMCAY', 'Industrials', NOW()),
(434781, 'Sonoco Products Co', 'SON', 'Materials', NOW()),
(434782, 'Sonos Inc', 'SONO', 'ConsumerDiscretionary', NOW()),
(434828, 'Spark New Zealand Ltd', 'SPKKY', 'CommunicationServices', NOW()),
(434837, 'SPDR Bloomberg Barclays Short Term High Yield Bond ETF', 'FSJNK', 'N/A', NOW()),
(434865, 'SPDR S&P Bank ETF', 'TFKBE', 'N/A', NOW()),
(434867, 'SPDR S&P Dividend ETF', 'TFSDY', 'N/A', NOW()),
(434881, 'Spectrum Brands Holdings Inc', 'SPB', 'ConsumerStaples', NOW()),
(434941, 'Starz', 'STRZA', 'ConsumerDiscretionary', NOW()),
(435020, 'The St. Joe Co', 'JOE', 'RealEstate', NOW()),
(435032, 'Stratasys Ltd', 'SSYS', 'Industrials', NOW()),
(435064, 'Sun Hung Kai Properties Ltd', 'SUHJY', 'RealEstate', NOW()),
(435067, 'SunPower Corp', 'SPWR', 'Industrials', NOW()),
(435068, 'Sunrun Inc', 'RUN', 'Industrials', NOW()),
(435080, 'Svenska Handelsbanken', 'SVNLY', 'Financials', NOW()),
(435090, 'Swire Pacific Ltd', 'SWRAY', 'Industrials', NOW()),
(435091, 'Swisscom AG, Ittigen', 'SCMWY', 'CommunicationServices', NOW()),
(435092, 'Schweizerische Rueckversicherungs-Gesellschaft, Zuerich', 'SSREY', 'Financials', NOW()),
(435132, 'Tanger Factory Outlet Centers Inc', 'SKT', 'RealEstate', NOW()),
(435145, 'Taylor Morrison Home Corporation', 'TMHC', 'ConsumerDiscretionary', NOW()),
(435171, 'Tekla Life Sciences Investors', 'HQL', 'N/A', NOW()),
(435179, 'Telefonica SA', 'SATEF', 'CommunicationServices', NOW()),
(435188, 'Temenos AG', 'TMSNY', 'InformationTechnology', NOW()),
(435215, 'TEXAS A&M UNIVERSITY', 'None', 'N/A', NOW()),
(435218, 'TEXAS DEPARTMENT OF TRANSPORTATION', 'None', 'N/A', NOW()),
(435371, 'TRI COUNTY METROPOLITAN TRANSPORTATION DISTRICT OF OREGON', 'None', 'N/A', NOW()),
(435378, 'TRINITY RIVER AUTHORITY OF TEXAS', 'None', 'N/A', NOW()),
(435417, 'TURNPIKE AUTHORITY OF KENTUCKY', 'None', 'N/A', NOW()),
(435492, 'UNIVERSITY OF ALABAMA', 'None', 'N/A', NOW()),
(435495, 'UNIVERSITY OF CALIFORNIA', 'None', 'N/A', NOW()),
(435502, 'UNIVERSITY OF MICHIGAN', 'None', 'N/A', NOW()),
(435513, 'UNIVERSITY OF PENNSYLVANIA', 'None', 'N/A', NOW()),
(435517, 'UNIVERSITY OF UTAH', 'None', 'N/A', NOW()),
(435649, 'VANTERRA HPH II LP', 'None', 'N/A', NOW()),
(435725, 'VIRGINIA PUBLIC BUILDING AUTHORITY', 'None', 'N/A', NOW()),
(435798, 'WASHINGTON STATE UNIVERSITY', 'None', 'N/A', NOW()),
(435799, 'WASHINGTON SUBURBAN SANITARY COMMISSION', 'None', 'N/A', NOW()),
(435804, 'WASHOE COUNTY SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(435910, 'WILLIAMSON COUNTY TENNESSEE', 'None', 'N/A', NOW()),
(435911, 'WILLIAMSON COUNTY TEXAS', 'None', 'N/A', NOW()),
(435918, 'WILSON COUNTY TENNESSEE', 'None', 'N/A', NOW()),
(435977, 'WYLIE INDEPENDENT SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(1557310, 'GREATER ALBANY SCHOOL DISTRICT NO 8J LINN AND BENTON COUNTIES OREGON', 'None', 'N/A', NOW()),
(2268972, 'SAN DIEGO COUNTY REGIONAL TRANSPORTATION COMMISSION', 'None', 'N/A', NOW()),
(2278831, 'COUNTY OF WINNEBAGO ILLINOIS', 'None', 'N/A', NOW()),
(2331066, 'SOUTHWEST SUBURBAN SEWER DISTRICT KING COUNTY WASHINGTON', 'None', 'N/A', NOW()),
(2331178, 'SENTERA INC', 'None', 'N/A', NOW()),
(2331184, 'CARDANO', 'None', 'N/A', NOW()),
(2331373, 'COUNTY OF ROANOKE VIRGINIA', 'None', 'N/A', NOW()),
(2331380, 'COUNTY OF DEKALB', 'None', 'N/A', NOW()),
(2331405, 'SALISBURY TOWNSHIP SCHOOL DISTRICT LEHIGH COUNTY PENNSYLVANIA', 'None', 'N/A', NOW()),
(2331445, 'SANS GENE STUDIOS LLC', 'None', 'N/A', NOW()),
(2331489, 'TOWN OF ORONO MAINE', 'None', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;