INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(435681, 'Vertex Pharmaceuticals Inc', 'VRTX', 'Healthcare', NOW()),
(429639, 'Altria Group Inc', 'MO', 'ConsumerStaples', NOW()),
(431879, 'Freeport-McMoRan Inc', 'FCX', 'Materials', NOW()),
(433773, 'NXP Semiconductors NV', 'VNXPI', 'InformationTechnology', NOW()),
(434825, 'CBOE SPX INDEX', 'EXSPX', 'N/A', NOW()),
(431316, 'Dollar Tree Inc', 'DLTR', 'ConsumerStaples', NOW()),
(431352, 'D.R. Horton Inc', 'DHI', 'ConsumerDiscretionary', NOW()),
(434429, 'Rockwell Automation Inc', 'ROK', 'Industrials', NOW()),
(430491, 'Charter Communications Inc', 'CHTR', 'CommunicationServices', NOW()),
(431135, 'CSX Corp', 'CSX', 'Industrials', NOW()),
(431372, 'DuPont  De Nemours Inc', 'DD', 'Materials', NOW()),
(435295, 'The Toronto-Dominion Bank', 'TD', 'Financials', NOW()),
(431262, 'DexCom Inc', 'DXCM', 'Healthcare', NOW()),
(432868, 'KeyCorp', 'KEY', 'Financials', NOW()),
(433147, 'LyondellBasell Industries NV', 'NVLYB', 'Materials', NOW()),
(434554, 'SAP SE', 'SESAP', 'InformationTechnology', NOW()),
(429569, 'Albemarle Corp', 'ALB', 'Materials', NOW()),
(429796, 'Aptiv PLC', 'CAPTV', 'ConsumerDiscretionary', NOW()),
(430944, 'Conagra Brands Inc', 'CAG', 'ConsumerStaples', NOW()),
(432274, 'Hilton Worldwide Holdings Inc', 'HLT', 'ConsumerDiscretionary', NOW()),
(432367, 'IDEXX Laboratories Inc', 'IDXX', 'Healthcare', NOW()),
(433434, 'Moderna Inc', 'MRNA', 'Healthcare', NOW()),
(433790, 'Occidental Petroleum Corp', 'OXY', 'Energy', NOW()),
(435473, 'United Rentals Inc', 'URI', 'Industrials', NOW()),
(432077, 'Graphic Packaging Holding Co', 'GPK', 'Materials', NOW()),
(432482, 'International Flavors & Fragrances Inc', 'IFF', 'Materials', NOW()),
(433493, 'MSCI Inc', 'MSCI', 'Financials', NOW()),
(431370, 'The Dun & Bradstreet Corp', 'DNB', 'Industrials', NOW()),
(434712, 'Simon Property Group Inc', 'SPG', 'RealEstate', NOW()),
(435122, 'Take-Two Interactive Software Inc', 'TTWO', 'CommunicationServices', NOW()),
(435529, 'Urban Outfitters Inc', 'URBN', 'ConsumerDiscretionary', NOW()),
(435886, 'Weyerhaeuser Co', 'WY', 'RealEstate', NOW()),
(429812, 'Archer-Daniels-Midland Co', 'ADM', 'ConsumerStaples', NOW()),
(429992, 'The Bank of New York Mellon Corp', 'BK', 'Financials', NOW()),
(430082, 'Biogen Inc', 'BIIB', 'Healthcare', NOW()),
(430399, 'CarMax Inc', 'KMX', 'ConsumerDiscretionary', NOW()),
(430827, 'The Clorox Co', 'CLX', 'ConsumerStaples', NOW()),
(432993, 'Lennar Corp', 'LEN', 'ConsumerDiscretionary', NOW()),
(433909, 'PACCAR Inc', 'PCAR', 'Industrials', NOW()),
(434004, 'Penn National Gaming Inc', 'PENN', 'ConsumerDiscretionary', NOW()),
(435477, 'United States Steel Corp', 'X', 'Materials', NOW()),
(429957, 'Axalta Coating Systems Ltd', 'AXTA', 'Materials', NOW()),
(429993, 'The Bank of Nova Scotia', 'BNS', 'Financials', NOW()),
(430093, 'BJ''s Wholesale Club Holdings Inc', 'BJ', 'ConsumerStaples', NOW()),
(430403, 'Carrier Global Corp', 'CARR', 'Industrials', NOW()),
(431375, 'Dynatrace Inc', 'DT', 'InformationTechnology', NOW()),
(431835, 'Fortive Corp', 'FTV', 'Industrials', NOW()),
(434278, 'Quanta Services Inc', 'PWR', 'Industrials', NOW()),
(435877, 'West Pharmaceutical Services Inc', 'WST', 'Healthcare', NOW()),
(430019, 'Bayer AG', 'BAYRY', 'Healthcare', NOW()),
(431282, 'Digital Realty Trust Inc', 'DLR', 'RealEstate', NOW()),
(429782, 'Apollo Global Management Inc', 'APO', 'Financials', NOW()),
(431002, 'CoStar Group Inc', 'CSGP', 'RealEstate', NOW()),
(432381, 'Illinois Tool Works Inc', 'ITW', 'Industrials', NOW()),
(432432, 'Ingersoll Rand Inc', 'IR', 'Industrials', NOW()),
(432543, 'Iqvia Holdings Inc', 'IQV', 'Healthcare', NOW()),
(432930, 'The Kroger Co', 'KR', 'ConsumerStaples', NOW()),
(434248, 'Public Storage', 'PSA', 'RealEstate', NOW()),
(435134, 'Tapestry Inc', 'TPR', 'ConsumerDiscretionary', NOW()),
(435166, 'TE Connectivity Ltd', 'TEL', 'InformationTechnology', NOW()),
(2331444, 'MillerKnoll Inc', 'MLKN', 'Industrials', NOW()),
(2334585, 'ISHARES MONTH TREAS BOND ETF', 'FSGOV', 'N/A', NOW()),
(2334903, 'DIREXION DAILY SMALL CAP BULL 3X ETF', 'TFTNA', 'N/A', NOW()),
(432900, 'KLA Corp', 'KLAC', 'InformationTechnology', NOW()),
(433712, 'Northrop Grumman Corp', 'NOC', 'Industrials', NOW()),
(434507, 'Safran SA', 'SAFRY', 'Industrials', NOW()),
(2333561, 'Block Inc', 'SQ', 'Financials', NOW()),
(430155, 'BNP Paribas', 'BNPQY', 'Financials', NOW()),
(430999, 'Corteva Inc', 'CTVA', 'Materials', NOW()),
(431648, 'Ferguson PLC', 'CFERG', 'Industrials', NOW()),
(431977, 'Gilead Sciences Inc', 'GILD', 'Healthcare', NOW()),
(2334051, 'STATE OF MASSACHUSETTS', 'None', 'N/A', NOW()),
(430922, 'COMMONWEALTH OF PENNSYLVANIA', 'None', 'N/A', NOW()),
(579351, 'OHIO WATER DEVELOPMENT AUTHORITY', 'None', 'N/A', NOW()),
(431222, 'Dell Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(431367, 'Duke Energy Corp', 'XLE', 'Utilities', NOW()),
(432516, 'Invesco QQQ Trust Series 1', 'QQQ', 'N/A', NOW()),
(433439, 'Molina Healthcare Inc', 'XLV', 'Healthcare', NOW()),
(433653, 'NGL Energy Partners LP', 'XLE', 'Energy', NOW()),
(429528, 'Agilent Technologies Inc', 'XLK', 'Healthcare', NOW()),
(434446, 'Roper Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(432872, 'Keysight Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(434771, 'SolarEdge Technologies Inc', 'XLK', 'InformationTechnology', NOW()),
(434860, 'SPDR S&P 500 ETF Trust', 'SPY', 'N/A', NOW()),
(2334178, 'GE HEALTHCARE TECHNOLOGI INC', 'XLK', 'Healthcare', NOW()),
(429717, 'Ameriprise Financial Inc', 'XLF', 'Financials', NOW()),
(431260, 'Devon Energy Corp', 'XLE', 'Energy', NOW()),
(430355, 'Canadian Imperial Bank of Commerce', 'DIA', 'Financials', NOW()),
(430479, 'Ceridian HCM Holding Inc', 'DIA', 'Industrials', NOW()),
(432216, 'Healthpeak Properties Inc', 'XLV', 'RealEstate', NOW()),
(433513, 'Murphy Oil Corp', 'USO', 'Energy', NOW()),
(430086, 'Bio-Techne Corp', 'XLK', 'Healthcare', NOW()),
(431270, 'Diageo PLC', 'DIA', 'ConsumerStaples', NOW()),
(432290, 'Hologic Inc', 'HOLX', 'Healthcare', NOW()),
(433624, 'Newmont Corporation', 'NEM', 'Materials', NOW()),
(434171, 'T. Rowe Price Group Inc', 'TROW', 'Financials', NOW()),
(2334504, 'KENVUE INC', 'CKVUE', 'ConsumerStaples', NOW()),
(429760, 'ANSYS Inc', 'ANSS', 'InformationTechnology', NOW()),
(431548, 'Equity Residential', 'EQR', 'RealEstate', NOW()),
(432164, 'Harley-Davidson Inc', 'HOG', 'ConsumerDiscretionary', NOW()),
(432323, 'HP Inc', 'HPQ', 'InformationTechnology', NOW()),
(433889, 'Oshkosh Corp', 'OSK', 'Industrials', NOW()),
(434452, 'Ross Stores Inc', 'ROST', 'ConsumerDiscretionary', NOW()),
(435339, 'The Trade Desk Inc', 'TTD', 'CommunicationServices', NOW()),
(2334843, 'ULTRA CLEAN HOLDINGS INC', 'CUCTT', 'InformationTechnology', NOW()),
(432961, 'Las Vegas Sands Corp', 'LVS', 'ConsumerDiscretionary', NOW()),
(433321, 'MercadoLibre Inc', 'MELI', 'ConsumerDiscretionary', NOW()),
(433464, 'Moody''s Corp.', 'MCO', 'Financials', NOW()),
(433479, 'Motorola Solutions Inc', 'MSI', 'InformationTechnology', NOW()),
(433495, 'M&T Bank Corp', 'MTB', 'Financials', NOW()),
(434226, 'Prosus NV', 'PROSY', 'ConsumerDiscretionary', NOW()),
(435338, 'Tractor Supply Co', 'TSCO', 'ConsumerDiscretionary', NOW()),
(435443, 'Ulta Beauty Inc', 'ULTA', 'ConsumerDiscretionary', NOW()),
(429724, 'AMETEK Inc', 'AME', 'Industrials', NOW()),
(429934, 'AutoZone Inc', 'AZO', 'ConsumerDiscretionary', NOW()),
(430176, 'BorgWarner Inc', 'BWA', 'ConsumerDiscretionary', NOW()),
(431541, 'Equinix Inc', 'EQIX', 'RealEstate', NOW()),
(431687, 'Fifth Third Bancorp', 'FITB', 'Financials', NOW()),
(433385, 'Mid-America Apartment Communities Inc', 'MAA', 'RealEstate', NOW()),
(434023, 'Revvity Inc', 'RVTY', 'Healthcare', NOW()),
(434241, 'PTC Inc', 'PTC', 'InformationTechnology', NOW()),
(435687, 'Paramount Global Inc', 'PSKY', 'CommunicationServices', NOW()),
(435812, 'Waters Corp', 'WAT', 'Healthcare', NOW()),
(430264, 'Brown & Brown Inc', 'BRO', 'Financials', NOW()),
(431539, 'Equifax Inc', 'EFX', 'Industrials', NOW()),
(432306, 'Hormel Foods Corp', 'HRL', 'ConsumerStaples', NOW()),
(432471, 'Intercontinental Exchange Inc', 'ICE', 'Financials', NOW()),
(433013, 'Liberty Broadband Corp', 'LBRDA', 'CommunicationServices', NOW()),
(435436, 'UBS Group AG', 'AGUBS', 'Financials', NOW()),
(435685, 'V.F. Corp', 'VFC', 'ConsumerDiscretionary', NOW()),
(430980, 'Copart Inc', 'CPRT', 'Industrials', NOW()),
(431405, 'Ecolab Inc', 'ECL', 'Materials', NOW()),
(431837, 'Fortune Brands Innovations Inc', 'FBIN', 'Industrials', NOW()),
(431928, 'Gartner Inc', 'IT', 'InformationTechnology', NOW()),
(432485, 'International Paper Co', 'IP', 'Materials', NOW()),
(433073, 'LKQ Corporation', 'LKQ', 'ConsumerDiscretionary', NOW()),
(434373, 'Resmed Inc', 'RMD', 'Healthcare', NOW()),
(434422, 'Robert Half International Inc', 'RHI', 'Industrials', NOW()),
(435694, 'VICI Properties Inc', 'VICI', 'RealEstate', NOW()),
(429991, 'Bank of Montreal', 'BMO', 'Financials', NOW()),
(430400, 'Carnival Corporation & PLC', 'LCCCL', 'ConsumerDiscretionary', NOW()),
(430565, 'Cintas Corp', 'CTAS', 'Industrials', NOW()),
(432061, 'Grainger (W.W.) Inc', 'GWW', 'Industrials', NOW()),
(432240, 'HENRY SCHEIN Inc', 'HSIC', 'Healthcare', NOW()),
(432528, 'Invitation Homes Inc', 'INVH', 'RealEstate', NOW()),
(433448, 'Monolithic Power Systems Inc', 'MPWR', 'InformationTechnology', NOW()),
(433708, 'Northern Trust Corp', 'NTRS', 'Financials', NOW()),
(429888, 'Astrazeneca PLC', 'LCAZN', 'Healthcare', NOW()),
(429936, 'AvalonBay Communities Inc', 'AVB', 'RealEstate', NOW()),
(429978, 'BALL CORPORATION', 'NBALL', 'Materials', NOW()),
(430393, 'Carlisle Cos Inc', 'CSL', 'Industrials', NOW()),
(431626, 'Fastenal Co', 'FAST', 'Industrials', NOW()),
(431722, 'First Solar Inc', 'FSLR', 'InformationTechnology', NOW()),
(432977, 'Lear Corp', 'LEA', 'ConsumerDiscretionary', NOW()),
(433978, 'Paycom Software Inc', 'PAYC', 'Industrials', NOW()),
(434371, 'Republic Services Inc', 'RSG', 'Industrials', NOW()),
(434456, 'Royal Bank of Canada', 'RY', 'Financials', NOW()),
(434800, 'The Southern Co', 'SO', 'Utilities', NOW()),
(430164, 'Boeing Co', 'BA', 'Industrials', NOW()),
(430408, 'Carter''s Inc.', 'CRI', 'ConsumerDiscretionary', NOW()),
(431509, 'Entegris Inc', 'ENTG', 'InformationTechnology', NOW()),
(433900, 'Ovintiv Inc', 'OVV', 'Energy', NOW()),
(2334354, 'CAFFEINATED CAPITAL 2023 ALLOCATE ACCESS FUND LP', 'None', 'N/A', NOW()),
(434130, 'PORT AUTHORITY OF NEW YORK AND NEW JERSEY', 'None', 'N/A', NOW()),
(430715, 'CITY OF NEW YORK', 'None', 'N/A', NOW()),
(430626, 'CITY OF COLUMBUS OHIO', 'None', 'N/A', NOW()),
(433471, 'MORGAN STANLEY FINANCE LLC', 'None', 'N/A', NOW()),
(430577, 'CITY AND COUNTY OF HONOLULU', 'None', 'N/A', NOW()),
(547164, 'SEVEN BRIDGES LONG SHORT EQUITY FUND LTD', 'None', 'N/A', NOW()),
(431304, 'DISTRICT OF COLUMBIA', 'None', 'N/A', NOW()),
(435761, 'Vulcan Materials Co', 'XLB', 'Materials', NOW()),
(430381, 'Cardinal Health Inc', 'XLV', 'Healthcare', NOW()),
(434687, 'Shopify Inc', 'SHOP', 'InformationTechnology', NOW()),
(435558, 'Valero Energy Corp', 'XLE', 'Energy', NOW()),
(2334914, 'BITWISE BITCOIN ETF', 'BTC-USD', 'N/A', NOW()),
(429618, 'Ally Financial Inc', 'XLF', 'Financials', NOW()),
(435079, 'SVB Financial Group', 'XLF', 'Financials', NOW()),
(435545, 'US TREASURY BOND', '^TNX', 'N/A', NOW()),
(2300799, 'JPMORGAN US GOVERNMENT MONEY MARKET FUND', 'JPM', 'N/A', NOW()),
(2333493, 'CME CATTLE', 'T', 'N/A', NOW()),
(433892, 'Otis Worldwide Corp', 'OTIS', 'Industrials', NOW()),
(435691, 'Viatris Inc', 'VTRS', 'Healthcare', NOW()),
(429589, 'Alibaba Group Holding Ltd', 'BABA', 'ConsumerDiscretionary', NOW()),
(432778, 'Johnson Controls International PLC', 'LCJCI', 'Industrials', NOW()),
(433219, 'Markel Corp', 'MKL', 'Financials', NOW()),
(433278, 'McCormick & Co Inc', 'MKC', 'ConsumerStaples', NOW()),
(433540, 'National Fuel Gas Co', 'NFG', 'Utilities', NOW()),
(433584, 'Nestle SA, Cham Und Vevey', 'NSRGY', 'ConsumerStaples', NOW()),
(433878, 'O''Reilly Automotive Inc', 'ORLY', 'ConsumerDiscretionary', NOW()),
(434027, 'Perrigo Co PLC', 'CPRGO', 'Healthcare', NOW()),
(435671, 'VERISK ANALYTICS Inc', 'VRSK', 'Industrials', NOW()),
(429524, 'AFLAC Inc', 'AFL', 'Financials', NOW()),
(430181, 'Boston Properties Inc', 'BXP', 'RealEstate', NOW()),
(430488, 'Charles River Laboratories International Inc', 'CRL', 'Healthcare', NOW()),
(430841, 'CNH Industrial N.V.', 'CNHI', 'Industrials', NOW()),
(431189, 'Datadog Inc', 'DDOG', 'InformationTechnology', NOW()),
(431845, 'Fox Corp', 'FOXA', 'CommunicationServices', NOW()),
(431941, 'General Dynamics Corp', 'GD', 'Industrials', NOW()),
(432321, 'Howmet Aerospace Inc', 'HWM', 'Industrials', NOW()),
(432338, 'Huntington Bancshares Inc', 'HBAN', 'Financials', NOW())
ON CONFLICT (id) DO NOTHING;