INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(2335080, 'SOUNDHOUND AI INC', 'CSOUN', 'InformationTechnology', NOW()),
(2335109, 'ARTISAN HIGH INCOME FUND', 'ARTFX', 'N/A', NOW()),
(2335111, 'RALLIANT CORP', 'RPRAL', 'InformationTechnology', NOW()),
(2335113, 'ON HOLDING AG', 'GONON', 'ConsumerDiscretionary', NOW()),
(2335115, 'AVANTIS INTERNATIONAL SMALL CAP VALUE ETF', 'FAVDV', 'N/A', NOW()),
(2335118, 'APPELL PETROLEUM CORP', 'PAPPL', 'N/A', NOW()),
(2335167, 'BIGBEAR.AI HOLDINGS INC', 'CBBAI', 'InformationTechnology', NOW()),
(2335173, 'BRIDGEBIO PHARMA INC', 'CBBIO', 'Healthcare', NOW()),
(2335174, 'LANDBRIDGE CO LLC', 'LLCLB', 'RealEstate', NOW()),
(2335180, 'BARON ASSET FUND', 'BARIX', 'N/A', NOW()),
(2335181, 'BARON EMERGING MARKETS FUND', 'BEXIX', 'N/A', NOW())
ON CONFLICT (id) DO NOTHING;