INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(435424, 'Twitter Inc', 'TWTR', 'CommunicationServices', NOW()),
(435475, 'United States Oil Fund LP', 'USO', 'N/A', NOW()),
(435591, 'Vanguard Financials ETF', 'XLF', 'N/A', NOW()),
(435603, 'Vanguard Health Care ETF', 'XLV', 'N/A', NOW()),
(435606, 'Vanguard Intermediate-Term Bond ETF', 'DIA', 'N/A', NOW()),
(435612, 'Vanguard Materials ETF', 'XLB', 'N/A', NOW()),
(2320890, 'ISHARES S&P 500 INDEX FUND', 'SPY', 'N/A', NOW()),
(2331190, 'SAN FRANCISCO BAY AREA RAPID TRANSIT DISTRICT', 'CSCO', 'N/A', NOW()),
(2331346, 'FOX VALLEY TECHNICAL COLLEGE DISTRICT', 'XLK', 'N/A', NOW()),
(2331367, 'RUANE CUNNIFF & GOLDFARB INC', 'GLD', 'N/A', NOW()),
(435195, 'Tencent Music Entertainment Group', 'TME', 'CommunicationServices', NOW()),
(435197, 'Tennant Co', 'TNC', 'Industrials', NOW()),
(435208, 'Terna SpA', 'TEZNY', 'Utilities', NOW()),
(435216, 'Texas Capital Bancshares Inc', 'TCBI', 'Financials', NOW()),
(435259, 'TIAA-CREF CORE IMPACT BOND FUND', 'TSBRX', 'N/A', NOW()),
(435301, 'Total System Services Inc', 'TSS', 'InformationTechnology', NOW()),
(435364, 'Trend Micro Inc', 'TMICY', 'InformationTechnology', NOW()),
(435379, 'TripAdvisor Inc', 'TRIP', 'CommunicationServices', NOW()),
(435380, 'Trip com Group Ltd', 'TCOM', 'ConsumerDiscretionary', NOW()),
(435391, 'T ROWE PRICE BALANCED FUND', 'RPBAX', 'N/A', NOW()),
(435448, 'Umpqua Holdings Corp', 'COLB', 'Financials', NOW()),
(435526, 'Upwork Inc', 'UPWK', 'Industrials', NOW()),
(435534, 'USD Partners LP', 'PUSDP', 'Energy', NOW()),
(435561, 'Vale SA', 'AVALE', 'Materials', NOW()),
(435581, 'Vanguard FTSE All-World Ex-US Small-Cap Index Fund ETF', 'TFVSS', 'N/A', NOW()),
(435604, 'Vanguard Whitehall Funds High Dividend Yield ETF', 'TFVYM', 'N/A', NOW()),
(435613, 'Vanguard Mega Cap Growth ETF', 'TFMGK', 'N/A', NOW()),
(435624, 'Vanguard Scottsdale Funds Vanguard Mortgage-Backed Securities ETF', 'FVMBS', 'N/A', NOW()),
(435625, 'Vanguard Scottsdale Funds Vanguard Short-Term Corporate Bond ETF', 'FVCSH', 'N/A', NOW()),
(435630, 'Vanguard Index Funds - Vanguard Small-Cap ETF', 'ETFVB', 'N/A', NOW()),
(435638, 'Vanguard Total International Stock ETF', 'FVXUS', 'N/A', NOW()),
(435642, 'Vanguard Value ETF', 'TFVTV', 'N/A', NOW()),
(435654, 'Varonis Systems Inc', 'VRNS', 'InformationTechnology', NOW()),
(435721, 'Virgin Galactic Holdings Inc', 'SPCE', 'Industrials', NOW()),
(435751, 'Vonovia SE', 'VONOY', 'RealEstate', NOW()),
(435839, 'Wesfarmers Ltd', 'WFAFY', 'ConsumerDiscretionary', NOW()),
(435936, 'WisdomTree Japan Hedged Equity Fund', 'DXJ', 'N/A', NOW()),
(435942, 'WisdomTree U.S. SmallCap Quality Dividend Growth Fund', 'DGRS', 'N/A', NOW()),
(435947, 'Wolters Kluwer NV', 'WTKWY', 'Industrials', NOW()),
(435996, 'Yandex NV', 'VYNDX', 'InformationTechnology', NOW()),
(435998, 'Yara International ASA', 'YARIY', 'Materials', NOW()),
(436012, 'Zalando SE', 'ZLNDY', 'ConsumerDiscretionary', NOW()),
(686931, 'VANGUARD ULTRA SHORT TERM BOND FUND', 'VUSFX', 'N/A', NOW()),
(708134, 'CAPITAL WORLD GROW AND INCOME', 'CWGIX', 'N/A', NOW()),
(1261017, 'Oramed Pharmaceuticals Inc', 'ORMP', 'Healthcare', NOW()),
(1612477, 'PUTNAM ULTRA SHORT DURATION INCOME FUND', 'PSDTX', 'N/A', NOW()),
(2265746, 'DODGE & COX GLOBAL STOCK FUND', 'DODWX', 'N/A', NOW()),
(2291415, 'The Brink''s Co', 'BCO', 'Industrials', NOW()),
(2316750, 'AMERICAN FUNDS THE BOND FUND OF AMERICA', 'ABNDX', 'N/A', NOW()),
(2326592, 'FEDERATED HERMES GOVERNMENT OBLIGATIONS FUND', 'GOIXX', 'N/A', NOW()),
(2331078, 'Vuzix Corp', 'VUZI', 'InformationTechnology', NOW()),
(2331102, 'Revolve Group Inc', 'RVLV', 'ConsumerDiscretionary', NOW()),
(2331108, 'EATON VANCE FLOATING RATE FUND', 'EIBLX', 'N/A', NOW()),
(2331214, 'Allied Esports Entertainment Inc', 'AGAE', 'ConsumerDiscretionary', NOW()),
(2331344, 'FIDELITY BALANCED FUND', 'FBALX', 'N/A', NOW()),
(2331357, 'Brenntag SE', 'BNTGY', 'Industrials', NOW()),
(2331415, 'Katapult Holdings Inc', 'KPLT', 'Financials', NOW()),
(2331427, 'T ROWE PRICE BLUE CHIP GROWTH FUND', 'TRBCX', 'N/A', NOW()),
(2331437, 'WILLIAM BLAIR LARGE CAP GROWTH FUND', 'LCGFX', 'N/A', NOW()),
(2331576, 'ArcBest Corp', 'ARCB', 'Industrials', NOW()),
(2331683, 'IOWA STATE UNIVERSITY', 'None', 'N/A', NOW()),
(2331717, 'UNIVERSITY OF TEXAS SYSTEM', 'None', 'N/A', NOW()),
(2331893, 'SCHOOL DISTRICT OF PALM BEACH COUNTY FLORIDA', 'None', 'N/A', NOW()),
(2332001, 'LEE COUNTY SOUTHWEST FLORIDA', 'None', 'N/A', NOW()),
(2332025, 'KKR GROUP FINANCE CO IX LLC', 'None', 'N/A', NOW()),
(2332420, 'TOBACCO SETTLEMENT FINANCING CORP', 'None', 'N/A', NOW()),
(2332454, 'EL CAMINO COMMUNITY COLLEGE DISTRICT', 'None', 'N/A', NOW()),
(2332516, 'WOOSTER CITY SCHOOL DISTRICT WAYNE COUNTY OHIO', 'None', 'N/A', NOW()),
(2332779, 'CITY OF DUBLIN OHIO', 'None', 'N/A', NOW()),
(2333119, 'PORT OF TACOMA', 'None', 'N/A', NOW()),
(2333130, 'VIRGINIA PORT AUTHORITY', 'None', 'N/A', NOW()),
(2333279, 'WALTON INVESTMENTS INC', 'None', 'N/A', NOW()),
(2333477, 'CIBOLO CREEK MUNICIPAL AUTHORITY', 'None', 'N/A', NOW()),
(2333496, 'CME WHEAT', 'None', 'N/A', NOW()),
(2333617, 'LANCASTER COUNTY NEBRASKA', 'None', 'N/A', NOW()),
(2333633, 'TACOMBI HOLDING NA LLC', 'None', 'N/A', NOW()),
(2333656, 'KAYNE ANDERSON SMALL CAP QUALITY VALUE PORTFOLIO', 'None', 'N/A', NOW()),
(2333663, 'WINSLOW LARGE CAP GROWTH PORTFOLIO', 'None', 'N/A', NOW()),
(2333735, 'Match Group Inc -OLD', 'None', 'CommunicationServices', NOW()),
(2333779, 'WADSWORTH CITY SCHOOL DISTRICT OHIO', 'None', 'N/A', NOW()),
(2333788, 'FAIRFAX COUNTY PUBLIC SCHOOLS', 'None', 'N/A', NOW()),
(2333848, 'COUNTY OF MUSKEGON STATE OF MICHIGAN', 'None', 'N/A', NOW()),
(2333890, 'COMAL COUNTY TEXAS', 'None', 'N/A', NOW()),
(2333914, 'MISSISSIPPI STATE UNIVERSITY', 'None', 'N/A', NOW()),
(2333951, 'GALVESTON COUNTY TEXAS', 'None', 'N/A', NOW()),
(2333953, 'CERRITOS COMMUNITY COLLEGE DISTRICT LOS ANGELES COUNTY CALIFORNIA', 'None', 'N/A', NOW()),
(2333954, 'MAMMOTH UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2333955, 'SAN MATEO UNION HIGH SCHOOL DISTRICT SAN MATEO COUNTY CALIFORNIA', 'None', 'N/A', NOW()),
(2333966, 'CITY OF QUINCY MASSACHUSETTS', 'None', 'N/A', NOW()),
(2333979, 'LODI UNIFIED SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2333984, 'ABDIEL QUALIFIED ONSHORE PARTNERS LP', 'None', 'N/A', NOW()),
(2334000, 'UNION-ENDICOTT CENTRAL SCHOOL DISTRICT', 'None', 'N/A', NOW()),
(2332435, 'TEXAS TECH UNIVERSITY', 'XLK', 'N/A', NOW()),
(2333516, 'Zoom Technologies Inc', 'ZM', 'InformationTechnology', NOW()),
(2333564, 'Principal Healthcare Innovators ETF', 'XLV', 'N/A', NOW()),
(2333628, 'Global Medical REIT Inc', 'VNQ', 'RealEstate', NOW()),
(2333657, 'NEUBERGER BERMAN INTERNATIONAL ADR PORTFOLIO', 'UBER', 'N/A', NOW()),
(2333935, 'CANO HEALTH INC', 'XLV', 'Healthcare', NOW()),
(2334025, 'INVESCO S&P 500 GARP ETF', 'SPY', 'N/A', NOW()),
(2331581, 'Arrowhead Pharmaceuticals Inc', 'ARWR', 'Healthcare', NOW())
ON CONFLICT (id) DO NOTHING;