INSERT INTO "Issuer" (id, name, ticker, sector, created_at) VALUES
(433382, 'Microsoft Corp', 'MSFT', 'InformationTechnology', NOW()),
(429622, 'Alphabet Inc', 'GOOGL', 'CommunicationServices', NOW()),
(433770, 'NVIDIA Corporation', 'NVDA', 'InformationTechnology', NOW()),
(429789, 'Apple Inc', 'AAPL', 'InformationTechnology', NOW()),
(432796, 'JPMorgan Chase & Co', 'JPM', 'Financials', NOW()),
(431610, 'Meta Platforms Inc', 'META', 'CommunicationServices', NOW()),
(435467, 'Unitedhealth Group Inc', 'UNH', 'Healthcare', NOW()),
(2264488, 'Berkshire Hathaway Inc', 'BRK.B', 'Financials', NOW()),
(2334591, 'JPMORGAN 100% US TREASURY SECURITIES MONEY MARKET FUND', 'JPM', 'N/A', NOW()),
(429495, 'Adobe Inc', 'ADBE', 'InformationTechnology', NOW()),
(435735, 'Visa Inc', 'V', 'Financials', NOW()),
(435211, 'Tesla Inc', 'TSLA', 'ConsumerDiscretionary', NOW()),
(435546, 'US TREASURY NOTE', '^TNX', 'N/A', NOW()),
(432782, 'Johnson & Johnson', 'JNJ', 'Healthcare', NOW()),
(429988, 'Bank of America Corp', 'BAC', 'Financials', NOW()),
(433323, 'Merck & Co Inc', 'MRK', 'Healthcare', NOW()),
(431303, 'The Walt Disney Co', 'DIS', 'CommunicationServices', NOW()),
(432293, 'The Home Depot Inc', 'HD', 'ConsumerDiscretionary', NOW()),
(434517, 'salesforce.com Inc', 'CRM', 'InformationTechnology', NOW()),
(430911, 'Comcast Corp', 'CMCSA', 'CommunicationServices', NOW()),
(433036, 'Eli Lilly and Co', 'LLY', 'Healthcare', NOW()),
(432464, 'Intel Corp', 'INTC', 'InformationTechnology', NOW()),
(434041, 'Pfizer Inc', 'PFE', 'Healthcare', NOW()),
(434191, 'The Procter & Gamble Co', 'PG', 'ConsumerStaples', NOW()),
(429443, 'AbbVie Inc', 'ABBV', 'Healthcare', NOW()),
(433589, 'Netflix Inc', 'NFLX', 'CommunicationServices', NOW()),
(435673, 'Verizon Communications Inc', 'VZ', 'CommunicationServices', NOW()),
(433381, 'Micron Technology Inc', 'XLK', 'InformationTechnology', NOW()),
(430852, 'The Coca-Cola Co', 'KO', 'ConsumerStaples', NOW()),
(433254, 'Mastercard Inc', 'MA', 'Financials', NOW()),
(429914, 'AT&T Inc', 'T', 'CommunicationServices', NOW()),
(431156, 'CVS Health Corp', 'XLV', 'Healthcare', NOW()),
(435403, 'Truist Financial Corp', 'XLF', 'Financials', NOW()),
(435432, 'Uber Technologies Inc', 'UBER', 'Industrials', NOW()),
(432035, 'The Goldman Sachs Group Inc', 'GLD', 'Financials', NOW()),
(429793, 'Applied Materials Inc', 'XLB', 'InformationTechnology', NOW()),
(429765, 'Elevance Health Inc', 'XLV', 'Healthcare', NOW()),
(430368, 'Capital One Financial Corp', 'XLF', 'Financials', NOW()),
(430515, 'Chevron Corp', 'CVX', 'Energy', NOW()),
(431424, 'Elanco Animal Health Inc', 'XLV', 'Healthcare', NOW()),
(433865, 'Oracle Corp', 'ORCL', 'InformationTechnology', NOW()),
(435777, 'Walmart Inc', 'WMT', 'ConsumerStaples', NOW()),
(1282836, 'Wells Fargo & Co', 'WFC', 'Financials', NOW()),
(430431, 'CBOE MINI SPX INDEX', 'EXXSP', 'N/A', NOW()),
(429469, 'Accenture PLC', 'LCACN', 'InformationTechnology', NOW()),
(430239, 'Broadcom Inc', 'AVGO', 'InformationTechnology', NOW()),
(435219, 'Texas Instruments Inc', 'TXN', 'InformationTechnology', NOW()),
(434019, 'PepsiCo Inc', 'PEP', 'ConsumerStaples', NOW()),
(434933, 'Starbucks Corp', 'SBUX', 'ConsumerDiscretionary', NOW()),
(429442, 'Abbott Laboratories', 'ABT', 'Healthcare', NOW()),
(430570, 'Citigroup Inc', 'C', 'Financials', NOW()),
(429505, 'Advanced Micro Devices Inc', 'AMD', 'InformationTechnology', NOW()),
(434591, 'Schwab (Charles) Corp', 'SCHW', 'Financials', NOW()),
(435244, 'Thermo Fisher Scientific Inc', 'TMO', 'Healthcare', NOW()),
(435472, 'United Parcel Service Inc', 'UPS', 'Industrials', NOW()),
(433469, 'Morgan Stanley', 'MS', 'Financials', NOW()),
(429769, 'Aon PLC', 'LCAON', 'Financials', NOW()),
(430423, 'Caterpillar Inc', 'CAT', 'Industrials', NOW()),
(433048, 'Linde PLC', 'LCLIN', 'Materials', NOW()),
(432337, 'Humana Inc', 'HUM', 'Healthcare', NOW()),
(432490, 'Intuit Inc', 'INTU', 'InformationTechnology', NOW()),
(431181, 'Danaher Corp', 'DHR', 'Healthcare', NOW()),
(435137, 'Target Corp', 'TGT', 'ConsumerStaples', NOW()),
(430016, 'Baxter International Inc', 'BAX', 'Healthcare', NOW()),
(433658, 'Nike Inc', 'NKE', 'ConsumerDiscretionary', NOW()),
(431003, 'Costco Wholesale Corp', 'COST', 'ConsumerStaples', NOW()),
(436024, 'Zoetis Inc', 'ZTS', 'Healthcare', NOW()),
(435459, 'Union Pacific Corp', 'UNP', 'Industrials', NOW()),
(429822, 'Arista Networks Inc', 'ANET', 'InformationTechnology', NOW()),
(430955, 'ConocoPhillips', 'COP', 'Energy', NOW()),
(434658, 'ServiceNow Inc', 'NOW', 'InformationTechnology', NOW()),
(432951, 'Lam Research Corp', 'LRCX', 'InformationTechnology', NOW()),
(434275, 'QUALCOMM Inc', 'QCOM', 'InformationTechnology', NOW()),
(430117, 'Blackrock Inc', 'BLK', 'Financials', NOW()),
(433309, 'Medtronic PLC', 'LCMDT', 'Healthcare', NOW()),
(429867, 'ASML Holding NV', 'VASML', 'InformationTechnology', NOW()),
(430534, 'Chipotle Mexican Grill Inc', 'CMG', 'ConsumerDiscretionary', NOW()),
(432480, 'International Business Machines Corp', 'IBM', 'InformationTechnology', NOW()),
(430172, 'Booking Holdings Inc', 'BKNG', 'ConsumerDiscretionary', NOW()),
(431675, 'Fidelity National Information Services Inc', 'FIS', 'Financials', NOW()),
(433279, 'McDonald''s Corp', 'MCD', 'ConsumerDiscretionary', NOW()),
(429617, 'The Allstate Corporation', 'ALL', 'Financials', NOW()),
(430820, 'Cleveland-Cliffs Inc', 'CLF', 'Materials', NOW()),
(431645, 'FedEx Corp', 'FDX', 'Industrials', NOW()),
(433121, 'Lowe''s Cos Inc', 'LOW', 'ConsumerDiscretionary', NOW()),
(434678, 'The Sherwin-Williams Co', 'SHW', 'Materials', NOW()),
(1734484, 'Centene Corp', 'CNC', 'Healthcare', NOW()),
(429700, 'American International Group Inc', 'AIG', 'Financials', NOW()),
(431426, 'ELCM2 LLC', 'None', 'N/A', NOW()),
(434983, 'STATE OF OHIO', 'None', 'N/A', NOW()),
(2334916, 'MH BUILT TO LAST LLC', 'None', 'N/A', NOW()),
(2334865, 'NOT FADE AWAY LLC', 'None', 'N/A', NOW()),
(2334500, 'MAYS ALLOCATE LP', 'None', 'N/A', NOW()),
(433633, 'NEW YORK CITY TRANSITIONAL FINANCE AUTHORITY', 'None', 'N/A', NOW()),
(434996, 'STATE OF WASHINGTON', 'None', 'N/A', NOW()),
(434652, 'Sensata Technologies Holding PLC', 'XLK', 'Industrials', NOW()),
(434094, 'Pinterest Inc', 'PINS', 'CommunicationServices', NOW()),
(434118, 'The PNC Financial Services Group Inc', 'XLF', 'Financials', NOW()),
(429542, 'Airbnb Inc', 'ABNB', 'ConsumerDiscretionary', NOW()),
(434919, 'SS&C Technologies Holdings Inc', 'XLK', 'Industrials', NOW())
ON CONFLICT (id) DO NOTHING;