name: Daily Data Scrape

on:
  schedule:
    # Run at 9pm, 10pm, and 1am HKT (Hong Kong Time)
    # 9pm HKT = 1pm UTC, 10pm HKT = 2pm UTC, 1am HKT = 5pm UTC (previous day)
    - cron: '0 13 * * *'  # 9pm HKT
    - cron: '0 14 * * *'  # 10pm HKT  
    - cron: '0 17 * * *'  # 1am HKT
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd web
        npm install
        
    - name: Run daily scrape
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        cd web
        node scripts/daily-scrape.js
        
    - name: Notify on success
      if: success()
      run: echo "✅ Daily scrape completed successfully"
      
    - name: Notify on failure
      if: failure()
      run: echo "❌ Daily scrape failed"
