INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('433279', 'McDonald''s Corp', 'MCD') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('433121', 'Lowe''s Cos Inc', 'LOW') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('430093', 'BJ''s Wholesale Club Holdings Inc', 'BJ') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('433464', 'Moody''s Corp.', 'MCO') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('430408', 'Carter''s Inc.', 'CRI') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('433878', 'O''Reilly Automotive Inc', 'ORLY') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('430518', 'CHICAGO O''HARE AIRPORT', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('431323', 'Domino''s Pizza Inc', 'DPZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('433106', 'L''Oreal S.A., Paris', 'LRLCY') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('431484', 'Enel Ente Nazionale Per L''Energia Elettrica SPA, Roma', 'ENLAY') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('430412', 'Casey''s General Stores Inc.', 'CASY') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('433830', 'Ollie''s Bargain Outlet Holdings Inc', 'OLLI') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('431276', 'Dick''s Sporting Goods Inc.', 'DKS') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('432939', 'L''Air Liquide SA', 'AIQUY') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('2335095', 'L''ANSE CREUSE PUBLIC SCHOOLS COUNTY OF MACOMB STATE OF MICHIGAN', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('430548', 'Chuy''s Holdings Inc', 'CHUY') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('432913', 'Kohl''s Corp', 'KSS') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('432997', 'Leslie''s Inc', 'LESL') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('433157', 'Macy''s Inc', 'M') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('2291415', 'The Brink''s Co', 'BCO') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Issuer" ("id", "name", "ticker") VALUES ('2334363', 'CONN''S INC', 'CCONN') ON CONFLICT (id) DO NOTHING;